import { PhotographerProfile, Review } from "@/types";
import { locations } from "./locations-data";

export const demoPhotographers: PhotographerProfile[] = [
  {
    id: "1",
    user_id: "u1",
    slug: "maria-santos",
    display_name: "Maria Santos",
    tagline: "Capturing Lisbon's soul through light and emotion",
    bio: "Born and raised in Lisbon, I've spent 8 years photographing this city's magic. I specialize in couples and engagement shoots, using the golden hour light that makes Lisbon glow. My style is natural, warm, and cinematic — I want your photos to feel like a movie scene. Fluent in English, Portuguese, and Spanish.",
    avatar_url: null,
    cover_url: null,
    languages: ["English", "Portuguese", "Spanish"],
    hourly_rate: 180,
    currency: "EUR",
    locations: [locations[0], locations[3]], // Lisbon, Sintra
    packages: [
      {
        id: "p1",
        name: "Quick Capture",
        description: "Perfect for a quick portrait session at one location",
        duration_minutes: 30,
        num_photos: 15,
        price: 120,
        is_popular: false,
      },
      {
        id: "p2",
        name: "Golden Hour",
        description: "Our most popular package — 1 hour at 1-2 locations during golden hour",
        duration_minutes: 60,
        num_photos: 40,
        price: 220,
        is_popular: true,
      },
      {
        id: "p3",
        name: "Full Experience",
        description: "Extended session covering multiple iconic locations",
        duration_minutes: 120,
        num_photos: 80,
        price: 380,
        is_popular: false,
      },
    ],
    experience_years: 8,
    is_verified: true,
    is_featured: true,
    plan: "premium",
    rating: 4.9,
    review_count: 47,
    session_count: 156,
    created_at: "2024-01-15",
  },
  {
    id: "2",
    user_id: "u2",
    slug: "tiago-ferreira",
    display_name: "Tiago Ferreira",
    tagline: "Your story, Porto's beauty — let's create magic",
    bio: "I'm a Porto-based photographer with a passion for storytelling. Every photoshoot is unique because every person has a different story. I love working with couples, families, and solo travelers who want authentic, non-posed photos that capture real emotions. I know every hidden corner of Porto and the Douro Valley.",
    avatar_url: null,
    cover_url: null,
    languages: ["English", "Portuguese", "French"],
    hourly_rate: 160,
    currency: "EUR",
    locations: [locations[1]], // Porto
    packages: [
      {
        id: "p4",
        name: "Porto Essentials",
        description: "1 hour session in Porto's most iconic spots",
        duration_minutes: 60,
        num_photos: 35,
        price: 180,
        is_popular: true,
      },
      {
        id: "p5",
        name: "Porto & Wine",
        description: "2 hour session including port wine cellars and Ribeira",
        duration_minutes: 120,
        num_photos: 70,
        price: 320,
        is_popular: false,
      },
    ],
    experience_years: 6,
    is_verified: true,
    is_featured: false,
    plan: "pro",
    rating: 4.8,
    review_count: 32,
    session_count: 98,
    created_at: "2024-03-20",
  },
  {
    id: "3",
    user_id: "u3",
    slug: "ana-costa",
    display_name: "Ana Costa",
    tagline: "Beach, cliffs, and the Algarve's golden light",
    bio: "Living in the Algarve for 10 years has given me an intimate knowledge of every beach, cliff, and hidden cove along this stunning coastline. I specialize in outdoor photography — couples, families, proposals, and elopements. The dramatic Algarve landscape is my studio, and I know exactly when and where to capture the most breathtaking light.",
    avatar_url: null,
    cover_url: null,
    languages: ["English", "Portuguese"],
    hourly_rate: 200,
    currency: "EUR",
    locations: [locations[2]], // Algarve
    packages: [
      {
        id: "p6",
        name: "Sunset Session",
        description: "1 hour golden hour session on the cliffs or beach",
        duration_minutes: 60,
        num_photos: 40,
        price: 200,
        is_popular: true,
      },
      {
        id: "p7",
        name: "Algarve Explorer",
        description: "3 hour session visiting multiple stunning locations",
        duration_minutes: 180,
        num_photos: 100,
        price: 480,
        is_popular: false,
      },
    ],
    experience_years: 10,
    is_verified: true,
    is_featured: true,
    plan: "premium",
    rating: 5.0,
    review_count: 61,
    session_count: 210,
    created_at: "2023-11-01",
  },
  {
    id: "4",
    user_id: "u4",
    slug: "pedro-oliveira",
    display_name: "Pedro Oliveira",
    tagline: "Sintra's fairytale photographer",
    bio: "Sintra is where fairy tales come alive, and my job is to put you in the story. I've been photographing in Sintra for 5 years and know the best times to visit each palace, the secret paths through the forests, and the viewpoints that will take your breath away. My style is romantic, dreamy, and editorial.",
    avatar_url: null,
    cover_url: null,
    languages: ["English", "Portuguese", "Italian"],
    hourly_rate: 170,
    currency: "EUR",
    locations: [locations[0], locations[3], locations[5]], // Lisbon, Sintra, Cascais
    packages: [
      {
        id: "p8",
        name: "Palace Session",
        description: "1 hour at one of Sintra's magical palaces",
        duration_minutes: 60,
        num_photos: 35,
        price: 190,
        is_popular: true,
      },
      {
        id: "p9",
        name: "Fairytale Tour",
        description: "3 hour session covering Pena Palace, Regaleira & more",
        duration_minutes: 180,
        num_photos: 90,
        price: 450,
        is_popular: false,
      },
    ],
    experience_years: 5,
    is_verified: true,
    is_featured: false,
    plan: "pro",
    rating: 4.9,
    review_count: 28,
    session_count: 87,
    created_at: "2024-02-10",
  },
  {
    id: "5",
    user_id: "u5",
    slug: "sofia-mendes",
    display_name: "Sofia Mendes",
    tagline: "Adventure & nature photography in Madeira",
    bio: "Madeira's dramatic landscapes are my playground. From shooting above the clouds at Pico do Arieiro to the lush levada trails and volcanic coastline, I create photos that capture the raw beauty of this island. Perfect for adventure-loving couples and families who want something different from the typical tourist photos.",
    avatar_url: null,
    cover_url: null,
    languages: ["English", "Portuguese", "German"],
    hourly_rate: 150,
    currency: "EUR",
    locations: [locations[4]], // Madeira
    packages: [
      {
        id: "p10",
        name: "Island Moments",
        description: "1 hour session at a stunning Madeira location",
        duration_minutes: 60,
        num_photos: 35,
        price: 160,
        is_popular: true,
      },
      {
        id: "p11",
        name: "Madeira Adventure",
        description: "Half-day adventure shoot across the island's highlights",
        duration_minutes: 240,
        num_photos: 120,
        price: 550,
        is_popular: false,
      },
    ],
    experience_years: 7,
    is_verified: true,
    is_featured: false,
    plan: "pro",
    rating: 4.8,
    review_count: 19,
    session_count: 64,
    created_at: "2024-05-01",
  },
  {
    id: "6",
    user_id: "u6",
    slug: "ricardo-almeida",
    display_name: "Ricardo Almeida",
    tagline: "Capturing moments where the Atlantic meets the Azores",
    bio: "The Azores are unlike anywhere else on Earth, and I've been lucky to call these islands home for my entire life. I photograph at crater lakes, hot springs, tea plantations, and volcanic coastlines. My style emphasizes the epic scale of nature while keeping you as the hero of the story.",
    avatar_url: null,
    cover_url: null,
    languages: ["English", "Portuguese"],
    hourly_rate: 140,
    currency: "EUR",
    locations: [locations[6]], // Azores
    packages: [
      {
        id: "p12",
        name: "Azores Classic",
        description: "1 hour session at Sete Cidades or another iconic spot",
        duration_minutes: 60,
        num_photos: 35,
        price: 150,
        is_popular: true,
      },
      {
        id: "p13",
        name: "Island Discovery",
        description: "3 hour multi-location adventure across São Miguel",
        duration_minutes: 180,
        num_photos: 90,
        price: 380,
        is_popular: false,
      },
    ],
    experience_years: 9,
    is_verified: true,
    is_featured: true,
    plan: "premium",
    rating: 4.9,
    review_count: 24,
    session_count: 78,
    created_at: "2024-01-20",
  },
];

export const demoReviews: Review[] = [
  {
    id: "r1",
    booking_id: "b1",
    client_id: "c1",
    photographer_id: "1",
    client_name: "Sarah Thompson",
    client_avatar: null,
    rating: 5,
    title: "Absolutely magical experience!",
    text: "Maria made us feel so comfortable from the very first minute. She took us to spots in Alfama that we never would have found on our own. The photos are incredible — warm, natural, and so full of life. We've already recommended her to three friends traveling to Lisbon!",
    photos: [],
    photos_public: false,
    is_verified: true,
    created_at: "2025-01-15",
  },
  {
    id: "r2",
    booking_id: "b2",
    client_id: "c2",
    photographer_id: "1",
    client_name: "James & Emily Park",
    client_avatar: null,
    rating: 5,
    title: "Best investment of our trip",
    text: "We booked the Golden Hour package for our anniversary and it was worth every cent. Maria captured the Lisbon sunset perfectly and our photos look like they belong in a travel magazine. The turnaround was fast too — we had our edited photos within 3 days.",
    photos: [],
    photos_public: false,
    is_verified: true,
    created_at: "2025-02-20",
  },
  {
    id: "r3",
    booking_id: "b3",
    client_id: "c3",
    photographer_id: "3",
    client_name: "The Williams Family",
    client_avatar: null,
    rating: 5,
    title: "Amazing with kids!",
    text: "Ana was incredible with our two young children. She turned the photoshoot into a fun adventure on the beach, and the kids were actually smiling and laughing in every photo. The cliffs in the background are stunning. These photos will be on our wall forever.",
    photos: [],
    photos_public: false,
    is_verified: true,
    created_at: "2025-03-05",
  },
];

export function getPhotographerBySlug(slug: string): PhotographerProfile | undefined {
  return demoPhotographers.find((p) => p.slug === slug);
}

export function getReviewsForPhotographer(photographerId: string): Review[] {
  return demoReviews.filter((r) => r.photographer_id === photographerId);
}
