import type { LocationExplorerRegion } from "./location-explorer-data";

/**
 * Spanish region data for the locations explorer.
 *
 * Hand-written alongside `location-hierarchy-es.ts` from the same slug list —
 * the generated version inherited Portuguese slugs and matched nothing.
 */

export const LOCATION_EXPLORER_REGIONS_ES: LocationExplorerRegion[] = [
  {
    slug: "catalonia",
    name: "Catalonia",
    names: {"es":"Cataluña","de":"Katalonien","fr":"Catalogne"},
    shortName: "Barcelona",
    scope: "mainland",
    center: [2.17, 41.6],
    mapZoom: 7.6,
    summary: "Gaudí facades, Gothic alleys, vineyard hinterland and the pine-backed coves of the Costa Brava.",
    bestFor: ["Couples", "Family", "Proposal", "Solo"],
    vibes: ["City", "Coast", "Historic"],
    highlight: "Most backdrops per square kilometre in Spain",
    photographerHref: "/photographers?location=catalonia",
    children: [
      { slug: "barcelona", name: "Barcelona", names: {"fr":"Barcelone"}, type: "City" },
      { slug: "sitges", name: "Sitges", type: "City" },
      { slug: "girona", name: "Girona", names: {"es":"Girona","fr":"Gérone"}, type: "City" },
      { slug: "costa-brava", name: "Costa Brava", type: "Region" },
    ],
  },
  {
    slug: "madrid-region",
    name: "Madrid & Central Spain",
    names: {"en":"Madrid & Central Spain","es":"Madrid y el centro de España","de":"Madrid & Zentralspanien","fr":"Madrid et le centre de l'Espagne"},
    shortName: "Madrid",
    scope: "mainland",
    center: [-3.9, 40.3],
    mapZoom: 7.4,
    summary: "Grand boulevards, royal parks and two walled cities half an hour away by fast train.",
    bestFor: ["Couples", "Family", "Proposal", "Solo"],
    vibes: ["City", "Historic"],
    highlight: "Sunset at Templo de Debod is the country's proposal spot",
    photographerHref: "/photographers?location=madrid-region",
    children: [
      { slug: "madrid", name: "Madrid", type: "City" },
      { slug: "toledo", name: "Toledo", names: {"fr":"Tolède"}, type: "City" },
      { slug: "segovia", name: "Segovia", names: {"fr":"Ségovie"}, type: "City" },
    ],
  },
  {
    slug: "andalusia",
    name: "Andalusia",
    names: {"es":"Andalucía","de":"Andalusien","fr":"Andalousie"},
    shortName: "Andalusia",
    scope: "mainland",
    center: [-4.9, 37.2],
    mapZoom: 6.8,
    summary: "Moorish palaces, whitewashed hill towns, a 120-metre gorge and the Costa del Sol beneath it all.",
    bestFor: ["Couples", "Proposal", "Honeymoon", "Family"],
    vibes: ["Historic", "Coast", "Dramatic"],
    highlight: "Strongest proposal and honeymoon market in the country",
    photographerHref: "/photographers?location=andalusia",
    children: [
      { slug: "seville", name: "Seville", names: {"es":"Sevilla","de":"Sevilla","fr":"Séville"}, type: "City" },
      { slug: "granada", name: "Granada", names: {"fr":"Grenade"}, type: "City" },
      { slug: "malaga", name: "Málaga", names: {"fr":"Malaga"}, type: "City" },
      { slug: "marbella", name: "Marbella", type: "City" },
      { slug: "ronda", name: "Ronda", type: "City" },
      { slug: "cordoba", name: "Córdoba", names: {"de":"Cordoba","fr":"Cordoue"}, type: "City" },
      { slug: "cadiz", name: "Cádiz", names: {"de":"Cadiz","fr":"Cadix"}, type: "City" },
    ],
  },
  {
    slug: "balearic-islands",
    name: "Balearic Islands",
    names: {"es":"Islas Baleares","de":"Balearen","fr":"Îles Baléares"},
    shortName: "Balearics",
    scope: "islands",
    center: [2.9, 39.4],
    mapZoom: 7.2,
    summary: "Sandstone cathedrals over the water, terraced mountains and coves reached on foot.",
    bestFor: ["Honeymoon", "Couples", "Family"],
    vibes: ["Coast", "Island", "Luxury"],
    highlight: "Spain's strongest wedding and honeymoon islands",
    photographerHref: "/photographers?location=balearic-islands",
    children: [
      { slug: "mallorca", name: "Mallorca", names: {"fr":"Majorque"}, type: "Island" },
      { slug: "ibiza", name: "Ibiza", type: "Island" },
      { slug: "menorca", name: "Menorca", names: {"fr":"Minorque"}, type: "Island" },
    ],
  },
  {
    slug: "canary-islands",
    name: "Canary Islands",
    names: {"es":"Islas Canarias","de":"Kanarische Inseln","fr":"Îles Canaries"},
    shortName: "Canaries",
    scope: "islands",
    center: [-15.8, 28.3],
    mapZoom: 6.6,
    summary: "Volcanic deserts above the clouds, black-sand coasts and dune fields running into the Atlantic.",
    bestFor: ["Couples", "Honeymoon", "Solo"],
    vibes: ["Dramatic", "Coast", "Island"],
    highlight: "The only reliable winter destination for outdoor sessions",
    photographerHref: "/photographers?location=canary-islands",
    children: [
      { slug: "tenerife", name: "Tenerife", names: {"de":"Teneriffa"}, type: "Island" },
      { slug: "gran-canaria", name: "Gran Canaria", type: "Island" },
      { slug: "lanzarote", name: "Lanzarote", type: "Island" },
    ],
  },
  {
    slug: "valencia-region",
    name: "Valencian Community",
    names: {"en":"Valencian Community","es":"Comunidad Valenciana","de":"Region Valencia","fr":"Communauté valencienne"},
    shortName: "Valencia",
    scope: "mainland",
    center: [-0.38, 39.47],
    mapZoom: 7.8,
    summary: "White sculptural architecture, a nine-kilometre park in a drained riverbed and a wide city beach.",
    bestFor: ["Family", "Couples", "Solo"],
    vibes: ["City", "Coast", "Modern"],
    highlight: "Modern and old town within walking distance",
    photographerHref: "/photographers?location=valencia-region",
    children: [
      { slug: "valencia", name: "Valencia", names: {"fr":"Valence"}, type: "City" },
    ],
  },
  {
    slug: "basque-country",
    name: "Basque Country",
    names: {"es":"País Vasco","de":"Baskenland","fr":"Pays basque"},
    shortName: "Basque",
    scope: "mainland",
    center: [-2.45, 43.29],
    mapZoom: 7.9,
    summary: "A shell-shaped bay between green hills, Belle Époque ironwork and titanium on the riverbank.",
    bestFor: ["Couples", "Family", "Solo"],
    vibes: ["Coast", "City", "Green"],
    highlight: "Greener and cooler than the south, dramatic Atlantic weather",
    photographerHref: "/photographers?location=basque-country",
    children: [
      { slug: "san-sebastian", name: "San Sebastián", names: {"fr":"Saint-Sébastien"}, type: "City" },
      { slug: "bilbao", name: "Bilbao", type: "City" },
    ],
  },
  {
    slug: "galicia",
    name: "Galicia",
    names: {"de":"Galicien","fr":"Galice"},
    shortName: "Galicia",
    scope: "mainland",
    center: [-8.54, 42.88],
    mapZoom: 7.6,
    summary: "Granite arcades, Atlantic mist and the square where the Camino ends.",
    bestFor: ["Couples", "Solo", "Family"],
    vibes: ["Historic", "Green"],
    highlight: "A completely different palette from the Mediterranean",
    photographerHref: "/photographers?location=galicia",
    children: [
      { slug: "santiago-de-compostela", name: "Santiago de Compostela", names: {"fr":"Saint-Jacques-de-Compostelle"}, type: "City" },
    ],
  },
];
