import type { LocationExplorerRegion } from "./location-explorer-data";

/**
 * Italian region data for the locations explorer.
 *
 * Hand-written alongside `location-hierarchy-it.ts` from the same slug list.
 * Slugs must match the tree and the dataset; a generated version inherits the
 * previous country's slugs and silently matches nothing.
 */

export const LOCATION_EXPLORER_REGIONS_IT: LocationExplorerRegion[] = [
  {
    slug: "lazio",
    name: "Rome & Lazio",
    names: { it: "Roma e Lazio", de: "Rom & Latium", fr: "Rome et Latium" },
    shortName: "Rome",
    scope: "mainland",
    center: [12.5, 41.9],
    mapZoom: 7.6,
    summary: "Three thousand years of backdrops in one walkable centre, empty for the first two hours of daylight.",
    bestFor: ["Couples", "Family", "Proposal", "Solo"],
    vibes: ["City", "Historic"],
    highlight: "The whole centre to yourselves before eight",
    photographerHref: "/photographers?location=lazio",
    children: [{ slug: "rome", name: "Rome", names: { it: "Roma", fr: "Rome", de: "Rom" }, type: "City" }],
  },
  {
    slug: "tuscany",
    name: "Tuscany",
    names: { it: "Toscana", de: "Toskana", fr: "Toscane" },
    shortName: "Florence",
    scope: "mainland",
    center: [11.3, 43.4],
    mapZoom: 7.5,
    summary: "Renaissance cities an hour apart, and the cypress ridges everyone pictures when they think of Italy.",
    bestFor: ["Couples", "Proposal", "Honeymoon", "Family"],
    vibes: ["Historic", "Countryside"],
    highlight: "City and countryside in the same session",
    photographerHref: "/photographers?location=tuscany",
    children: [
      { slug: "florence", name: "Florence", names: { it: "Firenze", de: "Florenz" }, type: "City" },
      { slug: "siena", name: "Siena", names: { fr: "Sienne" }, type: "City" },
      { slug: "val-dorcia", name: "Val d'Orcia", type: "Region" },
      { slug: "pisa", name: "Pisa", names: { fr: "Pise" }, type: "City" },
      { slug: "lucca", name: "Lucca", names: { fr: "Lucques" }, type: "City" },
    ],
  },
  {
    slug: "veneto",
    name: "Venice & Veneto",
    names: { it: "Venezia e Veneto", de: "Venedig & Venetien", fr: "Venise et Vénétie" },
    shortName: "Venice",
    scope: "mainland",
    center: [11.6, 45.5],
    mapZoom: 7.5,
    summary: "Canal light before the first vaporetto, pink marble in Verona and an alpine lake an hour west.",
    bestFor: ["Couples", "Proposal", "Honeymoon"],
    vibes: ["City", "Historic", "Lake"],
    highlight: "Venice at seven is a different city",
    photographerHref: "/photographers?location=veneto",
    children: [
      { slug: "venice", name: "Venice", names: { it: "Venezia", de: "Venedig", fr: "Venise" }, type: "City" },
      { slug: "verona", name: "Verona", names: { fr: "Vérone" }, type: "City" },
      { slug: "lake-garda", name: "Lake Garda", names: { it: "Lago di Garda", de: "Gardasee", fr: "Lac de Garde" }, type: "Region" },
    ],
  },
  {
    slug: "lombardy",
    name: "Milan & the Lakes",
    names: { it: "Milano e i laghi", de: "Mailand & die Seen", fr: "Milan et les lacs" },
    shortName: "Milan",
    scope: "mainland",
    center: [9.3, 45.7],
    mapZoom: 7.6,
    summary: "Sharp, modern city lines an hour from villa gardens hanging over Lake Como.",
    bestFor: ["Couples", "Proposal", "Honeymoon", "Business"],
    vibes: ["City", "Lake"],
    highlight: "Easiest city to reach, best lake to propose on",
    photographerHref: "/photographers?location=lombardy",
    children: [
      { slug: "milan", name: "Milan", names: { it: "Milano", de: "Mailand" }, type: "City" },
      { slug: "lake-como", name: "Lake Como", names: { it: "Lago di Como", de: "Comer See", fr: "Lac de Côme" }, type: "Region" },
    ],
  },
  {
    slug: "campania",
    name: "Amalfi Coast & Naples",
    names: { it: "Costiera Amalfitana e Napoli", de: "Amalfiküste & Neapel", fr: "Côte amalfitaine et Naples" },
    shortName: "Amalfi",
    scope: "mainland",
    center: [14.4, 40.7],
    mapZoom: 8.2,
    summary: "Cliff villages in apricot and rose, an island off the point, and a city that photographs like a film.",
    bestFor: ["Couples", "Honeymoon", "Proposal", "Family"],
    vibes: ["Coast", "Island", "City"],
    highlight: "Italy's most requested honeymoon backdrop",
    photographerHref: "/photographers?location=campania",
    children: [
      { slug: "naples", name: "Naples", names: { it: "Napoli", de: "Neapel" }, type: "City" },
      { slug: "amalfi-coast", name: "Amalfi Coast", names: { it: "Costiera Amalfitana" }, type: "Region" },
      { slug: "positano", name: "Positano", type: "City" },
      { slug: "sorrento", name: "Sorrento", names: { de: "Sorrent", fr: "Sorrente" }, type: "City" },
      { slug: "capri", name: "Capri", type: "Island" },
      { slug: "ravello", name: "Ravello", type: "City" },
    ],
  },
  {
    slug: "sicily",
    name: "Sicily",
    names: { it: "Sicilia", de: "Sizilien", fr: "Sicile" },
    shortName: "Sicily",
    scope: "islands",
    center: [14.2, 37.6],
    mapZoom: 7.4,
    summary: "A volcano behind a Greek theatre, honey-coloured baroque on the sea, and markets that need no direction.",
    bestFor: ["Couples", "Honeymoon", "Family", "Solo"],
    vibes: ["Island", "Coast", "Historic"],
    highlight: "Etna framed behind an ancient theatre",
    photographerHref: "/photographers?location=sicily",
    children: [
      { slug: "taormina", name: "Taormina", names: { fr: "Taormine" }, type: "City" },
      { slug: "palermo", name: "Palermo", names: { fr: "Palerme" }, type: "City" },
      { slug: "syracuse", name: "Syracuse", names: { it: "Siracusa", de: "Syrakus" }, type: "City" },
    ],
  },
  {
    slug: "liguria",
    name: "Cinque Terre & Liguria",
    names: { it: "Cinque Terre e Liguria", de: "Cinque Terre & Ligurien", fr: "Cinque Terre et Ligurie" },
    shortName: "Cinque Terre",
    scope: "mainland",
    center: [9.4, 44.2],
    mapZoom: 8.4,
    summary: "Painted villages pinned to a cliff coast, linked by footpaths and a train every twenty minutes.",
    bestFor: ["Couples", "Proposal", "Honeymoon"],
    vibes: ["Coast", "Countryside"],
    highlight: "More colour per frame than anywhere in Italy",
    photographerHref: "/photographers?location=liguria",
    children: [
      { slug: "cinque-terre", name: "Cinque Terre", type: "Region" },
      { slug: "portofino", name: "Portofino", type: "City" },
    ],
  },
  {
    slug: "puglia",
    name: "Puglia",
    names: { it: "Puglia", de: "Apulien", fr: "Pouilles" },
    shortName: "Puglia",
    scope: "mainland",
    center: [17.5, 40.6],
    mapZoom: 7.6,
    summary: "Golden baroque, whitewashed cone-roofed towns and two seas within an hour of each other.",
    bestFor: ["Couples", "Family", "Solo"],
    vibes: ["Historic", "Coast", "Countryside"],
    highlight: "The trulli look like nowhere else in Europe",
    photographerHref: "/photographers?location=puglia",
    children: [
      { slug: "lecce", name: "Lecce", type: "City" },
      { slug: "alberobello", name: "Alberobello", type: "City" },
    ],
  },
];
