export interface PhotoSpot {
  name: string;
  description: string;
  /** Portuguese translations; when absent, EN fallback is used on /pt. */
  namePt?: string;
  descriptionPt?: string;
  best_time?: string;
  best_timePt?: string;
  tips?: string;
  tipsPt?: string;
}

export function spotSlug(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function getSpot(citySlug: string, slug: string): PhotoSpot | undefined {
  return (photoSpots[citySlug] || []).find((s) => spotSlug(s.name) === slug);
}

/** Returns name/description in the requested locale, falling back to EN. */
export function spotLocalized(spot: PhotoSpot, locale: string) {
  const pt = locale === "pt";
  return {
    name: pt && spot.namePt ? spot.namePt : spot.name,
    description: pt && spot.descriptionPt ? spot.descriptionPt : spot.description,
    best_time: pt && spot.best_timePt ? spot.best_timePt : spot.best_time,
    tips: pt && spot.tipsPt ? spot.tipsPt : spot.tips,
  };
}

/** Top photography spots per location slug */
export const photoSpots: Record<string, PhotoSpot[]> = {
  lisbon: [
    { name: "Miradouro da Graca", namePt: "Miradouro da Graça",
      description: "One of Lisbon's most scenic viewpoints with panoramic views over the city rooftops and the Tagus River — perfect for golden hour portraits.",
      descriptionPt: "Um dos miradouros mais cénicos de Lisboa, com vistas panorâmicas sobre os telhados da cidade e o rio Tejo — perfeito para retratos ao pôr do sol." },
    { name: "Alfama", namePt: "Alfama",
      description: "The oldest neighborhood in Lisbon, with narrow cobblestone streets, colorful azulejo-tiled facades, and authentic Portuguese atmosphere.",
      descriptionPt: "O bairro mais antigo de Lisboa, com ruas estreitas de calçada, fachadas coloridas de azulejos e uma atmosfera autenticamente portuguesa." },
    { name: "Belem Tower", namePt: "Torre de Belém",
      description: "The iconic 16th-century riverside fortress and UNESCO World Heritage site, ideal for dramatic architectural backdrops.",
      descriptionPt: "A icónica fortaleza ribeirinha do século XVI, Património Mundial da UNESCO, ideal para cenários arquitetónicos dramáticos." },
    { name: "LX Factory", namePt: "LX Factory",
      description: "A trendy creative hub in a converted industrial complex, offering street art, vibrant murals, and an urban-cool photoshoot aesthetic.",
      descriptionPt: "Um polo criativo num antigo complexo industrial reconvertido, com street art, murais vibrantes e uma estética urbana para sessões fotográficas." },
    { name: "Praca do Comercio", namePt: "Praça do Comércio",
      description: "Lisbon's grand waterfront square with its striking yellow arcades and the Triumphal Arch — a wide-open, elegant setting for group and couple photos.",
      descriptionPt: "A grande praça ribeirinha de Lisboa, com os seus característicos arcos amarelos e o Arco da Rua Augusta — um cenário amplo e elegante para fotos de grupo e casal." },
  ],
  porto: [
    { name: "Ribeira", namePt: "Ribeira",
      description: "The colorful UNESCO-listed riverfront district with stacked houses cascading down to the Douro — Porto's most iconic photoshoot location.",
      descriptionPt: "O colorido bairro ribeirinho classificado pela UNESCO, com casas empilhadas em cascata até ao Douro — o local mais icónico do Porto para sessões fotográficas." },
    { name: "Dom Luis I Bridge", namePt: "Ponte Dom Luís I",
      description: "The double-deck iron bridge offers dramatic framing with the Douro River and both sides of the city stretching below.",
      descriptionPt: "A ponte de ferro de dois tabuleiros oferece um enquadramento dramático com o rio Douro e ambas as margens da cidade em baixo." },
    { name: "Livraria Lello", namePt: "Livraria Lello",
      description: "One of the world's most beautiful bookshops, with a stunning neo-Gothic interior and the famous crimson staircase.",
      descriptionPt: "Uma das livrarias mais bonitas do mundo, com um interior neogótico deslumbrante e a famosa escadaria vermelha." },
    { name: "Sao Bento Station", namePt: "Estação de São Bento",
      description: "A railway station adorned with over 20,000 hand-painted azulejo tiles depicting Portuguese history — a unique indoor backdrop.",
      descriptionPt: "Uma estação ferroviária decorada com mais de 20 000 azulejos pintados à mão que retratam a história portuguesa — um cenário interior único." },
    { name: "Serra do Pilar", namePt: "Serra do Pilar",
      description: "A hilltop viewpoint on the Vila Nova de Gaia side, offering the classic panoramic shot of Porto's skyline and the Douro River.",
      descriptionPt: "Um miradouro no topo da colina em Vila Nova de Gaia, oferecendo a vista panorâmica clássica do skyline do Porto e do rio Douro." },
  ],
  sintra: [
    { name: "Pena Palace", namePt: "Palácio da Pena",
      description: "A Romanticist castle in vivid red and yellow perched on a misty hilltop, surrounded by enchanted gardens — pure fairytale magic.",
      descriptionPt: "Um castelo romântico em vermelho e amarelo vivos, no topo de uma colina enevoada, rodeado por jardins encantados — pura magia de conto de fadas." },
    { name: "Quinta da Regaleira", namePt: "Quinta da Regaleira",
      description: "Mystical estate with the famous Initiation Well, underground tunnels, grottoes, and lush gardens that feel like a fantasy world.",
      descriptionPt: "Uma propriedade mística com o famoso Poço Iniciático, túneis subterrâneos, grutas e jardins exuberantes que parecem saídos de um mundo de fantasia." },
    { name: "National Palace", namePt: "Palácio Nacional de Sintra",
      description: "The medieval royal palace in the heart of Sintra village, with its distinctive twin conical chimneys and ornate Moorish interiors.",
      descriptionPt: "O palácio real medieval no centro de Sintra, com as suas distintivas chaminés cónicas gémeas e interiores ornamentados de influência mourisca." },
    { name: "Monserrate Palace", namePt: "Palácio de Monserrate",
      description: "An exotic 19th-century palace with Moorish, Gothic, and Indian influences, set in romantic botanical gardens with rare plant species.",
      descriptionPt: "Um palácio exótico do século XIX com influências mouriscas, góticas e indianas, rodeado de jardins botânicos românticos com espécies raras." },
  ],
  algarve: [
    { name: "Benagil Cave", namePt: "Gruta de Benagil",
      description: "A stunning sea cave with a natural skylight opening to the sky above a hidden beach — one of Portugal's most photographed natural wonders.",
      descriptionPt: "Uma deslumbrante gruta marinha com uma clarabóia natural que se abre para o céu sobre uma praia escondida — uma das maravilhas naturais mais fotografadas de Portugal." },
    { name: "Ponta da Piedade", namePt: "Ponta da Piedade",
      description: "Dramatic golden sandstone cliffs, arches, and sea stacks rising from turquoise waters near Lagos — an unforgettable coastal backdrop.",
      descriptionPt: "Falésias dramáticas de arenito dourado, arcos e pilares marinhos que se erguem das águas turquesa perto de Lagos — um cenário costeiro inesquecível." },
    { name: "Praia da Marinha", namePt: "Praia da Marinha",
      description: "Consistently rated one of the most beautiful beaches in Europe, framed by sculpted limestone cliffs and crystal-clear water.",
      descriptionPt: "Classificada consistentemente como uma das praias mais bonitas da Europa, emoldurada por falésias calcárias esculpidas e água cristalina." },
    { name: "Tavira Island", namePt: "Ilha de Tavira",
      description: "A pristine barrier island in the Ria Formosa lagoon, accessible by ferry, with endless white sand and calm turquoise waters.",
      descriptionPt: "Uma ilha-barreira imaculada na Ria Formosa, acessível por ferry, com areia branca sem fim e águas turquesa calmas." },
  ],
  lagos: [
    { name: "Ponta da Piedade", namePt: "Ponta da Piedade",
      description: "Towering sandstone pillars and sea grottos carved by the Atlantic, offering the most dramatic coastal scenery in the Algarve.",
      descriptionPt: "Imponentes pilares de arenito e grutas marinhas esculpidas pelo Atlântico, oferecendo o cenário costeiro mais dramático do Algarve." },
    { name: "Praia do Camilo", namePt: "Praia do Camilo",
      description: "A small cove beach reached by a wooden staircase through the cliffs, creating an intimate and picturesque setting for portraits.",
      descriptionPt: "Uma pequena praia em enseada acedida por uma escadaria de madeira através das falésias, criando um cenário íntimo e pitoresco para retratos." },
    { name: "Lagos Old Town", namePt: "Centro Histórico de Lagos",
      description: "Charming streets within 16th-century walls filled with colorful buildings, lively plazas, and waterfront cafes perfect for lifestyle shots.",
      descriptionPt: "Ruas encantadoras dentro de muralhas do século XVI, com edifícios coloridos, praças animadas e cafés à beira-mar perfeitos para fotos de estilo de vida." },
  ],
  cascais: [
    { name: "Boca do Inferno", namePt: "Boca do Inferno",
      description: "A dramatic chasm in the coastal cliffs where Atlantic waves crash with spectacular force — raw, powerful, and unforgettable.",
      descriptionPt: "Um abismo dramático nas falésias costeiras onde as ondas do Atlântico embatem com força espectacular — bruto, poderoso e inesquecível." },
    { name: "Cascais Marina", namePt: "Marina de Cascais",
      description: "A sleek, modern marina surrounded by pastel-colored buildings and waterfront restaurants, blending seaside elegance with coastal charm.",
      descriptionPt: "Uma marina moderna e elegante rodeada por edifícios em tons pastel e restaurantes à beira-mar, unindo elegância à beira-mar e charme costeiro." },
    { name: "Casa de Santa Maria", namePt: "Casa de Santa Maria",
      description: "A beautifully restored aristocratic mansion on the waterfront with ornate tile work, arched windows, and ocean views.",
      descriptionPt: "Uma mansão aristocrática lindamente restaurada à beira-mar, com azulejos ornamentados, janelas em arco e vistas para o oceano." },
  ],
  madeira: [
    { name: "Cabo Girao", namePt: "Cabo Girão",
      description: "Europe's highest sea cliff at 580 meters, with a glass-floor skywalk offering vertigo-inducing views over the Atlantic Ocean.",
      descriptionPt: "A falésia marítima mais alta da Europa, com 580 metros, com um miradouro de piso de vidro que oferece vistas vertiginosas sobre o Oceano Atlântico." },
    { name: "Funchal Old Town", namePt: "Zona Velha do Funchal",
      description: "Vibrant painted doors, flower-lined streets, and colorful markets make this historic district a photographer's playground.",
      descriptionPt: "Portas pintadas vibrantes, ruas floridas e mercados coloridos fazem deste bairro histórico um paraíso para fotógrafos." },
    { name: "Levada Walks", namePt: "Levadas",
      description: "Ancient irrigation channel trails through lush laurel forests and misty mountains — perfect for adventurous, nature-immersed photoshoots.",
      descriptionPt: "Antigos canais de irrigação que atravessam florestas de laurissilva e montanhas enevoadas — perfeitos para sessões fotográficas aventureiras imersas na natureza." },
  ],
  azores: [
    { name: "Sete Cidades", namePt: "Sete Cidades",
      description: "Twin crater lakes — one green, one blue — nestled inside a volcanic caldera, creating one of the most surreal landscapes in Europe.",
      descriptionPt: "Lagoas gémeas — uma verde, outra azul — dentro de uma caldeira vulcânica, criando uma das paisagens mais surreais da Europa." },
    { name: "Furnas", namePt: "Furnas",
      description: "A volcanic valley of steaming fumaroles, thermal hot springs, and lush botanical gardens with an otherworldly atmosphere.",
      descriptionPt: "Um vale vulcânico com fumarolas, nascentes termais e exuberantes jardins botânicos, com uma atmosfera de outro mundo." },
    { name: "Lagoa do Fogo", namePt: "Lagoa do Fogo",
      description: "A pristine crater lake surrounded by untouched wilderness, often wrapped in dramatic clouds — raw and remote natural beauty.",
      descriptionPt: "Uma lagoa de cratera intocada, rodeada de natureza selvagem e frequentemente envolta em nuvens dramáticas — beleza natural bruta e remota." },
  ],
  caparica: [
    { name: "Praia da Fonte da Telha", namePt: "Praia da Fonte da Telha",
      description: "A wild, windswept stretch of golden sand backed by dramatic fossil cliffs, ideal for sunset and editorial-style shoots.",
      descriptionPt: "Uma faixa selvagem de areia dourada protegida por falésias fósseis dramáticas, ideal para sessões ao pôr do sol e de estilo editorial." },
    { name: "Costa da Caparica Beach", namePt: "Praia da Costa da Caparica",
      description: "A long, wide beach with a lively atmosphere and unobstructed Atlantic sunset views just across the river from Lisbon.",
      descriptionPt: "Uma praia longa e ampla com atmosfera animada e vistas desobstruídas do pôr do sol atlântico, a poucos minutos de Lisboa." },
    { name: "Arriba Fossil", namePt: "Arriba Fóssil",
      description: "A protected fossilized clifftop landscape offering unique geological formations and panoramic coastal views.",
      descriptionPt: "Uma paisagem protegida de falésias fossilizadas com formações geológicas únicas e vistas panorâmicas da costa." },
  ],
  setubal: [
    { name: "Arrabida Natural Park", namePt: "Parque Natural da Arrábida",
      description: "Towering limestone cliffs plunging into crystal-clear turquoise coves, surrounded by lush Mediterranean vegetation.",
      descriptionPt: "Imponentes falésias calcárias que mergulham em enseadas turquesa cristalinas, rodeadas de exuberante vegetação mediterrânica." },
    { name: "Troia Peninsula", namePt: "Península de Tróia",
      description: "Endless white sand beaches stretching along the Sado Estuary, with calm waters and a tranquil, unspoiled atmosphere.",
      descriptionPt: "Praias infindáveis de areia branca ao longo do Estuário do Sado, com águas calmas e uma atmosfera tranquila e preservada." },
    { name: "Setubal Harbor", namePt: "Porto de Setúbal",
      description: "A working fishing port with colorful boats and an authentic, gritty charm that captures real Portuguese coastal life.",
      descriptionPt: "Um porto de pesca ativo com barcos coloridos e um charme autêntico que capta a verdadeira vida costeira portuguesa." },
  ],
  comporta: [
    { name: "Comporta Beach", namePt: "Praia da Comporta",
      description: "Pristine white sand backed by umbrella pines, with a bohemian luxury vibe favored by artists and creatives.",
      descriptionPt: "Areia branca imaculada rodeada de pinheiros-mansos, com um ambiente de luxo boémio apreciado por artistas e criativos." },
    { name: "Rice Paddies", namePt: "Arrozais",
      description: "Vast flooded rice fields reflecting the sky, dotted with storks — a uniquely serene and minimalist landscape.",
      descriptionPt: "Vastos arrozais inundados que refletem o céu, pontuados por cegonhas — uma paisagem serena e minimalista única." },
    { name: "Carvalhal Beach", namePt: "Praia do Carvalhal",
      description: "A quieter stretch with rustic wooden beach restaurants and golden dunes, perfect for relaxed golden-hour sessions.",
      descriptionPt: "Uma faixa mais tranquila com restaurantes de praia rústicos em madeira e dunas douradas, perfeita para sessões descontraídas ao pôr do sol." },
  ],
  guimaraes: [
    { name: "Guimaraes Castle", namePt: "Castelo de Guimarães",
      description: "The 10th-century castle where Portugal was born, with imposing stone towers and sweeping hilltop views over the city.",
      descriptionPt: "O castelo do século X onde Portugal nasceu, com imponentes torres de pedra e amplas vistas do topo da colina sobre a cidade." },
    { name: "Largo da Oliveira", namePt: "Largo da Oliveira",
      description: "A charming medieval square lined with granite buildings, outdoor cafes, and a 14th-century Gothic canopy shrine.",
      descriptionPt: "Uma encantadora praça medieval ladeada por edifícios em granito, cafés ao ar livre e um padrão gótico do século XIV." },
    { name: "Palace of the Dukes of Braganza", namePt: "Paço dos Duques de Bragança",
      description: "A grand 15th-century palace with a distinctive roofline of 39 brick chimneys, set in manicured gardens.",
      descriptionPt: "Um grande palácio do século XV com um telhado característico de 39 chaminés de tijolo, rodeado de jardins bem cuidados." },
  ],
  braga: [
    { name: "Bom Jesus do Monte", namePt: "Bom Jesus do Monte",
      description: "A monumental baroque stairway of 577 steps flanked by ornate fountains, leading to a hilltop church with panoramic views.",
      descriptionPt: "Uma monumental escadaria barroca de 577 degraus ladeada por fontes ornamentadas, que conduz a uma igreja no topo da colina com vistas panorâmicas." },
    { name: "Braga Cathedral", namePt: "Sé de Braga",
      description: "The oldest cathedral in Portugal, blending Romanesque, Gothic, and Baroque styles in the heart of the historic center.",
      descriptionPt: "A mais antiga catedral de Portugal, combinando estilos românico, gótico e barroco no coração do centro histórico." },
    { name: "Jardim de Santa Barbara", namePt: "Jardim de Santa Bárbara",
      description: "A beautifully manicured formal garden beside the medieval Archbishop's Palace, bursting with color year-round.",
      descriptionPt: "Um jardim formal lindamente cuidado junto ao medieval Paço Arquiepiscopal, cheio de cor todo o ano." },
  ],
  "douro-valley": [
    { name: "Pinhao", namePt: "Pinhão",
      description: "A riverside village at the heart of port wine country, with a tile-decorated train station and vine-covered hillsides.",
      descriptionPt: "Uma aldeia ribeirinha no coração da região do Vinho do Porto, com uma estação ferroviária decorada com azulejos e encostas cobertas de vinhas." },
    { name: "Miradouro de Sao Leonardo de Galafura", namePt: "Miradouro de São Leonardo de Galafura",
      description: "A panoramic viewpoint overlooking the terraced vineyards of the Douro, famously described as the most beautiful view in Portugal.",
      descriptionPt: "Um miradouro panorâmico sobre os vinhedos em socalcos do Douro, famosamente descrito como a vista mais bonita de Portugal." },
    { name: "Quinta da Roeda", namePt: "Quinta da Roeda",
      description: "A historic wine estate with terraced vineyards plunging toward the river, offering an authentic wine country backdrop.",
      descriptionPt: "Uma histórica quinta vinícola com vinhedos em socalcos que mergulham em direção ao rio, oferecendo um cenário autêntico da região vinhateira." },
  ],
  aveiro: [
    { name: "Central Canal", namePt: "Canal Central",
      description: "Colorful moliceiro boats glide along the canal lined with Art Nouveau buildings — the quintessential Aveiro photo.",
      descriptionPt: "Coloridos barcos moliceiros deslizam pelo canal ladeado por edifícios Arte Nova — a fotografia clássica de Aveiro." },
    { name: "Costa Nova", namePt: "Costa Nova",
      description: "A beach village famous for its striped palheiros (wooden houses) painted in vivid candy-colored stripes.",
      descriptionPt: "Uma vila de praia famosa pelos seus palheiros às riscas, pintados em cores vivas e contrastantes." },
    { name: "Ria de Aveiro Lagoon", namePt: "Ria de Aveiro",
      description: "A vast, serene lagoon with salt flats, fishing boats, and soft golden light perfect for tranquil portraits.",
      descriptionPt: "Uma vasta e serena ria com salinas, barcos de pesca e uma luz dourada suave, perfeita para retratos tranquilos." },
  ],
  geres: [
    { name: "Cascata do Tahiti", namePt: "Cascata do Tahiti",
      description: "A hidden waterfall cascading into an emerald pool surrounded by moss-covered rocks and ancient forest.",
      descriptionPt: "Uma cascata escondida que desce até uma poça esmeralda rodeada de rochas cobertas de musgo e floresta antiga." },
    { name: "Canicada Reservoir", namePt: "Albufeira da Caniçada",
      description: "A turquoise mountain lake surrounded by dense forest and granite peaks, offering dramatic nature backdrops.",
      descriptionPt: "Uma albufeira turquesa de montanha rodeada por floresta densa e picos graníticos, oferecendo cenários naturais dramáticos." },
    { name: "Lindoso Village", namePt: "Aldeia do Lindoso",
      description: "An ancient granite village with a hilltop castle and traditional espigueiros (stone granaries) set against wild mountain scenery.",
      descriptionPt: "Uma antiga aldeia de granito com castelo no topo da colina e tradicionais espigueiros, enquadrada por paisagem montanhosa selvagem." },
  ],
  tomar: [
    { name: "Convent of Christ", namePt: "Convento de Cristo",
      description: "A UNESCO World Heritage Templar fortress with one of the most ornate Manueline windows in Portugal.",
      descriptionPt: "Uma fortaleza templária, Património Mundial da UNESCO, com uma das mais ornamentadas janelas manuelinas de Portugal." },
    { name: "Nabao River Gardens", namePt: "Jardins do Rio Nabão",
      description: "Lush riverside gardens and tree-lined walkways along the Nabao River, offering a peaceful and romantic setting.",
      descriptionPt: "Jardins ribeirinhos exuberantes e passeios arborizados ao longo do Rio Nabão, oferecendo um ambiente pacífico e romântico." },
    { name: "Mata Nacional dos Sete Montes", namePt: "Mata Nacional dos Sete Montes",
      description: "A large forested park adjacent to the castle, with shaded paths, ancient trees, and hidden corners.",
      descriptionPt: "Um grande parque arborizado junto ao castelo, com caminhos sombreados, árvores centenárias e recantos escondidos." },
  ],
  peniche: [
    { name: "Cabo Carvoeiro", namePt: "Cabo Carvoeiro",
      description: "A dramatic clifftop lighthouse at the western tip of the Peniche peninsula, with sweeping Atlantic panoramas.",
      descriptionPt: "Um farol dramático no topo da falésia, no extremo ocidental da península de Peniche, com amplas panorâmicas atlânticas." },
    { name: "Supertubos Beach", namePt: "Praia dos Supertubos",
      description: "A world-famous surf break with powerful waves and wide golden sand, ideal for dynamic action-style shoots.",
      descriptionPt: "Uma praia de surf mundialmente famosa com ondas potentes e vasta areia dourada, ideal para sessões dinâmicas e de ação." },
    { name: "Berlengas Islands", namePt: "Ilhas Berlengas",
      description: "A nature reserve archipelago with crystal-clear waters and a 17th-century island fortress, accessible by boat.",
      descriptionPt: "Um arquipélago de reserva natural com águas cristalinas e uma fortaleza do século XVII, acessível de barco." },
  ],
  coimbra: [
    { name: "Joanina Library", namePt: "Biblioteca Joanina",
      description: "A jaw-dropping baroque library at the University of Coimbra, with gilded bookshelves and painted ceilings.",
      descriptionPt: "Uma deslumbrante biblioteca barroca da Universidade de Coimbra, com estantes douradas e tetos pintados." },
    { name: "University Tower", namePt: "Torre da Universidade",
      description: "The hilltop university campus offers panoramic views over the Mondego River and the old town's red rooftops.",
      descriptionPt: "O campus universitário no topo da colina oferece vistas panorâmicas sobre o Rio Mondego e os telhados vermelhos da baixa." },
    { name: "Quinta das Lagrimas", namePt: "Quinta das Lágrimas",
      description: "A romantic garden estate linked to the tragic medieval love story of Pedro and Ines de Castro.",
      descriptionPt: "Uma romântica quinta ligada à trágica história de amor medieval de D. Pedro e Inês de Castro." },
  ],
  obidos: [
    { name: "Castle Walls", namePt: "Muralhas do Castelo",
      description: "Walk along the medieval ramparts for panoramic views over whitewashed houses, terracotta roofs, and the surrounding countryside.",
      descriptionPt: "Percorra as muralhas medievais para vistas panorâmicas sobre as casas caiadas de branco, telhados de terracota e a paisagem envolvente." },
    { name: "Rua Direita", namePt: "Rua Direita",
      description: "The main cobblestone street lined with whitewashed houses adorned with bougainvillea and hand-painted ceramics.",
      descriptionPt: "A rua principal, em calçada portuguesa, ladeada por casas brancas decoradas com buganvílias e cerâmica pintada à mão." },
    { name: "Porta da Vila", namePt: "Porta da Vila",
      description: "The main town gate decorated with blue-and-white azulejo tiles, framing the entrance to the medieval walled town.",
      descriptionPt: "A porta principal da vila, decorada com azulejos azuis e brancos, a emoldurar a entrada da vila muralhada medieval." },
  ],
  nazare: [
    { name: "Farol da Nazare", namePt: "Farol da Nazaré",
      description: "The iconic lighthouse and cliff-edge viewpoint where spectators watch the world's biggest waves crash below.",
      descriptionPt: "O icónico farol e miradouro à beira da falésia, onde se assiste ao embate das maiores ondas do mundo." },
    { name: "Sitio", namePt: "Sítio",
      description: "The historic clifftop quarter with a fortress, churches, and dramatic panoramic views over the beach and Atlantic.",
      descriptionPt: "O histórico bairro no topo da falésia, com fortaleza, igrejas e vistas panorâmicas dramáticas sobre a praia e o Atlântico." },
    { name: "Praia da Nazare", namePt: "Praia da Nazaré",
      description: "The wide main beach with colorful traditional fishing boats and women in traditional seven-skirt costumes.",
      descriptionPt: "A ampla praia principal com coloridos barcos de pesca tradicionais e mulheres em trajes tradicionais de sete saias." },
  ],
  evora: [
    { name: "Temple of Diana", namePt: "Templo de Diana",
      description: "A remarkably preserved 2,000-year-old Roman temple in the heart of the city, surrounded by medieval architecture.",
      descriptionPt: "Um templo romano de 2000 anos notavelmente preservado no centro da cidade, rodeado de arquitetura medieval." },
    { name: "Chapel of Bones", namePt: "Capela dos Ossos",
      description: "A hauntingly beautiful chapel lined with human bones and skulls, creating a uniquely dramatic and atmospheric backdrop.",
      descriptionPt: "Uma capela de beleza inquietante, revestida com ossos e crânios humanos, criando um cenário dramático e atmosférico único." },
    { name: "Evora Cathedral Rooftop", namePt: "Telhado da Sé de Évora",
      description: "The Gothic cathedral rooftop terrace offers sweeping views over the Alentejo plains and the city's historic center.",
      descriptionPt: "O terraço do telhado da catedral gótica oferece vistas amplas sobre as planícies alentejanas e o centro histórico da cidade." },
  ],
  tavira: [
    { name: "Roman Bridge", namePt: "Ponte Romana",
      description: "An ancient seven-arched bridge spanning the Gilao River in the heart of town, framed by whitewashed buildings.",
      descriptionPt: "Uma antiga ponte de sete arcos sobre o Rio Gilão no centro da cidade, emoldurada por edifícios caiados de branco." },
    { name: "Ria Formosa Lagoon", namePt: "Ria Formosa",
      description: "A protected lagoon system with pristine barrier island beaches, tidal flats, and spectacular sunset views.",
      descriptionPt: "Um sistema lagunar protegido com praias imaculadas em ilhas-barreira, salinas e vistas espetaculares do pôr do sol." },
    { name: "Tavira Castle", namePt: "Castelo de Tavira",
      description: "A hilltop Moorish castle ruin surrounded by gardens, offering panoramic views over the town's pyramid-roofed houses.",
      descriptionPt: "As ruínas de um castelo mourisco no topo da colina, rodeado de jardins, com vistas panorâmicas sobre as casas de telhado em pirâmide." },
  ],
};
