export interface ShootType {
  slug: string;
  name: string;
  title: string;
  metaDescription: string;
  h1: string;
  heroText: string;
  bestLocations: { slug: string; name: string; reason: string }[];
  faqs: { question: string; answer: string }[];
}

export const shootTypes: ShootType[] = [
  {
    slug: "couples",
    name: "Couples",
    title: "Couples Photoshoot Portugal — Romantic Vacation Photography",
    metaDescription:
      "Book a couples photoshoot in Portugal. Professional photographers in Lisbon, Porto, Sintra & Algarve. Natural, relaxed sessions. From €150.",
    h1: "Couples Photoshoot in Portugal",
    heroText:
      "Portugal is one of Europe's most romantic destinations, and there's no better way to celebrate your relationship than with a professional couples photoshoot. Whether you're exploring Lisbon's golden-lit streets hand in hand, watching the sunset over Porto's Douro River, or strolling through Sintra's fairytale gardens, our photographers know exactly how to capture the magic between you. Sessions start from €150 for 60 minutes and include 40-60+ professionally edited photos. No awkward posing — just natural, beautiful moments guided by someone who knows Portugal's most intimate and photogenic spots. Most couples book golden hour sessions for the warmest, most flattering light.",
    bestLocations: [
      { slug: "lisbon", name: "Lisbon", reason: "Golden light, Alfama's charming streets, romantic miradouro viewpoints" },
      { slug: "sintra", name: "Sintra", reason: "Fairytale palaces, enchanted forests, dreamy romantic atmosphere" },
      { slug: "porto", name: "Porto", reason: "Dramatic Douro River sunsets, Ribeira waterfront, baroque charm" },
      { slug: "algarve", name: "Algarve", reason: "Golden cliff beaches, hidden sea caves, stunning coastal walks" },
      { slug: "douro-valley", name: "Douro Valley", reason: "Vineyard terraces, wine estates, golden countryside light" },
    ],
    faqs: [
      { question: "How long is a typical couples photoshoot in Portugal?", answer: "Most couples sessions last 60 to 90 minutes, which gives you enough time to visit 2-3 locations and capture a wide variety of natural, relaxed poses and candid moments together. During this time, your photographer will guide you through different backdrops — perhaps starting at a scenic viewpoint, moving to a charming side street, and finishing at a waterfront or garden. Some photographers also offer 30-minute mini sessions starting from €100, ideal for quick portrait shots if you're short on time. Longer 2-hour sessions are perfect for couples who want to explore more of a city. Book your session with Photo Portugal and let us match you with the ideal photographer for your style." },
      { question: "What should we wear for a couples photoshoot?", answer: "The golden rule is to coordinate without matching — choose complementary colors and classic styles that reflect your personality. Solid colors and muted tones (navy, cream, sage, terracotta) photograph beautifully against Portugal's warm-toned architecture and lush green landscapes. Avoid busy patterns, large logos, or neon colors that can distract from you as a couple. Comfortable shoes are essential, especially in Lisbon and Porto where cobblestone streets and hillside viewpoints are common. Bring a second outfit if you'd like variety — many couples change halfway through longer sessions. Your Photo Portugal photographer will provide a personalized style guide based on your chosen location, season, and time of day." },
      { question: "When is the best time of day for a couples photoshoot?", answer: "Golden hour — the hour after sunrise or before sunset — provides the most flattering, warm, romantic light and is universally recommended by professional photographers. In Portugal, sunset times range from around 5:30pm in winter to 9:00pm in summer, so plan accordingly. Sunset sessions in Lisbon and Porto are especially popular because the westward-facing viewpoints catch the light over the river and rooftops beautifully. Sunrise shoots are quieter and give you famous landmarks nearly to yourselves, which is ideal for Sintra or heavily touristed areas. Midday sessions can work but require a photographer experienced with harsh light. Your Photo Portugal photographer will recommend the ideal timing for your specific location and season." },
      { question: "Can we combine multiple locations in one session?", answer: "Yes! Combining multiple locations is one of the best ways to get a diverse set of photos from your trip. Many couples book a 90-minute to 2-hour session that covers 2-3 nearby spots. For example, in Lisbon you might start at Miradouro da Graca for panoramic city views, stroll through Alfama's narrow tiled streets for intimate close-ups, and finish at the waterfront near Praca do Comercio for open, airy portraits. In Porto, you could begin at the iconic Ribeira district, cross the Dom Luis Bridge, and end at a port wine cellar. Your photographer will plan an efficient route so no time is wasted on transport. Book through Photo Portugal and your photographer will suggest the best multi-stop itinerary for your preferred style." },
    ],
  },
  {
    slug: "family",
    name: "Family",
    title: "Family Photographer Portugal — Vacation Photos with Kids",
    metaDescription:
      "Book a family photoshoot in Portugal. Kid-friendly sessions in Lisbon, Algarve, Porto & more. Relaxed, natural photos. From €150.",
    h1: "Family Photoshoot in Portugal",
    heroText:
      "Family vacations in Portugal create memories that last a lifetime — but only if you're actually in the photos. Our photographers specialize in natural, relaxed family photography that captures genuine moments of joy, laughter, and connection. They know the best kid-friendly locations, how to keep little ones engaged, and how to make the whole experience feel like an adventure rather than a chore. Sessions start from €150 and include 40-80+ edited photos delivered to a private online gallery. From building sandcastles on the Algarve to exploring Lisbon's colorful neighborhoods and riding Porto's vintage trams, your family photos will be ones you'll treasure and display for generations to come.",
    bestLocations: [
      { slug: "lisbon", name: "Lisbon", reason: "Tram rides, colorful streets, waterfront parks — endless fun for kids" },
      { slug: "algarve", name: "Algarve", reason: "Beautiful beaches, calm waters, and dramatic cliff backdrops" },
      { slug: "cascais", name: "Cascais", reason: "Sandy beaches, seaside promenade, relaxed coastal atmosphere" },
      { slug: "sintra", name: "Sintra", reason: "Castle explorations, magical gardens, fairytale atmosphere kids love" },
      { slug: "porto", name: "Porto", reason: "Riverside walks, garden parks, vibrant and colorful backdrops" },
    ],
    faqs: [
      { question: "What if my kids won't cooperate during the photoshoot?", answer: "Our photographers are experienced with children of all ages and know that kids will be kids — that's actually what makes family photos so authentic and charming. They use games, silly jokes, piggyback rides, tickle attacks, and natural play to capture genuine laughter and real connections. Some of the best family photos come from spontaneous, unscripted moments when a toddler runs off or siblings start goofing around. Your photographer will keep the energy light and fun, taking breaks when needed. Sessions with young children (under 5) are often scheduled in the morning when energy levels are highest. Don't worry about perfection — book with Photo Portugal and let your photographer handle the rest." },
      { question: "What's the best age for a family photoshoot?", answer: "Every age is perfect for a family photoshoot in Portugal. Photographers adapt their approach to suit your children: for babies and toddlers (6 months to 3 years), they focus on natural play, cuddles, and close-up moments in calm settings like gardens or beaches. For children aged 4-10, sessions become more interactive with exploring, jumping, and adventure-style shots at castles or along waterfronts. Teenagers respond well to a relaxed, editorial approach that makes them feel cool rather than forced. Multi-generational families with grandparents benefit from Portugal's flat promenades in Cascais or Faro. The key is choosing a location and time that suits your youngest family member. Photo Portugal photographers will tailor the entire session to your family's ages and energy levels." },
      { question: "How should we dress for a family photoshoot?", answer: "Choose a coordinated color palette rather than matching outfits — this creates visual harmony without looking staged. Earth tones (tan, olive, cream), pastels (dusty rose, light blue), and classic blues work beautifully against Portugal's warm sandstone buildings and green landscapes. Avoid neon colors, large logos, and busy patterns that can distract from faces and expressions. Layers add visual interest: a light scarf, denim jacket, or cardigan works well. Comfortable shoes are essential, especially for Lisbon's cobblestone hills and Porto's steep riverside streets — sneakers or sandals with grip are ideal for kids. Your Photo Portugal photographer will send a personalized style guide after booking, with specific recommendations based on your location, season, and family size." },
      { question: "Can we bring a stroller or baby carrier?", answer: "Absolutely — your photographer will plan a route that accommodates your family's needs. For stroller-friendly sessions, locations like Cascais seafront promenade, Lisbon's Belem waterfront, and Porto's Foz do Douro coastal walk offer flat, paved paths with gorgeous backdrops. For locations with stairs or narrow streets (like Alfama in Lisbon or Porto's Ribeira), your photographer will suggest accessible alternatives or plan the route so you can park the stroller at a safe spot during brief photo stops. Baby carriers and wraps actually photograph beautifully and create intimate parent-child moments. Many families with babies under 12 months prefer morning sessions when little ones are most content. Let Photo Portugal know your family's needs when booking and we'll match you with the right photographer and route." },
    ],
  },
  {
    slug: "proposal",
    name: "Proposal",
    title: "Proposal Photographer Portugal — Capture the Perfect Moment",
    metaDescription:
      "Hire a surprise proposal photographer in Portugal. Discreet photography in Lisbon, Sintra, Porto & Algarve. Verified reviews. From €200.",
    h1: "Surprise Proposal Photography in Portugal",
    heroText:
      "Planning to pop the question in Portugal? Our photographers are experts at capturing surprise proposals — discreetly positioned to photograph every genuine reaction, tear of joy, and that unforgettable 'yes' moment. From choosing the perfect spot to coordinating timing and positioning, our team helps you plan every detail so you can focus on the most important question of your life. Proposal packages start from €200 and include pre-shoot planning, the surprise capture, plus 30-60 minutes of couple portraits afterward. Portugal offers some of the most breathtaking proposal backdrops in Europe: Sintra's fairytale palaces, Lisbon's panoramic viewpoints, Porto's dramatic bridges, and the Algarve's golden cliffs at sunset.",
    bestLocations: [
      { slug: "sintra", name: "Sintra", reason: "Pena Palace gardens, Regaleira's romantic terraces — fairy-tale worthy" },
      { slug: "lisbon", name: "Lisbon", reason: "Sunset at Miradouro da Graca, rooftop views, intimate Alfama streets" },
      { slug: "porto", name: "Porto", reason: "Dom Luis Bridge at sunset, Jardins do Palacio de Cristal viewpoint" },
      { slug: "algarve", name: "Algarve", reason: "Secluded cliff-top spots, golden beach sunsets, sea cave proposals" },
    ],
    faqs: [
      { question: "How do proposal photoshoots work?", answer: "The process is carefully planned to ensure a flawless surprise. After booking, you'll have a detailed planning call or message exchange with your photographer where you'll share your vision, preferred location, and timing. Your photographer will scout the exact spot in advance, identify the best angles and lighting positions, and plan their cover story — often posing as a tourist photographing the scenery. On the day, they'll be in position 15-20 minutes early with a telephoto lens to capture every moment from your approach to the ring reveal to your partner's genuine reaction. After the surprise, most packages include 30-60 minutes of relaxed couple portraits at the same location. Book with Photo Portugal for a seamlessly coordinated proposal experience." },
      { question: "Will my partner know the photographer is there?", answer: "No — our proposal photographers are experts at blending in and remaining completely invisible until the moment you choose to reveal the surprise. They'll dress casually and position themselves to look like a tourist, a local enjoying the view, or a casual street photographer — common sights at Portugal's popular viewpoints and landmarks. They use telephoto lenses so they can shoot from 15-30 meters away without being noticed. Your photographer will send you their photo beforehand so you can recognize them and avoid accidentally drawing attention. After the proposal, you can surprise your partner with the news that everything was captured, or keep it a secret and reveal the photos later. Photo Portugal photographers have captured hundreds of successful surprise proposals across the country." },
      { question: "What if the weather is bad on proposal day?", answer: "Portugal enjoys over 300 days of sunshine per year, but your photographer will always have a backup plan ready. They'll prepare 2-3 alternative covered or indoor locations that are equally beautiful — such as tiled courtyards, historic arcades, covered terraces, or botanical garden pavilions. Your photographer will check the weather forecast 48 hours and again 24 hours before the session and proactively reach out with recommendations. If conditions are truly unfavorable (heavy rain, strong wind), free rescheduling is available at no extra cost. Many photographers also note that overcast skies actually create soft, flattering light perfect for intimate photos. Trust your Photo Portugal photographer to adapt and deliver stunning results regardless of conditions." },
      { question: "Can the photographer help me choose a proposal spot?", answer: "Absolutely — this is one of the most valuable parts of booking with Photo Portugal. Our photographers live and work in their cities and know the most romantic, private, and photogenic proposal spots intimately. They'll recommend locations based on your preferences (dramatic viewpoint vs. quiet garden vs. iconic landmark), the optimal time of day for lighting, typical crowd levels, and how private the moment will feel. In Lisbon, popular choices include Miradouro da Graca at sunset or a quiet corner of Alfama. In Sintra, the Regaleira palace gardens offer enchanting secluded terraces. In the Algarve, clifftop spots near Carvoeiro provide breathtaking ocean backdrops. Share your vision with your photographer and they'll suggest the perfect location to match." },
    ],
  },
  {
    slug: "engagement",
    name: "Engagement",
    title: "Engagement Photoshoot Portugal — Pre-Wedding Sessions",
    metaDescription:
      "Book an engagement photoshoot in Portugal. Professional pre-wedding photography in Lisbon, Porto, Sintra & Algarve. From €150.",
    h1: "Engagement Photoshoot in Portugal",
    heroText:
      "You said yes — now it's time to celebrate with stunning engagement photos in one of Europe's most romantic countries. Portugal offers an incredible variety of backdrops for your pre-wedding photoshoot: from Lisbon's sun-drenched terraces and Porto's historic riverside to Sintra's enchanted palaces and the Algarve's dramatic coastline. Sessions start from €150 for 60 minutes and include high-resolution digital files perfect for save-the-dates, wedding websites, and social media announcements. Whether you're planning a destination wedding in Portugal or simply want engagement photos in a breathtaking setting, our photographers will create images that capture the joy and excitement of this beautiful chapter in your love story.",
    bestLocations: [
      { slug: "lisbon", name: "Lisbon", reason: "Iconic trams, golden light, romantic rooftop terraces" },
      { slug: "sintra", name: "Sintra", reason: "Fairytale palaces, lush gardens, magical and romantic" },
      { slug: "douro-valley", name: "Douro Valley", reason: "Vineyard-covered hills, wine estates, editorial-quality settings" },
      { slug: "porto", name: "Porto", reason: "Colorful Ribeira district, historic bridges, artistic atmosphere" },
      { slug: "algarve", name: "Algarve", reason: "Dramatic cliffs, secret beaches, warm coastal light" },
    ],
    faqs: [
      { question: "How far in advance should we book our engagement photoshoot?", answer: "We recommend booking 2-4 weeks in advance, especially during peak season from May through September when Portugal's photographers are busiest with weddings and tourism. For specific dates like Valentine's Day or holiday weekends, booking 4-6 weeks ahead is wise. However, some photographers do accept last-minute bookings depending on their availability, so it's always worth checking even with shorter notice. When you book through Photo Portugal, you can browse real-time availability and secure your preferred photographer and time slot instantly. Off-season months (November through March) offer more flexibility, beautiful soft light, and fewer crowds at popular locations — a hidden gem for engagement photography in Portugal." },
      { question: "Can we use engagement photos for our save-the-dates?", answer: "Yes — this is one of the most popular reasons couples book engagement sessions in Portugal. You'll receive high-resolution digital files (typically 300 DPI) that are perfect for print-quality save-the-dates, wedding website headers, invitation inserts, and social media announcements. Most photographers deliver 40-80+ edited images within 1-3 weeks, with expedited delivery available if you're on a tight timeline for your stationery. Many photographers also offer a sneak peek of 5-10 images within 48 hours so you can start sharing the news immediately. The digital files come with full personal-use rights, so you can print them at any lab or use any design service. Photo Portugal photographers know how to frame shots that work beautifully in both landscape and portrait orientations for maximum versatility." },
      { question: "What's the difference between an engagement and couples session?", answer: "The photography experience itself is very similar — both involve 60-90 minutes of relaxed, natural couple photography at beautiful Portuguese locations. The main difference is intent and styling. Engagement sessions often focus on creating polished, formal photos specifically for wedding-related stationery like save-the-dates, invitations, and websites, so couples tend to dress slightly more formally or bring a second outfit. Photographers may also focus on capturing the ring and close-up hand details. Couples sessions are typically more casual and vacation-oriented, capturing your travel experience together. The pricing and duration are the same on Photo Portugal, so you can book either type and simply communicate your goals to your photographer during the pre-shoot consultation." },
      { question: "Can we combine our engagement session with wedding scouting?", answer: "Absolutely — this is a brilliant idea and something many destination-wedding couples do when visiting Portugal ahead of their big day. Your photographer can take you to potential ceremony venues, reception locations, and portrait spots while capturing beautiful engagement photos along the way. This gives you professional-quality venue photos to share with your wedding planner, florist, or family back home, plus a feel for how different locations photograph at various times of day. Popular scouting routes include Sintra's palace gardens, Douro Valley wine estates, Algarve clifftop venues, and Lisbon's historic palaces. Many Photo Portugal photographers have extensive wedding venue experience and can provide honest recommendations about which venues photograph best and during which season." },
    ],
  },
  {
    slug: "honeymoon",
    name: "Honeymoon",
    title: "Honeymoon Photographer Portugal — Capture Your First Adventure",
    metaDescription:
      "Book a honeymoon photoshoot in Portugal. Romantic photography for newlyweds in Lisbon, Algarve, Douro Valley & Madeira. From €150.",
    h1: "Honeymoon Photoshoot in Portugal",
    heroText:
      "Your honeymoon in Portugal deserves to be remembered with more than phone photos. Our photographers capture the romance, joy, and adventure of your first trip as newlyweds with sessions starting from €150 for 60 minutes. Imagine a sunrise session on the Algarve's golden cliffs, a golden hour stroll through Lisbon's most romantic neighborhoods, or a vineyard photoshoot in the Douro Valley with views that stretch for miles. You'll receive 50-100+ professionally edited photos delivered to a private online gallery. These are the images you'll frame above your fireplace, share with family, and look back on for decades. Relaxed, intimate, and beautifully natural — the perfect start to married life.",
    bestLocations: [
      { slug: "algarve", name: "Algarve", reason: "Secluded beaches, sunset cliffs, ultimate romantic backdrop" },
      { slug: "douro-valley", name: "Douro Valley", reason: "Wine country romance, vineyard terraces, golden landscapes" },
      { slug: "lisbon", name: "Lisbon", reason: "City of light — rooftop bars, tram rides, waterfront sunsets" },
      { slug: "madeira", name: "Madeira", reason: "Tropical gardens, dramatic cliffs, island paradise vibes" },
      { slug: "comporta", name: "Comporta", reason: "Bohemian luxury, pristine beaches, editorial-quality scenes" },
    ],
    faqs: [
      { question: "When should we schedule our honeymoon photoshoot?", answer: "Many couples book their photoshoot for the second or third day of their honeymoon, once they've settled in, recovered from jet lag, and explored the area a bit. This timing also gives you a weather buffer — if rain is forecast for day two, you can easily shift to day three or four. Evening golden hour sessions are the most popular for honeymooners, typically starting 1-2 hours before sunset for the warmest, most romantic light. If your honeymoon involves multiple cities (a common Portugal itinerary is Lisbon, Sintra, then Algarve or Porto), consider booking a session in the city that excites you most visually. Photo Portugal makes it easy to book — simply choose your preferred date and time during checkout and your photographer will confirm within 24 hours." },
      { question: "What's included in a honeymoon photoshoot package?", answer: "Most honeymoon packages on Photo Portugal include 60-120 minutes of professional photography, 50-100+ individually edited high-resolution photos delivered digitally to your own private online gallery, and a pre-shoot consultation to plan locations, timing, and styling. Photos are typically delivered within 1-3 weeks, with many photographers offering expedited delivery or a sneak peek of 5-10 images within 48 hours. Some photographers offer premium add-ons like handcrafted photo books, fine-art prints, or even a short cinematic video clip. All images come with full personal-use digital rights so you can print, share, and post freely. Delivery timelines and specific inclusions are clearly displayed on each photographer's package page on Photo Portugal." },
      { question: "Can we bring props like champagne or flowers?", answer: "Absolutely — props add a personal and celebratory touch that elevates honeymoon photos beautifully. Popular choices include a bottle of champagne or Portuguese sparkling wine, a fresh flower bouquet (available at most local markets for €10-20), 'Just Married' signs, picnic setups with a blanket and pastries, or even your wedding veil for a creative callback. Some photographers can arrange a styled picnic setup as an add-on, complete with flowers, fruit, and glassware — perfect for a Douro Valley vineyard or Algarve beach session. Keep props simple and meaningful; one or two items are usually enough to add personality without feeling staged. Your Photo Portugal photographer will advise on what works best for your chosen location and can suggest local shops for last-minute prop purchases." },
      { question: "Do you offer sunrise sessions?", answer: "Yes — sunrise sessions are absolutely stunning in Portugal and come with a major bonus: having famous locations nearly to yourselves while the rest of the city sleeps. In Lisbon, the early morning light over the Tagus River bathes the Alfama district in a soft pink-gold glow that's truly magical. In the Algarve, sunrise at Praia da Marinha or the Benagil coast offers dramatic cliff lighting without the daytime crowds. Porto's Ribeira district at sunrise is equally breathtaking, with golden light reflecting off the Douro River. Sunrise times vary by season — around 6:30am in summer and 8:00am in winter — so early starts are more manageable than you might think. Your Photo Portugal photographer will meet you at the agreed location on time and fully prepared, so you just need to show up and enjoy the experience." },
    ],
  },
  {
    slug: "solo",
    name: "Solo Travel",
    title: "Solo Travel Photoshoot Portugal — Professional Portraits",
    metaDescription:
      "Book a solo travel photoshoot in Portugal. Confident portraits at iconic locations in Lisbon, Porto & beyond. From €150.",
    h1: "Solo Travel Photography in Portugal",
    heroText:
      "Traveling solo doesn't mean you should be absent from your own vacation photos. Our photographers help solo travelers capture confident, beautiful portraits that tell the story of your Portugal adventure. Whether you want Instagram-worthy shots at iconic landmarks, natural lifestyle photos exploring local neighborhoods, or a mix of both, your photographer doubles as a local guide and creative director. Sessions start from €150 for 60 minutes and include 40-60+ professionally edited photos. Your photographer will guide you through natural poses and movements, helping you feel relaxed and confident in front of the camera within minutes. You'll walk away with a stunning portfolio of professional photos that capture your solo travel experience — no more asking strangers for blurry selfies.",
    bestLocations: [
      { slug: "lisbon", name: "Lisbon", reason: "Colorful streets, iconic trams, endless Instagram-worthy backdrops" },
      { slug: "porto", name: "Porto", reason: "Dramatic riverfront, azulejo-covered churches, artistic vibes" },
      { slug: "sintra", name: "Sintra", reason: "Fairytale castles, lush forests — incredible portrait settings" },
      { slug: "nazare", name: "Nazare", reason: "Dramatic ocean, clifftop fortress, raw Atlantic energy" },
    ],
    faqs: [
      { question: "I'm shy in front of the camera — will I look awkward?", answer: "Not at all — this is the most common concern solo travelers have, and our photographers hear it every week. They're experts at making camera-shy people feel at ease using simple, natural direction: walking toward the camera, looking out at a view, adjusting your hair, or laughing at a joke they tell. There's no stiff posing or awkward standing around. Most solo travelers say they felt completely relaxed within the first 5-10 minutes and actually enjoyed the experience. Your photographer will start with easy, movement-based shots to warm you up before moving to more portrait-style images. By the end, you'll feel like a natural. Book with Photo Portugal and discover how comfortable professional photography can be." },
      { question: "How many photos will I receive?", answer: "For a standard 1-hour session, expect 40-60+ professionally edited photos delivered to your private online gallery. A 2-hour session typically yields 80-120+ images, giving you an incredible variety of looks, locations, and moods. All images are delivered in high resolution (suitable for large prints up to poster size) and are also optimized for social media sharing. Most photographers deliver within 1-3 weeks, with sneak peeks of 5-10 top images often available within 48 hours. Every photo is individually color-corrected and edited — no batch filters or generic presets. The exact number depends on the session length and photographer style, and delivery details are clearly listed on each Photo Portugal photographer's package page." },
      { question: "Can I use the photos for my blog or social media?", answer: "Yes — all photos are yours to use however you'd like with full personal-use digital rights included in every Photo Portugal package. Share them on Instagram, TikTok, your travel blog, YouTube thumbnails, dating profiles, LinkedIn headshots, or simply keep them as personal memories. Many solo travelers use their Portugal photos across multiple platforms for months after their trip, creating a library of professional content from a single session. If you're a professional blogger or content creator with commercial use needs (brand partnerships, paid campaigns, stock licensing), discuss this with your photographer at booking — most are happy to accommodate. Your photographer may ask for a social media tag or credit, which is a great way to support their work." },
      { question: "What if I want both portrait and landmark photos?", answer: "Our photographers excel at mixing close-up portrait-style shots with wider environmental photos that show you in context with Portugal's stunning architecture, coastlines, and streetscapes. A 1-2 hour session gives plenty of time for both: intimate headshots and three-quarter portraits for profiles and dating apps, plus full-body lifestyle shots at iconic landmarks like Lisbon's Tram 28, Porto's Sao Bento station, or Sintra's colorful palaces. The key is variety — your photographer will shift between tight and wide compositions, different angles, and multiple backdrops to give you a diverse gallery. Sharing a mood board or Pinterest inspiration before the session helps your Photo Portugal photographer understand your preferred balance of portrait versus landmark shots." },
    ],
  },
  {
    slug: "elopement",
    name: "Elopement",
    title: "Elopement Photographer Portugal — Intimate Ceremony Photography",
    metaDescription:
      "Hire an elopement photographer in Portugal. Intimate ceremonies in Sintra, Algarve, Lisbon & Douro Valley. From €300.",
    h1: "Elopement Photography in Portugal",
    heroText:
      "Portugal has become one of Europe's most popular elopement destinations, and for good reason. Imagine exchanging vows in a fairytale palace garden in Sintra, on a dramatic Algarve clifftop overlooking the Atlantic, or in a centuries-old Lisbon courtyard bathed in golden light. Our elopement photographers don't just take photos — they document the intimate, emotional journey of your most special day. Elopement packages start from €300 for 2-4 hours of coverage, including getting-ready moments, the ceremony, couple portraits, and celebration dinner. Full-day coverage up to 8 hours is also available. Portugal's year-round sunshine, diverse landscapes, affordable luxury, and welcoming culture make it the perfect elopement destination for couples from around the world.",
    bestLocations: [
      { slug: "sintra", name: "Sintra", reason: "Pena Palace, Monserrate gardens — fairy-tale ceremony settings" },
      { slug: "algarve", name: "Algarve", reason: "Clifftop ceremonies, beach vows, sunset celebrations" },
      { slug: "lisbon", name: "Lisbon", reason: "Historic venues, rooftop ceremonies, old-world romance" },
      { slug: "douro-valley", name: "Douro Valley", reason: "Vineyard wedding venues, wine country celebrations" },
      { slug: "evora", name: "Evora", reason: "Ancient Roman ruins, Alentejo countryside, rustic elegance" },
    ],
    faqs: [
      { question: "Do I need a permit to elope in Portugal?", answer: "For a symbolic ceremony (non-legal), you generally don't need permits for most public outdoor locations like beaches, parks, and viewpoints, though some specific sites like Pena Palace in Sintra or Monserrate Gardens may require advance booking or a small access fee. Private venues like wine estates or boutique hotels typically include ceremony permissions in their rental fee. For a legally binding ceremony, you'll need to register at a local civil registry office (Conservatoria do Registo Civil) and provide documentation including birth certificates and proof of single status translated into Portuguese. The process takes 2-4 weeks. Your Photo Portugal photographer can connect you with experienced local wedding planners who handle all the legal logistics, paperwork, and venue permissions so you can focus on enjoying the day." },
      { question: "How long does an elopement photography session last?", answer: "Elopement photography sessions typically last 2-4 hours, which is enough to beautifully cover getting ready, the walk to the ceremony spot, the vow exchange, ring ceremony, first kiss, couple portraits in multiple locations, and initial celebration moments like a champagne toast. This timeframe works perfectly for intimate elopements with just the two of you or a small group of up to 10 guests. For couples who want comprehensive all-day coverage — including morning preparations, a multi-location portrait session, the ceremony, and a celebration dinner — full-day packages of 6-8 hours are available from select Photo Portugal photographers. Your photographer will help you build a realistic timeline so every important moment is captured without feeling rushed." },
      { question: "Can our photographer recommend ceremony locations?", answer: "Yes — this is one of the biggest advantages of booking an elopement photographer through Photo Portugal. Our photographers have extensive local knowledge of the most beautiful, intimate, and photogenic ceremony spots, including hidden locations that tourists rarely discover. They'll recommend options based on your personal style, number of guests, time of year, and preferred atmosphere. For fairy-tale settings, they might suggest the mossy terraces of Quinta da Regaleira in Sintra. For dramatic coastal vows, a secluded Algarve clifftop near Carvoeiro. For urban romance, a private courtyard in Lisbon's Alfama quarter. For wine-country elegance, a terraced vineyard overlook in the Douro Valley. Many photographers also have relationships with private venues and can help arrange exclusive access for your ceremony." },
      { question: "What about witnesses — do we need them?", answer: "For a legally binding ceremony in Portugal, you need two witnesses who are at least 18 years old. Many eloping couples bring a close friend or family member to serve this role, making the day even more special. However, if you're eloping as just the two of you with no guests, there are practical solutions: your photographer and a second shooter, wedding planner, or officiant's assistant can often serve as official witnesses. Some Photo Portugal photographers specifically offer this as part of their elopement package. For symbolic (non-legal) ceremonies, there's no witness requirement at all — it's just you, your partner, and your photographer capturing the moment. If you plan to legalize the marriage in your home country afterward, check your country's specific requirements for foreign ceremonies and documentation." },
    ],
  },
  {
    slug: "friends",
    name: "Friends Trip",
    title: "Friends Trip Photoshoot Portugal — Group & Bachelorette Photos",
    metaDescription:
      "Book a friends trip photoshoot in Portugal. Bachelorette parties, birthdays & group vacations in Lisbon, Porto & Algarve. From €150.",
    h1: "Friends Trip Photoshoot in Portugal",
    heroText:
      "Traveling with friends to Portugal? Make it unforgettable with a professional group photoshoot. Whether it's a bachelorette weekend in Lisbon, a birthday celebration in Porto, or a reunion trip to the Algarve, our photographers know how to capture the energy, laughter, and connection of your group. Sessions start from €150 for groups of 2-10 and include both posed group portraits and candid moments at stunning locations. From rooftop bars and vibrant street art to dramatic coastal cliffs, you'll leave with photos that everyone in the group will actually want to post. No more awkward group selfies, cut-off heads, or asking strangers for blurry photos — book with Photo Portugal and get professional results.",
    bestLocations: [
      { slug: "lisbon", name: "Lisbon", reason: "Vibrant nightlife areas, rooftop bars, colorful street art" },
      { slug: "porto", name: "Porto", reason: "Wine cellars, riverfront, Instagram-worthy spots everywhere" },
      { slug: "algarve", name: "Algarve", reason: "Beach days, boat trips, cliff-top group shots" },
      { slug: "cascais", name: "Cascais", reason: "Beach town charm, coastal walks, relaxed group vibes" },
    ],
    faqs: [
      { question: "How many people can be in a group photoshoot?", answer: "Most photographers on Photo Portugal accommodate groups of 2-10 people in their standard packages at no extra charge per person. For larger groups of 10-20+, let us know in advance and we'll pair you with photographers experienced in managing large group dynamics, or arrange two photographers working simultaneously to capture different angles and sub-group combinations. For groups over 15, having two photographers ensures everyone gets individual attention alongside the big group shots. Your photographer will organize a mix of full-group portraits, smaller sub-group combinations (the bride and her sisters, college roommates, etc.), and individual moments. Book early during peak season (May-September) when bachelorette and group bookings fill up quickly in popular cities like Lisbon and Porto." },
      { question: "Can we do a photoshoot during a bachelorette party?", answer: "Absolutely — bachelorette photoshoots are one of our most popular group bookings on Photo Portugal. Groups of 4-12 friends typically book 60-90 minute sessions starting from €150-250 depending on group size and duration. Photographers capture both fun, posed group shots and candid party moments that feel natural and energetic. Props, matching outfits, creative themes, and bride-to-be accessories are all welcome and encouraged. Popular locations include Lisbon's Pink Street and LX Factory for fun urban vibes, Porto's Ribeira district and wine cellars for sophisticated charm, and the Algarve beaches for a sun-soaked celebration. Most photographers bring positive energy and help with creative posing to keep the group laughing. Book at least 2-3 weeks ahead during peak season to secure your preferred photographer and time slot." },
      { question: "What if some people in the group are camera-shy?", answer: "Our photographers are experts at making everyone feel included and comfortable regardless of their confidence level in front of a camera. They'll start with easy group activities — walking together, linking arms, laughing at a shared joke — that naturally bring out authentic expressions without anyone feeling singled out. The session alternates between posed group portraits and candid documentary-style moments, so camera-shy friends often don't even realize they're being photographed during the best shots. Photographers also capture a mix of the full group, pairs, and small clusters, giving shy individuals the comfort of being alongside their closest friends. By the end of the session, even the most reluctant group members are usually having a great time. Photo Portugal photographers hear 'I actually loved that!' from self-described camera-shy clients every week." },
      { question: "Can we combine a photoshoot with a food or wine tour?", answer: "This is a fantastic idea and creates some of the most memorable, authentic group photos. Many Photo Portugal photographers offer extended 2-3 hour sessions that can incorporate stops at local restaurants, rooftop bars, traditional tascas, wine cellars, or food markets like Lisbon's Time Out Market or Porto's Bolhao Market. This documentary-style approach captures your group naturally enjoying the real Portugal experience — clinking glasses over port wine, sharing pasteis de nata, browsing market stalls, and exploring neighborhoods together. Some photographers can recommend specific foodie routes that combine great backdrops with delicious stops. In Porto, a session that includes the Ribeira district and a port wine cellar visit is especially popular. Discuss your vision when booking through Photo Portugal and your photographer will build a custom itinerary." },
    ],
  },
  {
    slug: "wedding",
    name: "Wedding",
    title: "Wedding Photographer Portugal — Destination Wedding Photography",
    metaDescription:
      "Hire a wedding photographer in Portugal. Destination weddings in Lisbon, Sintra, Algarve, Douro Valley & more. Verified professionals. From €500.",
    h1: "Wedding Photography in Portugal",
    heroText:
      "Portugal has become one of Europe's most sought-after destination wedding locations — and with good reason. From vineyard estates in the Douro Valley to oceanfront venues in the Algarve, historic palaces in Sintra to rooftop celebrations in Lisbon, every setting tells a unique story. Our wedding photographers combine documentary-style storytelling with fine-art portraits, capturing every emotion from the nervous excitement of getting ready to the last dance of the night. Wedding photography packages start from €500 for 6 hours of coverage, with full-day packages up to 16 hours available. They know Portugal's best venues, light conditions, and hidden spots for stunning couple portraits between celebrations. Browse verified wedding portfolios on Photo Portugal to find your perfect match.",
    bestLocations: [
      { slug: "sintra", name: "Sintra", reason: "Palace venues, fairytale gardens, magical ceremony backdrops" },
      { slug: "algarve", name: "Algarve", reason: "Clifftop venues, beach ceremonies, golden sunset receptions" },
      { slug: "douro-valley", name: "Douro Valley", reason: "Vineyard estates, wine country elegance, panoramic terraces" },
      { slug: "lisbon", name: "Lisbon", reason: "Historic palaces, rooftop venues, city-view celebrations" },
      { slug: "comporta", name: "Comporta", reason: "Bohemian beach weddings, rice paddies, barefoot luxury" },
    ],
    faqs: [
      { question: "How far in advance should we book a wedding photographer in Portugal?", answer: "For peak wedding season (May through October), we strongly recommend booking 6-12 months in advance, especially for Saturday weddings at popular venues. Portugal's top wedding photographers often have their prime summer dates booked a full year ahead, particularly in sought-after regions like the Algarve, Sintra, and Douro Valley. For off-season weddings (November through April), you'll have more flexibility and may find availability with 2-3 months notice. Weekday weddings also tend to have better photographer availability year-round. When you find a photographer you love on Photo Portugal, secure your date with a deposit to lock in their availability — the earlier you book, the wider your selection of top-rated professionals." },
      { question: "How many hours of coverage do we need?", answer: "Most destination wedding couples book 8-12 hours of photography coverage, which captures the complete story from getting-ready preparations through the ceremony, cocktail hour, dinner, speeches, first dance, and party. For more intimate weddings (under 30 guests) or shorter celebrations, 6 hours of coverage may be sufficient to capture all the key moments. Full-day packages of up to 16 hours are available for extended celebrations that start with morning preparations and continue through a late-night party or after-party. When estimating your needs, consider adding a buffer of 1-2 hours beyond what you think you'll need — the candid moments between events are often the most treasured. Your Photo Portugal photographer will help you build a realistic photography timeline during your pre-wedding consultation." },
      { question: "Do photographers travel to any venue in Portugal?", answer: "Yes — Photo Portugal photographers cover weddings across the entire country, from the northern Minho region to the southern Algarve coast, and even the islands of Madeira and the Azores. Travel within the photographer's home region (typically a 50-80km radius) is included in standard packages at no extra charge. For weddings in other regions — for example, a Lisbon-based photographer traveling to an Algarve venue — a small travel fee may apply to cover transport and accommodation. This fee is always shown upfront and transparently in each photographer's package listing, so there are no surprises. Many photographers also offer multi-day packages for destination weddings that include a rehearsal dinner shoot or day-after session, which is especially popular for international couples hosting a wedding weekend in Portugal." },
      { question: "Can we book a second photographer?", answer: "Absolutely — and for weddings with 80 or more guests, we strongly recommend it. A second photographer captures simultaneous moments that a single photographer would miss: both getting-ready preparations happening in different locations, guest reactions during the ceremony while the main photographer focuses on the couple, candid cocktail hour moments while the couple does portraits, and different angles of the first dance and speeches. Many Photo Portugal photographers offer second-shooter add-ons that can be added to any package. The second photographer typically provides 30-50% additional images from unique perspectives, giving you a richer, more complete visual story of your wedding day. For very large weddings (150+ guests) or multi-venue celebrations, some couples even book a third photographer to ensure comprehensive coverage." },
    ],
  },
  {
    slug: "maternity",
    name: "Maternity",
    title: "Maternity Photographer Portugal — Beautiful Pregnancy Photos",
    metaDescription:
      "Book a maternity photoshoot in Portugal. Stunning pregnancy photography in Lisbon, Cascais, Sintra & Algarve. Natural, elegant sessions. From €150.",
    h1: "Maternity Photoshoot in Portugal",
    heroText:
      "Pregnancy is one of life's most beautiful chapters, and Portugal provides the perfect backdrop to celebrate it. Whether you're a local expecting parent or visiting Portugal during your pregnancy, our photographers specialize in creating elegant, natural maternity portraits that you'll cherish forever. Sessions start from €150 for 60 minutes and are best scheduled between 28-34 weeks when your bump is beautifully visible. From the golden beaches of Cascais to Lisbon's sun-drenched botanical gardens, Sintra's romantic palace grounds to the Algarve's dramatic coastline — every location offers a unique atmosphere for this milestone. Our photographers know how to make you feel comfortable, confident, and absolutely radiant throughout the session.",
    bestLocations: [
      { slug: "cascais", name: "Cascais", reason: "Sandy beaches, soft coastal light, relaxed seaside atmosphere" },
      { slug: "lisbon", name: "Lisbon", reason: "Botanical gardens, golden hour rooftops, elegant urban backdrops" },
      { slug: "sintra", name: "Sintra", reason: "Romantic forest paths, palace gardens, dreamy natural settings" },
      { slug: "algarve", name: "Algarve", reason: "Golden cliffs, serene beaches, warm Mediterranean light" },
    ],
    faqs: [
      { question: "When is the best time for a maternity photoshoot?", answer: "Most photographers recommend scheduling your maternity session between 28-34 weeks of pregnancy, when your bump is beautifully round and visible but you're still comfortable moving around, sitting, standing, and walking to different locations. The sweet spot for many women is around 30-32 weeks. However, every pregnancy is different — women carrying twins or those who show earlier may want to book at 24-28 weeks, while others are comfortable shooting up to 36 weeks. Time of day matters too: golden hour (1-2 hours before sunset) provides the softest, most flattering light that makes skin glow. Book your session with Photo Portugal at least 2-3 weeks ahead of your preferred date to ensure availability, and leave a buffer week in case you need to reschedule due to how you're feeling." },
      { question: "What should I wear for a maternity session?", answer: "Flowing maxi dresses, form-fitting fabrics that accentuate your bump, and neutral or soft colors photograph beautifully in Portugal's warm-toned landscapes. Popular color choices include white, cream, dusty rose, sage green, and lavender — these work wonderfully against both beach and garden settings. Many Photo Portugal photographers have a curated collection of maternity gowns, sheer wraps, and fabrics you can borrow at no extra charge, so don't feel pressured to buy something new. Bring 1-2 outfit options so you can get variety in your gallery. Comfortable flat sandals or bare feet work best for beach sessions. Avoid busy patterns and bold logos. Your photographer will send a detailed style guide after booking with specific recommendations for your chosen location, season, and personal style." },
      { question: "Can my partner and other children be included?", answer: "Absolutely — family maternity sessions are one of the most heartwarming types of photoshoots we facilitate on Photo Portugal. Your photographer will capture a beautiful mix of solo maternity portraits showcasing your bump, intimate couple moments with your partner, and joyful family photos with your other children. Including siblings creates especially precious images: little hands on the bump, a toddler kissing mama's belly, or the whole family walking hand-in-hand are consistently among parents' favorite photos. Partners are typically involved for about half the session, with the other half focused on elegant solo maternity portraits. There's no extra charge for including family members in most standard packages. If you have young children, your photographer will keep the session fun and relaxed with play and movement." },
      { question: "What if I'm not feeling well on the day of the shoot?", answer: "Your comfort and wellbeing are the absolute top priority for every Photo Portugal maternity session. If you wake up not feeling well on the day of your shoot, free rescheduling is available with all our photographers — no questions asked, no penalties. Simply message your photographer and they'll find a new date that works. During the session itself, photographers pace maternity shoots gently with plenty of sitting breaks, water stops, and rest moments between locations. They'll never ask you to hold an uncomfortable position or walk further than you're comfortable with. Most maternity sessions in Portugal are designed around 1-2 nearby locations rather than extensive walking routes. Our photographers are experienced with pregnant clients and intuitively adjust their approach based on how you're feeling in the moment — your comfort always comes first." },
    ],
  },
  {
    slug: "anniversary",
    name: "Anniversary",
    title: "Anniversary Photoshoot Portugal — Celebrate Your Love Story",
    metaDescription:
      "Book an anniversary photoshoot in Portugal. Romantic photography for couples celebrating milestones in Lisbon, Porto, Sintra & Algarve. From €150.",
    h1: "Anniversary Photoshoot in Portugal",
    heroText:
      "Whether it's your 1st or your 50th, an anniversary trip to Portugal deserves to be captured beautifully. Our photographers specialize in creating relaxed, romantic portraits that reflect the depth and warmth of your relationship. Sessions start from €150 and include 40-80+ professionally edited photos. Imagine recreating the magic of your early days against the backdrop of Lisbon's golden-lit streets, raising a toast in a Douro Valley vineyard, or walking hand-in-hand along the Algarve coast at sunset. Anniversary photoshoots celebrate where your love has been and where it's going — and Portugal, with its warm light, rich culture, and intimate atmosphere, is the perfect place to tell that story. Book with Photo Portugal for a truly memorable milestone experience.",
    bestLocations: [
      { slug: "lisbon", name: "Lisbon", reason: "Romantic rooftop dinners, golden hour walks, intimate Alfama streets" },
      { slug: "douro-valley", name: "Douro Valley", reason: "Wine tasting sessions, vineyard views, luxurious countryside" },
      { slug: "sintra", name: "Sintra", reason: "Timeless palace settings, romantic gardens, fairytale atmosphere" },
      { slug: "porto", name: "Porto", reason: "Riverside romance, port wine cellars, sunset over the Douro" },
      { slug: "algarve", name: "Algarve", reason: "Beach walks, cliff-top moments, golden coastal light" },
    ],
    faqs: [
      { question: "Can we incorporate a special dinner or activity into the shoot?", answer: "Yes — this is one of the most popular ways to elevate an anniversary photoshoot in Portugal. Many couples combine their session with a sunset dinner at a waterfront restaurant, a private wine tasting at a Douro Valley estate, a boat ride on the Tagus River in Lisbon, or a port wine cellar visit in Porto. Extended 2-3 hour sessions work perfectly for this approach, allowing your photographer to capture both the portrait session and the celebration activity naturally and seamlessly. The result is a documentary-style gallery that tells the complete story of your anniversary experience, not just posed portraits. Discuss your ideal celebration with your Photo Portugal photographer during the pre-shoot consultation and they'll build a timeline that combines beautiful photography with a genuinely enjoyable experience." },
      { question: "We're not used to being photographed — will it feel awkward?", answer: "Not at all — anniversary sessions are actually the most relaxed type of couples photography because you already know each other so well. There's a natural comfort, chemistry, and ease between long-term partners that photographs beautifully. Your photographer will give gentle direction but mostly focuses on capturing authentic moments: walking hand-in-hand, whispering, laughing at a shared memory, clinking glasses over a drink. There's very little traditional posing involved. Most anniversary couples tell us afterward that it felt like a romantic date, not a photoshoot — and that's exactly the intention. The first 5-10 minutes are always the most self-conscious, but once you're strolling through a beautiful Portuguese neighborhood together, the camera quickly becomes invisible. Book with Photo Portugal and enjoy a relaxed, memorable experience." },
      { question: "Can we recreate our wedding photos or a special moment?", answer: "Absolutely — this is one of the most meaningful and popular requests for anniversary photoshoots. Bring along any sentimental props or wardrobe items: your wedding veil, a framed photo from your wedding day, your original bouquet flowers (or a recreation), a meaningful piece of jewelry, or even your wedding outfits if they still fit. Some couples recreate their first dance pose, their wedding kiss moment, or a specific composition from their original wedding photos in a new Portuguese setting. Photographers love incorporating these personal elements because they add emotional depth and storytelling to the gallery. Share your original wedding photos with your Photo Portugal photographer beforehand and they'll suggest creative ways to honor those memories while creating something fresh and beautiful in their Portuguese location." },
      { question: "Is this a good gift idea?", answer: "Anniversary photoshoots are consistently one of the most popular gift bookings on Photo Portugal — and one of the highest-rated in post-session feedback. You can book a session and receive a beautifully designed digital gift voucher to present to your partner, with a personal message included. The voucher allows your partner (or both of you together) to choose the specific date, time, location, and photographer when you're ready. Gift vouchers are valid for 12 months, giving you flexibility to plan the perfect trip. Many partners say it was the most thoughtful and memorable anniversary gift they've ever received — far more meaningful than material items. It's especially popular for milestone anniversaries (5th, 10th, 25th, 50th) and for couples who prioritize experiences over things. A truly unique way to celebrate your love story in Portugal." },
    ],
  },
  {
    slug: "birthday",
    name: "Birthday",
    title: "Birthday Photoshoot Portugal — Celebrate in Style",
    metaDescription:
      "Book a birthday photoshoot in Portugal. Solo or group celebrations in Lisbon, Porto & Algarve. Fun, professional photography. From €150.",
    h1: "Birthday Photoshoot in Portugal",
    heroText:
      "What better way to celebrate your birthday than with a professional photoshoot in one of Europe's most beautiful countries? Whether you're marking a milestone birthday with a solo portrait session, celebrating with your best friends in Lisbon, or having a family birthday getaway in the Algarve, our photographers capture the joy and energy of the occasion. Sessions start from €150 for solo or group bookings and include 40-80+ edited photos. From chic urban settings and rooftop bars to sun-drenched beaches, colorful tiled streets, and dramatic coastal cliffs, Portugal offers endless stunning backdrops for birthday photos you'll actually want to frame, post, and look back on for years to come. Book your birthday photoshoot with Photo Portugal today.",
    bestLocations: [
      { slug: "lisbon", name: "Lisbon", reason: "Rooftop bars, vibrant streets, colorful neighborhoods" },
      { slug: "porto", name: "Porto", reason: "Wine cellars, riverside charm, Instagram-worthy spots" },
      { slug: "algarve", name: "Algarve", reason: "Beach parties, sunset cliffs, resort celebrations" },
      { slug: "cascais", name: "Cascais", reason: "Coastal elegance, beachfront restaurants, relaxed vibes" },
    ],
    faqs: [
      { question: "Can we do a photoshoot during a birthday dinner or party?", answer: "Yes — photographers can cover your birthday dinner at a Portuguese restaurant, rooftop party overlooking the city, beach celebration, or any gathering. Extended sessions of 2-3 hours work best for event coverage, capturing the full atmosphere from guests arriving and mingling through toasts, cake cutting, and celebrations. For dinner events, photographers skilled in low-light or indoor photography are ideal — mention this when booking on Photo Portugal and we'll match you accordingly. Popular birthday dinner locations include Lisbon's rooftop terraces with river views, Porto's wine cellars with atmospheric lighting, and Algarve beachfront restaurants at sunset. Your photographer will blend into the event naturally, capturing both candid guest moments and key posed group shots without disrupting the celebration flow." },
      { question: "Is this good for milestone birthdays (30th, 40th, 50th)?", answer: "Milestone birthday photoshoots are among the most popular bookings on Photo Portugal, and for good reason — turning 30, 40, 50, or beyond deserves more than a phone selfie. Many clients use these professional photos for social media announcements, party invitations, birthday video montages, or simply as a personal celebration and confidence boost at a meaningful age. Your photographer will make you feel and look amazing, capturing your best angles in Portugal's most flattering light. Solo milestone sessions often have a fashion-editorial feel, while group milestone celebrations capture the energy and love of your closest people. Some clients book a session as a birthday gift to themselves — an empowering experience that combines travel, self-celebration, and stunning photography. Photo Portugal photographers are experts at making every age look incredible." },
      { question: "Can we bring balloons, cake, or other props?", answer: "Absolutely — birthday props add personality, color, and fun to the photos and are highly encouraged. Popular choices include foil number balloons (available at party shops in every major Portuguese city for €5-15), confetti poppers for a burst of celebration, a small decorated cake or cupcakes from a local bakery, champagne or Portuguese sparkling wine, birthday banners, party hats, and sparklers for dramatic evening shots. Your photographer can suggest specific locations that work well with props — open plazas and beaches are ideal for balloons and confetti, while intimate cafes and rooftop bars suit cake and champagne setups. Keep in mind that Portugal has strict rules about littering, so choose biodegradable confetti and clean up after. Your Photo Portugal photographer will help coordinate the prop timing for maximum visual impact." },
      { question: "Can we combine the photoshoot with a group activity?", answer: "Many birthday groups combine their photoshoot with a memorable group activity, creating a richer, more authentic set of photos that tells the story of the entire celebration. Popular combinations include a walking food tour through Lisbon's Alfama or Bairro Alto neighborhoods, a port wine tasting and cellar tour in Porto's Vila Nova de Gaia, a sunset boat trip along the Algarve coast, or a cooking class at a Portuguese culinary school. Your photographer can join for part or all of the activity, capturing candid moments alongside more posed group portraits. Extended 2-3 hour sessions work best for this format, giving enough time for both the activity and dedicated portrait stops at photogenic locations. Discuss your ideal birthday itinerary when booking through Photo Portugal and your photographer will build a custom plan that balances great photography with genuine fun." },
    ],
  },
  {
    slug: "content-creator",
    name: "Content Creator",
    title: "Content Creator Photography Portugal — Professional Content Shoots",
    metaDescription:
      "Book a content creator photoshoot in Portugal. Instagram, TikTok & brand content in Lisbon, Porto & Algarve. Professional quality. From €150.",
    h1: "Content Creator Photography in Portugal",
    heroText:
      "Portugal is a content creator's dream — vibrant colors, incredible architecture, golden light, and endless variety within a compact area. Our photographers understand the content creation world: they know which angles work for Instagram Reels vs. static feed posts, how to capture both vertical and horizontal compositions, and how to create a cohesive set of images that elevates your personal brand. Sessions start from €150 for 60 minutes and deliver 50-80+ optimized photos. Whether you need a batch of Instagram content, TikTok behind-the-scenes clips, LinkedIn headshots, or brand photography for your website and press kit, our photographers deliver scroll-stopping content that performs. Book with Photo Portugal and walk away with weeks of professional content from a single session.",
    bestLocations: [
      { slug: "lisbon", name: "Lisbon", reason: "Colorful tiles, trams, pink streets — the most 'grammable city in Europe" },
      { slug: "porto", name: "Porto", reason: "Blue azulejos, Lello Bookshop, Ribeira — instantly recognizable backdrops" },
      { slug: "sintra", name: "Sintra", reason: "Fairytale castles, lush gardens — fantasy content that goes viral" },
      { slug: "algarve", name: "Algarve", reason: "Benagil Cave, golden cliffs, turquoise water — travel content gold" },
    ],
    faqs: [
      { question: "How many photos will I get for my content?", answer: "For a standard 1-hour session, expect 50-80+ photos specifically optimized for social media use. A 2-hour session typically yields 100-150+ images, giving you an extensive content library. Photographers deliver high-resolution original edits and can provide cropped versions formatted for different platforms: 4x5 for Instagram feed, 9x16 for Stories and Reels, 16x9 for YouTube thumbnails, and square for profile photos. This means a single session can supply weeks or even months of content across multiple platforms. Many creators book a 2-hour session across 3-4 locations to maximize variety in backgrounds, lighting, and outfit changes. Turnaround is typically 1-2 weeks, with a sneak peek of top images often available within 48 hours so you can start posting during your trip. Photo Portugal photographers understand content creators' needs for volume, variety, and platform optimization." },
      { question: "Can the photographer shoot video too?", answer: "Some Photo Portugal photographers offer hybrid photo and video packages, which are increasingly popular for content creators who need Reels, TikTok clips, and YouTube content alongside static photos. When browsing photographers, look for those who list video in their services or hybrid packages on their profile. Typical video deliverables include 3-5 short-form clips (15-60 seconds) edited with transitions and music, plus raw b-roll footage you can edit yourself. For dedicated video-only needs, some photographers work with a videographer partner for a two-person setup. If video is essential to your session, mention this when booking so we can match you with the right photographer. The best hybrid sessions alternate between photo and video moments, capturing both your styled poses and natural behind-the-scenes movement that performs well on short-form platforms." },
      { question: "Can I get a mix of candid and posed content?", answer: "Absolutely — a mix of candid and styled content is the standard approach for creator sessions on Photo Portugal and produces the most versatile, authentic-feeling gallery. Your photographer will capture a balanced mix of walking shots, laughing candids, look-away moments, styled editorial poses, flat lays, and detail shots of outfits or accessories. Many content creators bring a shot list, mood board, or Pinterest board of specific compositions they need, which photographers love working from — it ensures nothing gets missed. The candid walking and exploring moments feel authentic and perform well for Reels and Stories, while the styled posed shots give you polished feed content and website imagery. If you have specific brand partnerships or sponsored deliverables, share the brand guidelines with your photographer beforehand and they'll incorporate those specific shots seamlessly into the session flow." },
      { question: "Do you work with brands and influencers?", answer: "Yes — many Photo Portugal photographers have extensive experience with brand campaigns, sponsored content shoots, press trips, and influencer collaborations across fashion, travel, food, and lifestyle verticals. They understand how to work from brand guidelines, detailed shot lists, and specific deliverable requirements including usage rights, exclusivity periods, and approval workflows. For brand partnerships, photographers can deliver images with specific crop ratios, color grading that matches your brand aesthetic, and even white-label files without photographer watermarks. We also offer custom brand partnership packages for agencies and PR companies coordinating multi-creator campaigns in Portugal. Whether you're a micro-influencer with 5K followers or a major creator with a six-figure audience, Photo Portugal can match you with a photographer who understands your specific content needs and audience expectations." },
    ],
  },
];

export function getShootTypeBySlug(slug: string): ShootType | undefined {
  return shootTypes.find((t) => t.slug === slug);
}
