// Photo Italy blog — batch 7: couples, elopements and family, EN + IT pairs.
// Ends the one-post state of those categories in both core locales.
export const POSTS = [
  {
    "slug": "servizio-di-coppia-in-italia-come-funziona-quell-ora",
    "locale": "it",
    "category": "couples",
    "published_at": "2026-07-30T09:00:00Z",
    "title": "Servizio fotografico di coppia in Italia: com'è davvero quell'ora",
    "meta_title": "Servizio di coppia in Italia: come funziona l'ora",
    "meta_description": "Minuto per minuto: come si svolge un servizio di coppia in Italia, cosa vi farà fare il fotografo, quando arrivano le foto e perché nessuno deve saper posare.",
    "target_keywords": "servizio fotografico di coppia come funziona, cosa aspettarsi servizio di coppia, foto di coppia in vacanza italia, servizio coppia roma firenze",
    "excerpt": "I primi dieci minuti sono i più rigidi per tutti. Poi si cammina, si ride, e la fotocamera sparisce: ecco il copione reale di un'ora di coppia.",
    "content": "## Nessuno dei due deve saper posare\n\nLa paura più comune prima di un servizio di coppia non riguarda i luoghi né la luce: è \"non sappiamo stare davanti alla fotocamera\". La risposta onesta è che non serve. Un buon servizio di coppia non è una sequenza di pose: è una passeggiata diretta da qualcuno che sa dove mettervi e cosa chiedervi, e le foto succedono lungo la strada.\n\n## Minuto per minuto\n\n**0-10: i minuti rigidi.** Lo sono per tutti, sempre. Il fotografo lo sa e li usa per le cose facili: si cammina mano nella mano, si parla, si guarda il panorama. Queste prime foto raramente sono le migliori — servono a farvi dimenticare l'obiettivo.\n\n**10-25: il movimento.** Camminate verso la fotocamera, uno fa girare l'altra, qualcuno dice una sciocchezza e la risata è vera. I comandi sono semplici e fisici — \"avvicinati alla sua spalla\", \"guardala mentre cammina\" — mai \"siate naturali\", che è l'istruzione più innaturale del mondo.\n\n**25-45: il posto migliore, la luce migliore.** A questo punto siete caldi e il fotografo vi porta nel punto per cui ha costruito il percorso — il belvedere, il vicolo, il lungofiume — nell'ora in cui la luce lo merita. Qui nascono le foto da parete.\n\n**45-60: i dettagli e il gioco.** Mani, anelli, un ballo accennato, il gelato comprato al volo. Le ultime foto sono le più sciolte, e spesso le preferite.\n\n## Cosa decide la riuscita (e non è la vostra fotogenia)\n\n- **L'orario.** L'ora dorata — dopo l'alba o prima del tramonto — perdona tutto; il mezzogiorno estivo non perdona niente. Se il fotografo vi propone le 6:30, c'è un motivo.\n- **Le scarpe.** Sampietrini, salite, scale: si cammina comodi e si cambia per l'inquadratura.\n- **Due outfit al massimo.** Uno elegante, uno rilassato. I cambi mangiano minuti di luce.\n- **Dirlo, se c'è un lato che odiate.** Il fotografo lavora intorno a qualsiasi insicurezza, ma solo se la conosce.\n\n## Dopo\n\nUn'anteprima di 5-10 scatti arriva spesso entro 48 ore; la galleria completa — in genere 40-60+ foto per un'ora — entro una-tre settimane, tutte ritoccate una a una. I file sono vostri, in alta risoluzione, da stampare e condividere liberamente.\n\n## Dove farlo\n\nL'ora di coppia funziona ovunque, ma tre combinazioni non sbagliano mai: Roma all'alba per avere il centro vuoto, Firenze all'ora dorata per il fiume e i ponti, la Costiera al tramonto per le falesie. La [pagina dei servizi di coppia](/photoshoots/couples) elenca fotografi e pacchetti; per scegliere la città ci sono le guide di [Roma](/locations/rome) e [Firenze](/locations/florence).\n"
  },
  {
    "slug": "couples-photoshoot-in-italy-what-the-hour-looks-like",
    "locale": "en",
    "category": "couples",
    "published_at": "2026-07-30T09:00:00Z",
    "title": "A Couples Photoshoot in Italy: What the Hour Actually Looks Like",
    "meta_title": "Couples Photoshoot in Italy: What to Expect",
    "meta_description": "Minute by minute: how a couples photoshoot in Italy really unfolds, what the photographer will ask you to do, when photos arrive — and why nobody needs to pose.",
    "target_keywords": "couples photoshoot what to expect, couples photoshoot italy, vacation couple photos italy, how does a couples photoshoot work",
    "excerpt": "The first ten minutes are stiff for everyone. Then you walk, someone laughs for real, and the camera disappears — the actual script of a couples hour.",
    "content": "## Neither of you needs to know how to pose\n\nThe most common worry before a couples shoot is not about locations or light — it is \"we don't know what to do in front of a camera\". The honest answer: you don't need to. A good couples session is not a sequence of poses. It is a walk, directed by someone who knows where to put you and what to ask — and the photographs happen along the way.\n\n## Minute by minute\n\n**0–10: the stiff minutes.** They are stiff for everyone, every time. Your photographer knows it and spends them on the easy things: walking hand in hand, talking, looking at the view. These first frames are rarely the best — their job is to make you forget the lens.\n\n**10–25: movement.** You walk towards the camera, one of you spins the other, somebody says something silly and the laugh is real. The directions are simple and physical — \"lean into his shoulder\", \"watch her walk ahead\" — never \"act natural\", which is the least natural instruction in the world.\n\n**25–45: the best spot, in the best light.** By now you are warm, and the photographer takes you to the point the whole route was built around — the belvedere, the lane, the riverside — at the hour the light deserves it. This is where the wall-print photos come from.\n\n**45–60: details and play.** Hands, rings, a half-danced turn, gelato bought on the go. The last photos are the loosest, and often the favourites.\n\n## What decides the result (and it isn't how photogenic you are)\n\n- **The hour.** Golden hour — after sunrise or before sunset — forgives everything; a summer noon forgives nothing. If your photographer suggests 6:30am, there is a reason.\n- **Shoes.** Cobblestones, climbs, stairs: walk in comfort, change for the frame.\n- **Two outfits at most.** One dressed up, one relaxed. Changes eat minutes of light.\n- **Say it if there's an angle you hate.** A photographer can work around any insecurity — but only one they know about.\n\n## Afterwards\n\nA preview of 5–10 frames often lands within 48 hours; the full gallery — typically 40–60+ photos for an hour — within one to three weeks, each edited individually. The files are yours in full resolution, to print and share freely.\n\n## Where to do it\n\nThe couples hour works anywhere, but three combinations never miss: Rome at dawn for an empty centre, Florence at golden hour for the river and bridges, the Amalfi Coast at sunset for the cliffs. The [couples photoshoot page](/photoshoots/couples) lists photographers and packages; for picking the city there are the [Rome](/locations/rome) and [Florence](/locations/florence) guides.\n"
  },
  {
    "slug": "dove-sposarsi-in-due-in-italia-sette-scenari",
    "locale": "it",
    "category": "elopements",
    "published_at": "2026-07-27T09:00:00Z",
    "title": "Dove sposarsi in due in Italia: sette scenari a confronto",
    "meta_title": "Dove sposarsi in due in Italia: sette scenari",
    "meta_description": "Toscana, Costiera, laghi, Sicilia, Puglia, Roma o le Dolomiti? Sette scenari per un elopement in Italia, con stagioni, logistica e che foto ne escono.",
    "target_keywords": "elopement italia dove, sposarsi in due in italia, matrimonio intimo italia dove farlo, elopement toscana o costiera",
    "excerpt": "Un elopement compra libertà: nessuna sala da riempire, solo il posto giusto. Sette scenari italiani a confronto, con la stagione giusta per ciascuno.",
    "content": "## La domanda non è \"dove è più bello\"\n\nÈ tutta bella, e questo non aiuta a scegliere. Le domande utili sono altre: che paesaggio volete nelle foto tra vent'anni, in che stagione viaggiate, e quanta logistica siete disposti a sopportare in un giorno che avete scelto proprio per non averne.\n\n## I sette scenari\n\n**1. Val d'Orcia, Toscana.** Colline, cipressi, una cappella su un crinale. È il paesaggio che il mondo intende quando dice \"Italia\", e all'alba con la nebbia nelle valli non somiglia a nient'altro. Meglio maggio (verde e papaveri) o fine settembre (oro). Le promesse in una tenuta tra le vigne risolvono anche il ricevimento: si cena dove ci si è sposati.\n\n**2. Costiera Amalfitana.** Le terrazze di Ravello a strapiombo, i vicoli verticali di Positano. Le foto hanno il mare dentro a ogni inquadratura. Il prezzo è la logistica: strade strette, transfer lenti, luglio e agosto affollati. Aprile-giugno e settembre-ottobre sono la finestra giusta.\n\n**3. Lago di Como.** Ville, giardini a lago, montagne nell'acqua. È lo scenario più \"cinematografico\" e il più fotografato in barca: le promesse su un motoscafo di legno sono un classico che funziona davvero. Ottimo da maggio a ottobre.\n\n**4. Roma.** L'elopement urbano: un cortile storico, una terrazza, il Centro all'alba per i ritratti. Funziona tutto l'anno — dicembre compreso — e non richiede transfer: si fa tutto a piedi. La scelta di chi vuole la città eterna e zero complicazioni.\n\n**5. Sicilia — Taormina e Siracusa.** Il teatro greco con l'Etna dietro, il barocco color miele di Ortigia sul mare. Stagione lunghissima: a novembre si sta in maniche corte. È il sud più scenografico, con i voli in più che comporta.\n\n**6. Puglia — Alberobello e la campagna.** Trulli bianchi, masserie, ulivi secolari. Lo scenario più rustico ed economico della lista, perfetto per chi vuole un elopement contadino-chic con cena in masseria.\n\n**7. Dolomiti.** Per chi vuole le foto che nessun altro ha: prati alti, pareti rosa al tramonto (l'enrosadira), laghi verdi. Stagione corta — da metà giugno a settembre — e serve camminare. Le promesse a 2.000 metri non si dimenticano.\n\n## Simbolico o legale?\n\nLa cerimonia simbolica si fa ovunque, senza permessi nella maggior parte dei luoghi pubblici. Quella legale passa dall'Ufficio di Stato Civile, con documenti tradotti e 2-4 settimane di pratica — e per gli stranieri conviene un wedding planner locale che la gestisca. Molte coppie fanno il legale a casa e le promesse in Italia: nessuno, nelle foto, vede la differenza.\n\n## Quanto coprire con il fotografo\n\nPer un elopement vero — voi due, forse una manciata di persone — bastano 2-4 ore: preparazione, cerimonia, ritratti, brindisi. La [pagina elopement](/photoshoots/elopement) spiega i pacchetti; se il progetto cresce fino a trenta invitati, guardate piuttosto la [fotografia di matrimonio](/weddings).\n"
  },
  {
    "slug": "where-to-elope-in-italy-seven-settings-compared",
    "locale": "en",
    "category": "elopements",
    "published_at": "2026-07-27T09:00:00Z",
    "title": "Where to Elope in Italy: Seven Settings, Honestly Compared",
    "meta_title": "Where to Elope in Italy: Seven Settings Compared",
    "meta_description": "Tuscany, the Amalfi Coast, the lakes, Sicily, Puglia, Rome or the Dolomites? Seven Italian elopement settings compared — seasons, logistics and the photos you get.",
    "target_keywords": "where to elope in italy, elope in tuscany or amalfi, italy elopement locations, small wedding italy where",
    "excerpt": "An elopement buys you freedom: no hall to fill, just the right place. Seven Italian settings compared, with the season that suits each one.",
    "content": "## The question is not \"which is most beautiful\"\n\nAll of it is beautiful, which is exactly why that question doesn't help. The useful questions are different: what landscape do you want in the photographs twenty years from now, what season are you travelling in, and how much logistics are you willing to absorb on a day you chose precisely to avoid it.\n\n## The seven settings\n\n**1. Val d'Orcia, Tuscany.** Rolling hills, cypress avenues, a chapel on a ridge. This is the landscape the world means when it says \"Italy\", and at dawn with mist in the valleys it looks like nowhere else. Best in May (green, poppies) or late September (gold). Vows at a wine estate solve the reception too — you dine where you married.\n\n**2. The Amalfi Coast.** Ravello's clifftop terraces, Positano's vertical lanes. The sea ends up inside every frame. The price is logistics: narrow roads, slow transfers, packed July and August. April–June and September–October are the window.\n\n**3. Lake Como.** Villas, lakeside gardens, mountains standing in the water. The most cinematic setting of the list, and the one best photographed from a boat — vows on a wooden motoscafo are a cliché that genuinely works. Good May to October.\n\n**4. Rome.** The urban elopement: a historic courtyard, a rooftop terrace, the centro at dawn for portraits. It works year-round — December included — and needs no transfers: everything happens on foot. The choice for couples who want the Eternal City and zero moving parts.\n\n**5. Sicily — Taormina and Syracuse.** The Greek theatre with Etna behind it; Ortigia's honey-coloured baroque on the sea. The longest season of all — short sleeves in November. The most scenic south, with the extra flights that implies.\n\n**6. Puglia — Alberobello and the countryside.** Whitewashed trulli, masserie, ancient olive groves. The most rustic and most affordable setting on the list, made for a farmhouse-chic elopement with dinner at the masseria.\n\n**7. The Dolomites.** For couples who want photographs nobody else has: high meadows, rock walls turning pink at sunset, green lakes. A short season — mid-June to September — and some walking required. Vows at 2,000 metres are not forgotten.\n\n## Symbolic or legal?\n\nA symbolic ceremony can happen anywhere, permit-free in most public places. A legal one goes through the civil registry (Ufficio di Stato Civile) with translated documents and 2–4 weeks of paperwork — for foreigners, a local planner who handles it is worth the fee. Many couples do the legal part at home and the vows in Italy: in the photographs, nobody can tell.\n\n## How much coverage you need\n\nFor a true elopement — the two of you, maybe a handful of people — 2–4 hours covers it: preparation, ceremony, portraits, a toast. The [elopement page](/photoshoots/elopement) explains the packages; if the plan grows to thirty guests, look at [wedding photography](/weddings) instead.\n"
  },
  {
    "slug": "servizio-di-famiglia-a-roma-con-i-bambini",
    "locale": "it",
    "category": "family",
    "published_at": "2026-07-24T09:00:00Z",
    "title": "Servizio fotografico di famiglia a Roma con i bambini: dove e a che ora",
    "meta_title": "Servizio di famiglia a Roma con bambini: la guida",
    "meta_description": "Villa Borghese per correre, Trastevere per il gelato, l'Aventino per la calma: dove funziona un servizio di famiglia a Roma con i bambini, e a che ora farlo.",
    "target_keywords": "servizio fotografico famiglia roma, foto famiglia roma bambini, villa borghese foto famiglia, servizio famiglia con bambini piccoli",
    "excerpt": "Un bambino di quattro anni non vi deve un'ora di posa. A Roma il servizio di famiglia funziona dove può correre — e la mattina, non al tramonto.",
    "content": "## La regola: il percorso lo detta il più piccolo\n\nUn servizio di famiglia a Roma fallisce per un solo motivo: un itinerario pensato per adulti. Salite, code, \"non toccare\", orari da tramonto quando la stanchezza è al massimo. Il programma giusto parte dall'età del più piccolo e costruisce tutto il resto intorno.\n\n## I posti che funzionano\n\n**Villa Borghese.** Il valore sicuro. Viali larghi e piani (passeggino: nessun problema), ombra vera dei pini a mezzogiorno, il laghetto con le barche a remi, un muretto che i bambini scalano senza che nessuno glielo chieda. Le foto migliori succedono mentre giocano: il fotografo osserva e reagisce, non mette in posa. Ingresso in piano da Porta Pinciana; la rampa dal Pincio è la salita panoramica per chi non spinge un passeggino.\n\n**Trastevere di mattina presto.** Vicoli d'ocra, panni stesi, e il trucco che salva tutto: il gelato (o un maritozzo) come tappa concordata. Un bambino che cammina verso la gelateria è un bambino felice in foto. Dopo le dieci i tavolini escono e i vicoli si stringono: la finestra è 8:30-10:00.\n\n**Il Giardino degli Aranci.** Piccolo, chiuso, tranquillo: i genitori si rilassano perché nessuno può correre in strada, e il belvedere regala la foto di famiglia con Roma sotto. Abbinabile al roseto (maggio-giugno) due minuti più in là.\n\n**Piazza del Popolo + Pincio.** La piazza è enorme e chiusa al traffico — spazio per correre con i monumenti dietro — e la terrazza sopra dà il panorama senza camminate lunghe.\n\n**Il Colosseo, ma da fuori e presto.** Con bambini si lavora dall'esterno: via dei Fori Imperiali all'alba o la terrazza sopra la metro. Dentro, code e divieti; fuori, scala e libertà.\n\n## L'orario giusto (non è il tramonto)\n\nPer gli adulti l'ora dorata serale è regina. Con bambini sotto i sei anni vale il contrario: la mattina — 8:00-10:30 — hanno l'energia buona, la luce è ancora morbida e i luoghi sono vuoti. Un servizio alle 19 con un bimbo di tre anni è una scommessa contro il sonno, e il sonno vince.\n\n## Come prepararli (poco)\n\n- **Non annunciate \"le foto\".** Annunciate un'avventura: il parco, il gelato, le barche. La fotocamera è un dettaglio.\n- **Snack e acqua** in borsa, sempre. Metà dei capricci è fame.\n- **Vestiti in cui possono muoversi**, palette coordinata senza esagerare — i toni terra e i pastelli reggono bene sull'ocra romana.\n- **45 minuti utili**, non 90. Sotto i cinque anni il limite è la pazienza, e i pacchetti da un'ora bastano.\n\n## Cosa aspettarsi dal risultato\n\nUn buon servizio di famiglia a Roma consegna tre famiglie di foto: quelle d'insieme al belvedere, quelle di gioco (le più vere), e i dettagli — manine, gelato, la corsa. La [pagina dei servizi famiglia](/photoshoots/family) elenca i fotografi che con i bambini ci sanno fare; la [guida di Roma](/locations/rome) copre orari e luce di ogni zona.\n"
  },
  {
    "slug": "family-photoshoot-in-rome-with-kids",
    "locale": "en",
    "category": "family",
    "published_at": "2026-07-24T09:00:00Z",
    "title": "A Family Photoshoot in Rome With Kids: Where It Works, and When",
    "meta_title": "Family Photoshoot in Rome With Kids: the Guide",
    "meta_description": "Villa Borghese for running, Trastevere for gelato, the Aventine for calm — where a family photoshoot in Rome actually works with children, and why mornings win.",
    "target_keywords": "family photoshoot rome, rome family photos with kids, villa borghese family photoshoot, family photographer rome",
    "excerpt": "A four-year-old doesn't owe you an hour of posing. In Rome, family shoots work where kids can run — and in the morning, not at sunset.",
    "content": "## The rule: the youngest sets the route\n\nA family photoshoot in Rome fails for exactly one reason: an itinerary designed for adults. Climbs, queues, \"don't touch\", a sunset slot when tiredness peaks. The right plan starts from the age of your youngest and builds everything else around it.\n\n## The places that work\n\n**Villa Borghese.** The safe bet. Wide, flat gravel avenues (prams: a non-issue), real pine shade at midday, the boating lake, and a low wall children climb unprompted. The best photos happen while they play — the photographer observes and reacts rather than posing anyone. Level entry from Porta Pinciana; the ramp up from the Pincio is the scenic climb for families without a pram.\n\n**Trastevere, early.** Ochre lanes, washing lines, and the trick that saves the session: gelato (or a maritozzo) as an agreed stop. A child walking towards a gelateria is a happy child in photographs. After ten the café tables come out and the lanes tighten — the window is 8:30–10:00.\n\n**The Orange Garden.** Small, enclosed, calm: parents relax because nobody can run into a road, and the belvedere gives you the family shot with Rome below. Pair it with the rose garden (May–June) two minutes down the hill.\n\n**Piazza del Popolo + the Pincio.** The square is huge and traffic-free — room to run with monuments behind — and the terrace above delivers the panorama without a long walk.\n\n**The Colosseum — from outside, early.** With children you work the exterior: Via dei Fori Imperiali at dawn, or the terrace above the metro exit. Inside means queues and rules; outside means scale and freedom.\n\n## The right hour (it isn't sunset)\n\nFor adults, evening golden hour is king. With children under six the opposite holds: in the morning — 8:00 to 10:30 — the energy is good, the light still soft, the places empty. A 7pm session with a three-year-old is a bet against sleep, and sleep wins.\n\n## How to prepare them (barely)\n\n- **Don't announce \"photos\".** Announce an adventure: the park, the gelato, the rowing boats. The camera is a detail.\n- **Snacks and water** in the bag, always. Half of all meltdowns are hunger.\n- **Clothes they can move in**, a loosely coordinated palette — earth tones and pastels hold up beautifully against Roman ochre.\n- **Forty-five useful minutes**, not ninety. Under five, the limit is patience — an hour's package is enough.\n\n## What the gallery looks like\n\nA good family session in Rome delivers three families of photos: the together-shots at a viewpoint, the play shots (the truest ones), and the details — small hands, gelato, the run. The [family photoshoot page](/photoshoots/family) lists photographers who are genuinely good with kids; the [Rome guide](/locations/rome) covers light and timing area by area.\n"
  }
]
