// Package batch 2 — 25 more packages (Sophie, Rui, Jose Santos, Tatiana, Massimo, Denis, Maria)
import pg from "pg";
import { readFileSync } from "fs";
const env = Object.fromEntries(readFileSync("/var/www/photoportugal/.env","utf-8").split("\n").filter((l)=>l&&l.includes("=")&&!l.startsWith("#")).map((l)=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim().replace(/^["']|["']$/g,"")]}));
const client = new pg.Client({ connectionString: env.DATABASE_URL });
await client.connect();

const PKG = [
  // Sophie Bellmann
  { id: "f762ee5e-d24f-44a3-adfc-f8552971661e",
    name: { pt: "Sessão Fotográfica de Branding", de: "Branding-Fotoshooting", es: "Sesión fotográfica de branding", fr: "Séance photo branding" },
    description: { pt: "Para mulheres e criativos que querem explorar a sua identidade, presença e expressão emocional através de imagens poderosas.\n\nEsta experiência foca-se na autenticidade, conexão e auto-expressão num ambiente guiado e intuitivo.", de: "Für Frauen und Kreative, die ihre Identität, Präsenz und emotionale Ausdruckskraft durch starke Bilder erkunden möchten.\n\nDiese Erfahrung konzentriert sich auf Authentizität, Verbindung und Selbstausdruck in einer geführten, intuitiven Umgebung.", es: "Para mujeres y creativos que quieren explorar su identidad, presencia y expresión emocional a través de imágenes poderosas.\n\nEsta experiencia se centra en la autenticidad, la conexión y la autoexpresión en un entorno guiado e intuitivo.", fr: "Pour les femmes et les créatifs qui veulent explorer leur identité, leur présence et leur expression émotionnelle à travers des images fortes.\n\nCette expérience se concentre sur l'authenticité, la connexion et l'expression de soi dans un cadre guidé et intuitif." },
  },
  { id: "7dba07de-8d21-4deb-b7aa-ed57f2cfe315",
    name: { pt: "Experiência Foto & Surf", de: "Foto-&-Surf-Erlebnis", es: "Experiencia foto y surf", fr: "Expérience photo & surf" },
    description: { pt: "Uma combinação única de surf e narrativa visual. Esta experiência junta uma sessão de surf guiada e uma sessão fotográfica profissional. Vou captá-lo(a) tanto na água como na praia. A experiência é para iniciantes, intermédios e avançados. A sessão é sobre conexão com o mar, consigo e com o momento. Decorre na Costa da Caparica e é documentada de terra e da água com equipamento subaquático profissional.", de: "Eine einzigartige Kombination aus Surfen und Bildgeschichten. Diese Erfahrung verbindet eine geführte Surfsession mit einem professionellen Fotoshooting. Ich halte Sie sowohl im Wasser als auch am Strand fest. Geeignet für Anfänger, Fortgeschrittene und Profis. Es geht um Verbindung zum Meer, zu sich selbst und zum Moment. Die Session findet an der Costa da Caparica statt und wird mit professioneller Unterwasserausrüstung von Land und Wasser dokumentiert.", es: "Una combinación única de surf y narrativa visual. Esta experiencia une una sesión de surf guiada con una sesión fotográfica profesional. Le capto tanto en el agua como en la playa. Apta para principiantes, intermedios y avanzados. La sesión va sobre la conexión con el mar, consigo mismo(a) y con el momento. Tiene lugar en Costa da Caparica y se documenta desde tierra y agua con equipo subacuático profesional.", fr: "Une combinaison unique de surf et de récit visuel. Cette expérience associe une séance de surf encadrée à une séance photo professionnelle. Je vous capture aussi bien dans l'eau que sur la plage. Pour débutants, intermédiaires et avancés. La séance porte sur la connexion à la mer, à soi et à l'instant. Elle se déroule à la Costa da Caparica, documentée depuis la terre et l'eau avec un équipement aquatique professionnel." },
  },
  // Rui Veloso
  { id: "64020823-c9c9-4576-8c16-2d5ac973e117",
    name: { pt: "MOMENTOS", de: "MOMENTS", es: "MOMENTOS", fr: "MOMENTS" },
    description: { pt: "Uma sessão fotográfica descontraída e natural para captar o seu tempo em Lisboa, Sintra ou na costa.\nGuio-o(a) quando é preciso, mantendo tudo simples e genuíno — sem poses, apenas momentos reais.", de: "Eine entspannte, natürliche Fotosession, um Ihre Zeit in Lissabon, Sintra oder an der Küste festzuhalten.\nIch leite Sie, wenn nötig, halte aber alles einfach und ehrlich — kein Posieren, nur echte Momente.", es: "Una sesión fotográfica relajada y natural para captar su tiempo en Lisboa, Sintra o la costa.\nLe guío cuando hace falta, manteniendo todo sencillo y genuino — sin poses, solo momentos reales.", fr: "Une séance photo détendue et naturelle pour capturer votre séjour à Lisbonne, Sintra ou sur la côte.\nJe vous guide quand nécessaire, en gardant tout simple et sincère — pas de poses, juste des moments réels." },
  },
  { id: "7d6f8c10-2415-4e94-a236-e8854aa67601",
    name: { pt: "STORY", de: "STORY", es: "STORY", fr: "STORY" },
    description: { pt: "Uma experiência mais completa, com tempo extra, variedade e narrativa natural.\nPodemos explorar uma ou duas localizações mantendo a sessão descontraída e flexível.\nIdeal para casais, viajantes solo e famílias a visitar Portugal.", de: "Eine umfassendere Erfahrung mit mehr Zeit, Vielfalt und natürlichem Storytelling.\nWir können ein oder zwei Locations erkunden, während die Session entspannt und flexibel bleibt.\nIdeal für Paare, Solo-Reisende und Familien beim Portugal-Besuch.", es: "Una experiencia más completa, con tiempo extra, variedad y narrativa natural.\nPodemos explorar una o dos localizaciones manteniendo la sesión relajada y flexible.\nIdeal para parejas, viajeros solos y familias que visitan Portugal.", fr: "Une expérience plus complète, avec plus de temps, de variété et de narration naturelle.\nNous pouvons explorer un ou deux lieux tout en gardant la séance détendue et flexible.\nIdéal pour les couples, voyageurs solos et familles en visite au Portugal." },
  },
  { id: "4b56cce6-c0fc-4577-b4d7-314b98415444",
    name: { pt: "EXPERIENCE", de: "EXPERIENCE", es: "EXPERIENCE", fr: "EXPERIENCE" },
    description: { pt: "Uma experiência completa para explorar Lisboa e os arredores, criando uma galeria diversa e significativa.\nIdeal se quiser mais variedade, cenários diferentes e um ritmo descontraído.\nIdeal para casais, viajantes solo e famílias a visitar Portugal.", de: "Eine vollständige Erfahrung, um Lissabon und Umgebung zu erkunden und eine vielseitige, bedeutungsvolle Galerie zu schaffen.\nIdeal, wenn Sie mehr Vielfalt, unterschiedliche Kulissen und ein entspanntes Tempo möchten.\nIdeal für Paare, Solo-Reisende und Familien beim Portugal-Besuch.", es: "Una experiencia completa para explorar Lisboa y sus alrededores, creando una galería diversa y significativa.\nIdeal si quiere más variedad, escenarios diferentes y un ritmo relajado.\nIdeal para parejas, viajeros solos y familias que visitan Portugal.", fr: "Une expérience complète pour explorer Lisbonne et ses environs, en créant une galerie variée et porteuse de sens.\nIdéal si vous souhaitez plus de variété, des décors différents et un rythme détendu.\nIdéal pour les couples, voyageurs solos et familles en visite au Portugal." },
  },
  // Jose Santos
  { id: "3d2f02df-a1bb-47ee-b8f9-722eada57651",
    name: { pt: "Pedido de Casamento", de: "Heiratsantrag", es: "Pedida de mano", fr: "Demande en mariage" },
    description: { pt: "O pedido de casamento é um momento único que deve reflectir amor, emoção e a promessa de um futuro juntos. Estamos cá para ajudar a captar esse momento e a encontrar os melhores locais.\nConte connosco!", de: "Der Heiratsantrag ist ein einzigartiger Moment, der Liebe, Emotion und das Versprechen einer gemeinsamen Zukunft widerspiegeln sollte. Wir helfen Ihnen, diesen Moment einzufangen und die besten Orte dafür zu finden.\nVerlassen Sie sich auf uns!", es: "La pedida de mano es un momento único que debe reflejar amor, emoción y la promesa de un futuro juntos. Estamos aquí para ayudarle a capturar ese momento y encontrar los mejores lugares.\n¡Cuente con nosotros!", fr: "La demande en mariage est un moment unique qui doit refléter l'amour, l'émotion et la promesse d'un avenir partagé. Nous sommes là pour vous aider à capturer ce moment et à trouver les plus beaux lieux.\nComptez sur nous !" },
  },
  { id: "7aa26474-9eac-4d08-a856-c0f268a1d916",
    name: { pt: "Sessão Açoriana Dourada — Ilha de São Miguel", de: "Azorische Goldene Session — Insel São Miguel", es: "Sesión Azoreña Dorada — Isla de São Miguel", fr: "Séance Açorienne Dorée — Île de São Miguel" },
    description: { pt: "Sessão fotográfica num hotel ou na natureza. Na natureza, a sessão decorre em uma das seguintes localizações:\nLagoa das Sete Cidades;\nLagoa das Furnas (Vulcão das Furnas);\nPlantação de Chá Gorreana;\nLagoa de S. Brás;\nPraia de Santa Bárbara ou Monte Verde;\nCidade de Ponta Delgada ou outro local.", de: "Fotosession in einem Hotel oder in der Natur. In der Natur findet die Session an einem der folgenden Orte statt:\nLagoa das Sete Cidades;\nLagoa das Furnas (Furnas-Vulkan);\nGorreana-Teeplantage;\nLagoa de S. Brás;\nStrand Santa Bárbara oder Monte Verde;\nStadt Ponta Delgada oder ein anderer Ort.", es: "Sesión fotográfica en un hotel o en la naturaleza. En la naturaleza, la sesión se realiza en una de las siguientes localizaciones:\nLagoa das Sete Cidades;\nLagoa das Furnas (Volcán de Furnas);\nPlantación de té Gorreana;\nLagoa de S. Brás;\nPlaya de Santa Bárbara o Monte Verde;\nCiudad de Ponta Delgada u otra localización.", fr: "Séance photo en hôtel ou en pleine nature. En pleine nature, la séance se déroule dans l'un des lieux suivants :\nLagoa das Sete Cidades ;\nLagoa das Furnas (Volcan de Furnas) ;\nPlantation de thé Gorreana ;\nLagoa de S. Brás ;\nPlage de Santa Bárbara ou Monte Verde ;\nVille de Ponta Delgada ou un autre lieu." },
  },
  { id: "b94c98a5-ca74-42e9-8ab1-cab787cb6209",
    name: { pt: "Sessão Açoriana Prateada — Ilha de São Miguel", de: "Azorische Silberne Session — Insel São Miguel", es: "Sesión Azoreña Plateada — Isla de São Miguel", fr: "Séance Açorienne Argentée — Île de São Miguel" },
    description: { pt: "Sessão fotográfica num hotel ou na natureza. Na natureza, a sessão decorre em duas das seguintes localizações:\nLagoa das Sete Cidades;\nLagoa das Furnas (Vulcão das Furnas);\nPlantação de Chá Gorreana;\nLagoa de S. Brás;\nPraia de Santa Bárbara ou Monte Verde;\nCidade de Ponta Delgada ou outro local.", de: "Fotosession in einem Hotel oder in der Natur. In der Natur findet die Session an zwei der folgenden Orte statt:\nLagoa das Sete Cidades;\nLagoa das Furnas (Furnas-Vulkan);\nGorreana-Teeplantage;\nLagoa de S. Brás;\nStrand Santa Bárbara oder Monte Verde;\nStadt Ponta Delgada oder ein anderer Ort.", es: "Sesión fotográfica en un hotel o en la naturaleza. En la naturaleza, la sesión se realiza en dos de las siguientes localizaciones:\nLagoa das Sete Cidades;\nLagoa das Furnas (Volcán de Furnas);\nPlantación de té Gorreana;\nLagoa de S. Brás;\nPlaya de Santa Bárbara o Monte Verde;\nCiudad de Ponta Delgada u otra localización.", fr: "Séance photo en hôtel ou en pleine nature. En pleine nature, la séance se déroule dans deux des lieux suivants :\nLagoa das Sete Cidades ;\nLagoa das Furnas (Volcan de Furnas) ;\nPlantation de thé Gorreana ;\nLagoa de S. Brás ;\nPlage de Santa Bárbara ou Monte Verde ;\nVille de Ponta Delgada ou un autre lieu." },
  },
  { id: "73096ae9-bcfe-456a-bbf1-3e30dfec0b06",
    name: { pt: "Sessão na Rota do Vulcão dos Capelinhos — Ilha do Faial", de: "Fotosession auf der Capelinhos-Vulkanroute — Insel Faial", es: "Sesión en la Ruta del Volcán Capelinhos — Isla de Faial", fr: "Séance sur la route du volcan Capelinhos — Île de Faial" },
    description: { pt: "Sessão fotográfica na natureza ou num hotel. Na natureza, a sessão decorre em locais como: a cidade da Horta, a icónica marina da Horta, as areias vulcânicas do Vulcão dos Capelinhos e outros lugares onde a natureza realça a pureza das pessoas fotografadas.", de: "Fotosession in der Natur oder in einem Hotel. In der Natur findet die Session an Orten wie der Stadt Horta, dem ikonischen Hafen von Horta, den vulkanischen Sänden des Capelinhos-Vulkans und weiteren Plätzen statt, an denen die Natur die Reinheit der fotografierten Personen unterstreicht.", es: "Sesión fotográfica en la naturaleza o en un hotel. En la naturaleza, la sesión se realiza en lugares como: la ciudad de Horta, la icónica marina de Horta, las arenas volcánicas del Volcán Capelinhos y otros sitios donde la naturaleza realza la pureza de las personas fotografiadas.", fr: "Séance photo en pleine nature ou en hôtel. En nature, la séance se déroule dans des lieux comme la ville de Horta, sa marina emblématique, les sables volcaniques du volcan Capelinhos et d'autres endroits où la nature sublime la pureté des personnes photographiées." },
  },
  { id: "b14a61de-2f43-4cb4-bf26-ce06495c1e2b",
    name: { pt: "Sessão Açoriana Diamante", de: "Azorische Diamant-Session", es: "Sesión Azoreña Diamante", fr: "Séance Açorienne Diamant" },
    description: { pt: "Sessão fotográfica na natureza, hotel ou outro espaço, em locais a combinar na ilha de São Miguel e também numa das seguintes ilhas dos Açores: Santa Maria, Graciosa, S. Jorge, Pico e Flores.", de: "Fotosession in der Natur, in einem Hotel oder an einem anderen Ort — auf der Insel São Miguel und zusätzlich auf einer der folgenden Azoren-Inseln: Santa Maria, Graciosa, São Jorge, Pico oder Flores.", es: "Sesión fotográfica en la naturaleza, hotel u otro espacio, en lugares a acordar en la isla de São Miguel y también en una de las siguientes islas de las Azores: Santa María, Graciosa, S. Jorge, Pico o Flores.", fr: "Séance photo en pleine nature, en hôtel ou autre lieu — sur l'île de São Miguel et également sur l'une des îles suivantes des Açores : Santa Maria, Graciosa, São Jorge, Pico ou Flores." },
  },
  { id: "a35bdcd3-20b3-48ce-aa8e-fa2ea53f8fc9",
    name: { pt: "Queijo açoriano dourado — Ilha de São Jorge", de: "Goldener Azoren-Käse — Insel São Jorge", es: "Queso azoreño dorado — Isla de São Jorge", fr: "Fromage açorien doré — Île de São Jorge" },
    description: { pt: "Sessão fotográfica na ilha de São Jorge, com prova do famoso queijo São Jorge. A reportagem fotográfica na natureza decorre em Fajãs dos Vimes, Fajã do Ouvidor, Caldeira de Santo Cristo e Velas.", de: "Fotosession auf der Insel São Jorge, mit Verkostung des berühmten São-Jorge-Käses. Die Naturreportage findet in Fajãs dos Vimes, Fajã do Ouvidor, Caldeira de Santo Cristo und Velas statt.", es: "Sesión fotográfica en la isla de São Jorge, con cata del famoso queso São Jorge. El reportaje fotográfico en la naturaleza tiene lugar en Fajãs dos Vimes, Fajã do Ouvidor, Caldeira de Santo Cristo y Velas.", fr: "Séance photo sur l'île de São Jorge, avec dégustation du célèbre fromage São Jorge. Le reportage photo en pleine nature a lieu à Fajãs dos Vimes, Fajã do Ouvidor, Caldeira de Santo Cristo et Velas." },
  },
  { id: "e7847d8a-9d69-49b9-8b2f-383bd40aaf0f",
    name: { pt: "Sonhos do Corvo", de: "Corvo-Träume", es: "Sueños de Corvo", fr: "Rêves de Corvo" },
    description: { pt: "Sessão fotográfica na natureza ou num hotel. Na natureza, a sessão decorre em locais como: a vila do Corvo, a icónica Caldeira do Corvo e outros lugares onde a natureza realça a pureza das pessoas fotografadas.", de: "Fotosession in der Natur oder in einem Hotel. In der Natur findet die Session an Orten wie dem Dorf Corvo, der ikonischen Caldeira do Corvo und weiteren Plätzen statt, an denen die Natur die Reinheit der fotografierten Personen unterstreicht.", es: "Sesión fotográfica en la naturaleza o en un hotel. En la naturaleza, la sesión se realiza en lugares como: el pueblo de Corvo, la icónica Caldeira do Corvo y otros sitios donde la naturaleza realza la pureza de las personas fotografiadas.", fr: "Séance photo en pleine nature ou en hôtel. En nature, la séance se déroule dans des lieux comme le village de Corvo, l'emblématique Caldeira do Corvo et d'autres endroits où la nature sublime la pureté des personnes photographiées." },
  },
  { id: "4219ea06-b2ac-4099-9f0f-9d9662a2ab33",
    name: { pt: "Sonhos ao pôr-do-sol em Santa Maria", de: "Sonnenuntergangsträume in Santa Maria", es: "Sueños al atardecer en Santa María", fr: "Rêves au coucher du soleil à Santa Maria" },
    description: { pt: null, de: null, es: null, fr: null },
  },
  { id: "9148a6c3-c124-46b6-990d-3289bceca9a2",
    name: { pt: "Casamento nos Açores", de: "Hochzeit auf den Azoren", es: "Boda en las Azores", fr: "Mariage aux Açores" },
    description: { pt: "Reportagem fotográfica de casamento, incluindo 400 ficheiros digitais em alta resolução.\nA cobertura do casamento decorre desde o início da cerimónia até ao fim da recepção.", de: "Hochzeitsfotoreportage, inklusive 400 digitalen Dateien in hoher Auflösung.\nDie Hochzeitsabdeckung reicht vom Beginn der Zeremonie bis zum Ende des Empfangs.", es: "Reportaje fotográfico de boda, con 400 archivos digitales en alta resolución.\nLa cobertura de la boda va desde el inicio de la ceremonia hasta el final de la recepción.", fr: "Reportage photo de mariage avec 400 fichiers numériques haute résolution.\nLa couverture du mariage va du début de la cérémonie jusqu'à la fin de la réception." },
  },
  // Tatiana Ostrower
  { id: "b5f55f95-5d19-4a59-b30b-7423daff3a1a",
    name: { pt: "Sessão na Vila Histórica de Sintra — Lar de mistério, história e realeza", de: "Session in Sintras historischer Altstadt — Heimat von Mystik, Geschichte und Königtum", es: "Sesión en la Vila Histórica de Sintra — Hogar de misterio, historia y realeza", fr: "Séance dans le vieux Sintra — Berceau de mystère, d'histoire et de royauté" },
    description: { pt: "Encontre-me na estação de Sintra para uma sessão a passear pelos pequenos cantos e ruelas do centro histórico.\nFotografamos em locais como os jardins públicos do castelo, ruas antigas com 4 séculos, miradouros, árvores que guardam segredos das fadas. Vai levar para casa fotos naturais e candid.\nSintra é uma das vilas mais românticas e místicas de Portugal — e é a minha casa. Ideal para casais, viajantes solo e famílias.\nTraga sapatos confortáveis para caminhar. Vamos divertir-nos!", de: "Treffen Sie mich am Bahnhof Sintra für eine Spazier-Fotosession durch die kleinen Ecken und Gassen der historischen Altstadt.\nWir fotografieren an Orten wie den öffentlichen Schlossgärten, 400 Jahre alten Straßen, Aussichtspunkten und Bäumen, die Geheimnisse aus Feenzeiten bewahren. Sie bekommen natürliche, ungestellte Fotos.\nSintra ist eines der romantischsten und mystischsten Dörfer Portugals — und mein Zuhause. Ideal für Paare, Solo-Reisende und Familien.\nBringen Sie bequeme Schuhe zum Laufen mit. Lassen Sie uns Spaß haben!", es: "Encuéntreme en la estación de Sintra para una sesión a pie por los pequeños rincones y callejones del centro histórico.\nFotografiamos en lugares como los jardines públicos del castillo, calles antiguas de 4 siglos, miradores y árboles que guardan secretos de los tiempos de las hadas. Se llevará a casa fotos naturales y candid.\nSintra es uno de los pueblos más románticos y místicos de Portugal — y es mi hogar. Ideal para parejas, viajeros solos y familias.\nLleve calzado cómodo para caminar. ¡Vamos a divertirnos!", fr: "Retrouvez-moi à la gare de Sintra pour une séance en marchant dans les petits coins et ruelles du centre historique.\nNous photographions dans des lieux comme les jardins publics du château, des rues vieilles de 4 siècles, des points de vue, des arbres qui gardent des secrets de l'époque des fées. Vous repartirez avec des photos naturelles et spontanées.\nSintra est l'un des villages les plus romantiques et mystiques du Portugal — et c'est chez moi. Idéal pour les couples, voyageurs solos et familles.\nApportez des chaussures confortables pour marcher. Amusons-nous !" },
  },
  { id: "9de3a61a-5a74-4832-852c-9f6efe4a4284",
    name: { pt: "Sessão fotográfica no centro da cidade", de: "Fotosession im Stadtzentrum", es: "Sesión fotográfica en el centro", fr: "Séance photo dans le centre" },
    description: { pt: "Escolha uma cidade entre Lisboa, Cascais ou Sintra para a sua sessão em pontos clássicos do centro!\nPodemos ir a monumentos e locais turísticos, ou a parques, pequenos bairros e miradouros.\nPosso sugerir uma localização baseada nas suas expectativas e preferências.\nUma sessão para viajantes solo, casais ou grupos que queiram levar uma memória querida e adorariam ser fotografados num cenário icónico e típico de Lisboa.\nFotos documentais com edição natural.", de: "Wählen Sie zwischen Lissabon, Cascais oder Sintra für Ihre Session an klassischen Orten im Zentrum!\nWir können Sehenswürdigkeiten und Touristenpunkte besuchen oder Parks, kleine Viertel und Aussichtspunkte.\nIch schlage eine Location basierend auf Ihren Erwartungen und Vorlieben vor.\nEine Session für Solo-Reisende, Paare oder Gruppen, die eine schöne Erinnerung mit nach Hause nehmen möchten, in einem ikonischen, typischen Lissabon-Setting.\nDokumentarische Fotos mit natürlicher Bearbeitung.", es: "¡Elija una ciudad entre Lisboa, Cascais o Sintra para su sesión en puntos clásicos del centro!\nPodemos ir a monumentos y lugares turísticos, o a parques, pequeños barrios y miradores.\nLe sugiero una ubicación según sus expectativas y preferencias.\nUna sesión para viajeros solos, parejas o grupos que quieran llevarse un recuerdo bonito y disfrutar siendo fotografiados en un escenario icónico y típico de Lisboa.\nFotos documentales con edición natural.", fr: "Choisissez une ville entre Lisbonne, Cascais ou Sintra pour votre séance dans les lieux classiques du centre !\nNous pouvons aller voir des monuments et sites touristiques, ou des parcs, petits quartiers et points de vue.\nJe peux suggérer un lieu selon vos attentes et préférences.\nUne séance pour voyageurs solos, couples ou groupes qui veulent rapporter un beau souvenir et adorent être photographiés dans un décor emblématique de Lisbonne.\nPhotos documentaires avec retouche naturelle." },
  },
  { id: "4e7fe3c0-c7a7-4b0b-8f5d-b9e38c9e1a28",
    name: { pt: "O Seu Pedido em Portugal", de: "Ihr Heiratsantrag in Portugal", es: "Su pedida en Portugal", fr: "Votre demande au Portugal" },
    description: { pt: "Uma sessão emocional e surpresa de pedido, captando este momento único da sua vida.\nPode ser um pedido de casamento, renovação de votos, um \"vamos viver juntos\" — sejamos criativos!\nPodemos ir a um local especial que combine com o seu gosto e estilo.\nProgredimos como uma sessão normal de casal até ao momento da surpresa e do pedido.\nAberto a casais de todos os tipos e idades.", de: "Eine emotionale Überraschungs-Antrags-Session, die diesen einzigartigen Lebensmoment einfängt.\nEs kann ein Heiratsantrag, eine Erneuerung der Eheversprechen, ein „Lass uns zusammenziehen\" sein — seien wir kreativ!\nWir können einen besonderen Ort wählen, der Ihrem Geschmack und Stil entspricht.\nWir starten wie eine normale Paar-Session, bis zum Moment der Überraschung und des Antrags.\nOffen für alle Arten von Paaren und alle Altersgruppen.", es: "Una sesión emocional y sorpresa de pedida, capturando este momento único de su vida.\nPuede ser una pedida de mano, una renovación de votos, un \"vente a vivir conmigo\" — ¡seamos creativos!\nPodemos ir a un lugar especial que combine con su gusto y estilo.\nAvanzamos como una sesión normal de pareja hasta el momento de la sorpresa y la pedida.\nAbierto a todo tipo de parejas y edades.", fr: "Une séance émotion et surprise pour la demande, capturant ce moment unique de votre vie.\nÇa peut être une demande en mariage, un renouvellement de vœux, un « viens vivre avec moi » — soyons créatifs !\nNous pouvons aller dans un lieu spécial qui correspond à votre goût et style.\nNous avançons comme une séance couple classique jusqu'au moment de la surprise et de la demande.\nOuvert à tous les couples, de tous âges." },
  },
  { id: "fdf8f2fa-4f92-41e8-b85d-3b4ec4dc2d15",
    name: { pt: "Sessão alargada no seu bairro favorito — Lisboa, Cascais, Sintra", de: "Erweiterte Session in Ihrem Lieblingsviertel — Lissabon, Cascais, Sintra", es: "Sesión ampliada en su barrio favorito — Lisboa, Cascais, Sintra", fr: "Séance prolongée dans votre quartier préféré — Lisbonne, Cascais, Sintra" },
    description: { pt: "Vamos passear no bairro à sua escolha e captar fotos icónicas e naturais em diferentes pontos das ruas, ruelas e praças.\nEscolha uma zona como: Alfama, Bairro Alto, Príncipe Real, Estrela, Alcântara, Belém, Avenida da Liberdade em Lisboa; centro de Cascais; ou centro histórico de Sintra para um phototour por vários pontos de interesse. Enquanto caminhamos, capto fotos espontâneas suas e da sua companhia. Uma sessão com mais tempo, focada em descobrir segredos e lugares especiais.", de: "Wir spazieren durch das Viertel Ihrer Wahl und halten ikonische, natürliche Fotos an verschiedenen Punkten der Straßen, Gassen und Plätze fest.\nWählen Sie ein Viertel wie Alfama, Bairro Alto, Príncipe Real, Estrela, Alcântara, Belém, Avenida da Liberdade in Lissabon; Stadtzentrum von Cascais; oder die historische Altstadt Sintras für eine Foto-Tour zu mehreren Sehenswürdigkeiten. Während wir laufen, halte ich spontane Aufnahmen von Ihnen und Ihrer Begleitung fest. Eine Session mit mehr Zeit, fokussiert darauf, Geheimnisse und besondere Orte zu entdecken.", es: "Pasearemos por el barrio que elija y captaremos fotos icónicas y naturales en distintos puntos de calles, callejones y plazas.\nElija una zona como: Alfama, Bairro Alto, Príncipe Real, Estrela, Alcântara, Belém, Avenida da Liberdade en Lisboa; centro de Cascais; o centro histórico de Sintra para un phototour por varios puntos de interés. Mientras caminamos, hago fotos espontáneas de usted y su compañía. Una sesión con más tiempo, centrada en descubrir secretos y lugares especiales.", fr: "Nous parcourons le quartier de votre choix pour capter des photos emblématiques et naturelles dans différents points : rues, ruelles, places.\nChoisissez un quartier comme Alfama, Bairro Alto, Príncipe Real, Estrela, Alcântara, Belém, Avenida da Liberdade à Lisbonne ; centre de Cascais ; ou le vieux Sintra pour un photo-tour à travers plusieurs points d'intérêt. Pendant la marche, je prends des photos spontanées de vous et de votre compagnie. Une séance plus longue, centrée sur la découverte de secrets et de lieux spéciaux." },
  },
  { id: "af093c42-9f83-46b6-9484-9e2020d23be0",
    name: { pt: "O seu evento em Portugal", de: "Ihr Event in Portugal", es: "Su evento en Portugal", fr: "Votre événement au Portugal" },
    description: { pt: "Vai ter um evento familiar ou corporativo? Um encontro ou reunião? Quer registar tudo num estilo natural? Pode contar comigo para o trabalho.", de: "Sie haben ein Familien- oder Firmenevent? Ein Treffen oder eine Versammlung? Möchten Sie alles in einem natürlichen Stil festhalten? Verlassen Sie sich auf mich für den Job.", es: "¿Tendrá un evento familiar o corporativo? ¿Una reunión o encuentro? ¿Quiere registrarlo todo en estilo natural? Puede contar conmigo para el trabajo.", fr: "Un événement familial ou d'entreprise ? Une réunion ou un rassemblement ? Vous voulez tout enregistrer dans un style naturel ? Vous pouvez compter sur moi pour la mission." },
  },
  // Massimo Pardini
  { id: "8e40ea0e-d082-4af3-bdfc-9f83656bdb21",
    name: { pt: "Hora dourada — Pacote básico", de: "Goldene Stunde — Basis-Paket", es: "Hora dorada — Pack básico", fr: "Heure dorée — Pack basique" },
    description: { pt: null, de: null, es: null, fr: null },
  },
  { id: "74fc6cef-c326-4de8-ba6c-7186525ac7de",
    name: { pt: "Escapada ao Pôr-do-Sol", de: "Sonnenuntergangs-Auszeit", es: "Escapada al atardecer", fr: "Échappée coucher de soleil" },
    description: { pt: null, de: null, es: null, fr: null },
  },
  { id: "890bc49f-67f1-45cd-bb76-c9dedfe4a40a",
    name: { pt: "Memórias para sempre — grandes famílias / grupos / noivado com cuidado extra", de: "Bleibende Erinnerungen — Großfamilien / Gruppen / Verlobung mit Extra-Sorgfalt", es: "Recuerdos eternos — familias grandes / grupos / compromiso con cuidado extra", fr: "Souvenirs éternels — grandes familles / groupes / fiançailles avec soin particulier" },
    description: { pt: "60 imagens digitais editadas em alta resolução em formato JPEG\n\n2 localizações\n\nVários outfits, se necessário\n\nFicheiros digitais incluídos, galeria online com 180+ imagens à escolha. Ideal para:\n\nGrandes grupos de 6+ pessoas\n\nLeve toda a galeria por um pequeno extra.", de: "60 bearbeitete digitale Bilder in hoher Auflösung im JPEG-Format\n\n2 Locations\n\nMehrere Outfits bei Bedarf\n\nDigitale Dateien inklusive, Online-Galerie mit 180+ Bildern zur Auswahl. Perfekt für:\n\nGroße Gruppen ab 6 Personen\n\nGesamte Galerie gegen kleinen Aufpreis.", es: "60 imágenes digitales editadas en alta resolución en formato JPEG\n\n2 localizaciones\n\nVarios outfits si es necesario\n\nArchivos digitales incluidos, galería online con más de 180 imágenes a elegir. Ideal para:\n\nGrupos grandes de 6+ personas\n\nLlévese el resto de la galería por un pequeño extra.", fr: "60 images numériques retouchées en haute résolution au format JPEG\n\n2 lieux\n\nPlusieurs tenues si nécessaire\n\nFichiers numériques inclus, galerie en ligne avec 180+ images à choisir. Parfait pour :\n\nGrands groupes de 6+ personnes\n\nObtenez le reste de la galerie pour un petit supplément." },
  },
  // Denis Erroyaux
  { id: "aa8dd22c-fb82-467b-8f71-b62f340ff403",
    name: { pt: "Sessão de Família", de: "Familien-Session", es: "Sesión de Familia", fr: "Séance Famille" },
    description: { pt: "Vamos passear por alguns dos pontos mais fotogénicos de Lisboa e captar imagens bonitas juntos. Não se preocupe se não é profissional — vou garantir que se sente confortável e à vontade em cada passo do caminho.", de: "Wir schlendern durch einige der fotogensten Orte Lissabons und halten gemeinsam schöne Bilder fest. Keine Sorge, wenn Sie kein Profi sind — ich sorge dafür, dass Sie sich auf dem ganzen Weg wohl und entspannt fühlen.", es: "Pasearemos por algunos de los puntos más fotogénicos de Lisboa y captaremos imágenes bonitas juntos. No se preocupe si no es profesional — me aseguro de que se sienta cómodo(a) y a gusto en cada paso del camino.", fr: "Nous flânerons dans quelques-uns des endroits les plus photogéniques de Lisbonne et capturerons de belles images ensemble. Ne vous inquiétez pas si vous n'êtes pas professionnel(le) — je veillerai à ce que vous vous sentiez à l'aise à chaque étape." },
  },
  { id: "6bf31e9f-624a-407a-bb5d-7406ed497a3e",
    name: { pt: "Amigos de férias", de: "Freunde im Urlaub", es: "Amigos de vacaciones", fr: "Amis en vacances" },
    description: { pt: "Um fim-de-semana de reunião, uma despedida de solteiro, um encontro de família no estrangeiro — seja qual for o motivo, juntar quem se gosta ao sol é sempre especial. E voltar para casa com fotos inesquecíveis? Ainda melhor.", de: "Ein Wiedersehens-Wochenende, ein Junggesellenabschied, ein Familientreffen im Ausland — egal aus welchem Anlass, mit den Liebsten in der Sonne zusammenzukommen ist immer besonders. Und mit unvergesslichen Fotos nach Hause kommen? Macht es noch besser.", es: "Un fin de semana de reencuentro, una despedida de soltero(a), una reunión familiar en el extranjero — sea cual sea el motivo, juntarse con los suyos al sol siempre es especial. ¿Y volver a casa con fotos inolvidables? Aún mejor.", fr: "Un week-end retrouvailles, un enterrement de vie de garçon/fille, un rassemblement familial à l'étranger — quelle que soit l'occasion, retrouver vos proches au soleil est toujours spécial. Et rentrer chez vous avec des photos inoubliables ? Encore mieux." },
  },
  // Maria Malko
  { id: "1e6295bc-4917-4458-8ae4-e9a828acc1ed",
    name: { pt: "« Experiência Lisboa »", de: "«Lisbon Experience»", es: "«Lisbon Experience»", fr: "« Expérience Lisbonne »" },
    description: { pt: "Um encontro consigo mesmo(a) na capital mais soalheira da Europa. Telhados cor de laranja, o azul infinito do Tejo, a cidade e você. Juntos vamos explorar os cantos escondidos de Alfama e captar momentos icónicos com o lendário eléctrico de Lisboa — os seus postais pessoais de Portugal.", de: "Ein Date mit sich selbst in Europas sonnigster Hauptstadt. Orange Dächer, das endlose Blau des Tejo, die Stadt und Sie. Gemeinsam erkunden wir die versteckten Ecken Alfamas und halten ikonische Momente mit der legendären Lissabonner Tram fest — Ihre persönlichen Postkarten aus Portugal.", es: "Una cita consigo mismo(a) en la capital más soleada de Europa. Tejados anaranjados, el azul infinito del Tajo, la ciudad y usted. Juntos exploraremos los rincones ocultos de Alfama y captaremos momentos icónicos con el legendario tranvía de Lisboa — sus postales personales de Portugal.", fr: "Un rendez-vous avec vous-même dans la capitale la plus ensoleillée d'Europe. Toits orangés, bleu infini du Tage, la ville et vous. Ensemble, nous explorerons les coins cachés d'Alfama et capterons des moments emblématiques avec le légendaire tramway de Lisbonne — vos cartes postales personnelles du Portugal." },
  },
];

for (const p of PKG) {
  const cols = []; const params = [];
  for (const loc of ["pt","de","es","fr"]) {
    if (p.name?.[loc]) { cols.push(`name_${loc} = $${params.length+1}`); params.push(p.name[loc]); }
    if (p.description?.[loc]) { cols.push(`description_${loc} = $${params.length+1}`); params.push(p.description[loc]); }
  }
  if (cols.length === 0) {
    // Empty package — still mark dirty=false
    await client.query(`UPDATE packages SET translations_dirty = FALSE, translations_updated_at = NOW() WHERE id = $1`, [p.id]);
    console.log(`✓ ${p.id.slice(0,8)} (empty/skipped)`);
    continue;
  }
  cols.push(`translations_updated_at = NOW()`, `translations_dirty = FALSE`);
  params.push(p.id);
  await client.query(`UPDATE packages SET ${cols.join(", ")} WHERE id = $${params.length}`, params);
  console.log(`✓ ${p.id.slice(0,8)} ${p.name.fr || ""}`);
}
await client.end();
console.log(`\nBatch pkg-2 done — ${PKG.length} packages translated.`);
