// Package batch 1 — first 20 packages (Vika, Ricardo, Chris, Isa, Sophie)
import pg from "pg";
import { readFileSync } from "fs";
const env = Object.fromEntries(readFileSync("/var/www/photoportugal/.env","utf-8").split("\n").filter((l)=>l&&l.includes("=")&&!l.startsWith("#")).map((l)=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim().replace(/^["']|["']$/g,"")]}));
const client = new pg.Client({ connectionString: env.DATABASE_URL });
await client.connect();

const PKG = [
  // Vika Emerson
  { id: "3727818f-3b93-4960-acd0-9208a0a6cb2b",
    name: { pt: "Mini sessão solo rápida", de: "Schnelle Solo-Mini-Session", es: "Mini sesión solo rápida", fr: "Mini séance solo express" },
    description: { pt: "Mini sessão rápida no centro de Lisboa; recebe ~50 fotografias com a minha edição e cores.", de: "Schnelles Mini-Shooting im Zentrum von Lissabon; Sie erhalten ca. 50 Fotos mit meiner Bearbeitung und Farben.", es: "Mini sesión rápida en el centro de Lisboa; recibe ~50 fotos con mi edición y color.", fr: "Mini-séance rapide dans le centre de Lisbonne ; vous recevez ~50 photos avec mon édition et mes couleurs." },
  },
  { id: "39b93d16-443e-4e4c-a218-e718cfa70681",
    name: { pt: "Sessão rápida casal/família", de: "Schnelles Paar-/Familien-Shooting", es: "Sesión rápida pareja/familia", fr: "Séance rapide couple/famille" },
    description: { pt: "Sessão fotográfica matinal rápida no centro de Lisboa ou em miradouros de Alfama. Recebe até 50-60 fotografias com edição básica e correcção de cor. Entrego apenas fotos finalizadas em .jpg, não em RAW. Não faço retoque de estúdio. Todas as fotos têm o mesmo estilo.", de: "Schnelle Morgen-Fotosession im Zentrum von Lissabon oder an Aussichtspunkten in Alfama. Sie erhalten bis zu 50-60 Fotos mit grundlegender Bearbeitung und Farbkorrektur. Ich liefere nur fertige Fotos im .jpg-Format, keine RAW-Dateien. Keine Studioretusche. Alle Fotos haben denselben Stil.", es: "Sesión matinal rápida en el centro de Lisboa o en miradores de Alfama. Recibe hasta 50-60 fotos con edición básica y corrección de color. Solo entrego fotos finalizadas en .jpg, no RAW. No hago retoque de estudio. Todas las fotos tienen el mismo estilo.", fr: "Séance photo matinale rapide dans le centre de Lisbonne ou aux miradouros d'Alfama. Vous recevez jusqu'à 50-60 photos avec édition de base et correction colorimétrique. Je livre uniquement des photos finalisées en .jpg, pas de RAW. Pas de retouche studio. Toutes les photos ont le même style." },
  },
  { id: "e52a9f89-246b-4b89-a589-4336b9d46312",
    name: { pt: "Sessão matinal solo/casal em Lisboa", de: "Morgen-Session Solo/Paar in Lissabon", es: "Sesión matinal solo/pareja en Lisboa", fr: "Séance matinale solo/couple à Lisbonne" },
    description: { pt: "Participe numa sessão fotográfica matinal na praça e arco icónicos do centro de Lisboa, com um segundo local em Alfama ou Baixa. Recebe até 80-100 fotografias com edição básica e correcção de cor. Entrego apenas fotos finalizadas em .jpg, não em RAW. Não faço retoque de estúdio.", de: "Nehmen Sie an einer Morgen-Fotosession am ikonischen Platz und Bogen im Zentrum von Lissabon teil, mit einem zweiten Standort in Alfama oder Baixa. Sie erhalten bis zu 80-100 Fotos mit grundlegender Bearbeitung und Farbkorrektur. Ich liefere nur fertige .jpg-Fotos, keine RAW-Dateien. Keine Studioretusche.", es: "Participe en una sesión matinal en la plaza y arco icónicos del centro de Lisboa, con una segunda localización en Alfama o Baixa. Recibe hasta 80-100 fotos con edición básica y corrección de color. Solo entrego fotos finalizadas en .jpg, no RAW. No hago retoque de estudio.", fr: "Participez à une séance photo matinale sur la place emblématique et l'arc du centre de Lisbonne, avec un second lieu à Alfama ou Baixa. Vous recevez jusqu'à 80-100 photos avec édition de base et correction colorimétrique. Je ne livre que des photos finalisées en .jpg, pas de RAW. Pas de retouche studio." },
  },
  { id: "e404a364-202a-4557-bbab-0aec35c71bc0",
    name: { pt: "Sessão de família/grupo de 1h em Lisboa", de: "Familien-/Gruppen-Shooting 1 Stunde in Lissabon", es: "Sesión familia/grupo de 1h en Lisboa", fr: "Séance famille/groupe d'1h à Lisbonne" },
    description: { pt: "Sessão fotográfica matinal ou ao final do dia na praça e arco icónicos do centro de Lisboa, com um segundo local em Alfama ou Baixa. Recebe até 100-120 fotografias com edição básica e correcção de cor. Entrego apenas fotos finalizadas em .jpg, não em RAW. Não faço retoque de estúdio.", de: "Morgen- oder Abend-Fotosession am ikonischen Platz und Bogen im Zentrum von Lissabon, mit einem zweiten Standort in Alfama oder Baixa. Sie erhalten bis zu 100-120 Fotos mit grundlegender Bearbeitung und Farbkorrektur. Ich liefere nur fertige .jpg-Fotos, keine RAW-Dateien. Keine Studioretusche.", es: "Sesión matinal o al final del día en la plaza y arco icónicos del centro de Lisboa, con una segunda localización en Alfama o Baixa. Recibe hasta 100-120 fotos con edición básica y corrección de color. Solo entrego fotos finalizadas en .jpg, no RAW. No hago retoque de estudio.", fr: "Séance photo matinale ou en fin de journée sur la place emblématique et l'arc du centre de Lisbonne, avec un second lieu à Alfama ou Baixa. Vous recevez jusqu'à 100-120 photos avec édition de base et correction colorimétrique. Je ne livre que des photos finalisées en .jpg, pas de RAW. Pas de retouche studio." },
  },
  { id: "b32b3e8e-a41f-41b0-9a30-6bf66d582f2a",
    name: { pt: "Sessão no oceano / Sintra", de: "Ocean-/Sintra-Shooting", es: "Sesión en el océano / Sintra", fr: "Séance océan / Sintra" },
    description: { pt: "Sessão divertida na praia ao pôr-do-sol; ou em Sintra.\n~100+ fotografias com edição de cor, 10 fotos com retoque profundo, cortes de vídeo do iPhone.", de: "Schöne Session am Strand zum Sonnenuntergang; oder in Sintra.\n~100+ Fotos mit Farbbearbeitung, 10 Fotos mit detaillierter Retusche, Videoschnitte vom iPhone.", es: "Sesión bonita en la playa al atardecer; o en Sintra.\n~100+ fotos con edición de color, 10 fotos con retoque profundo, cortes de vídeo desde el iPhone.", fr: "Belle séance à la plage au coucher du soleil ; ou à Sintra.\n~100+ photos avec édition couleur, 10 photos avec retouche poussée, montages vidéo depuis l'iPhone." },
  },
  // Ricardo Moura
  { id: "a694259b-9ca8-4f65-a78d-205835b389d7",
    name: { pt: "O Snapshot do Porto", de: "Der Porto-Schnappschuss", es: "La instantánea de Oporto", fr: "L'instantané de Porto" },
    description: { pt: "A escolha perfeita para quem tem pouco tempo e não quer deixar o Porto sem uma memória profissional. Nesta sessão focada de 30 minutos encontramo-nos num dos pontos mais icónicos da cidade para captar retratos de impacto da sua viagem. Curta, eficaz, pensada para o(a) deixar a explorar de novo num instante.", de: "Die perfekte Wahl für alle mit knappem Zeitplan, die Porto nicht ohne professionelle Erinnerung verlassen wollen. In dieser fokussierten 30-Minuten-Session treffen wir uns an einem der ikonischsten Wahrzeichen der Stadt und halten ausdrucksstarke Porträts Ihrer Reise fest. Kurz, prägnant — und Sie können im Handumdrehen weiter erkunden.", es: "La elección perfecta para quienes tienen poco tiempo y no quieren dejar Oporto sin un recuerdo profesional. En esta sesión enfocada de 30 minutos nos encontramos en uno de los puntos más icónicos de la ciudad para capturar retratos de gran impacto de su viaje. Corta, efectiva, pensada para volver a explorar en un instante.", fr: "Le choix parfait pour celles et ceux qui ont peu de temps et ne veulent pas quitter Porto sans un souvenir professionnel. Dans cette séance ciblée de 30 minutes, nous nous retrouvons à l'un des points les plus emblématiques de la ville pour capturer des portraits saisissants de votre voyage. Courte, efficace, conçue pour vous laisser repartir explorer en un instant." },
  },
  { id: "02216af9-6492-4a00-8c3c-bfec5d6be5c3",
    name: { pt: "Os Dois Lados do Douro", de: "Die zwei Seiten des Douro", es: "Las dos orillas del Duero", fr: "Les deux rives du Douro" },
    description: { pt: "Uma jornada dinâmica de 60 minutos a captar o melhor dos dois mundos. Começamos no charme histórico e colorido da Ribeira e seguimos numa curta caminhada cénica pela ponte até Vila Nova de Gaia, para a vista panorâmica mais icónica do skyline do Porto. Duas perspectivas, uma história sem interrupções.", de: "Eine dynamische 60-Minuten-Reise, die das Beste aus beiden Welten einfängt. Wir beginnen im historischen, farbenfrohen Charme der Ribeira und gehen dann auf einem kurzen, malerischen Weg über die Brücke nach Vila Nova de Gaia, um den ikonischsten Panoramablick auf Portos Skyline zu erleben. Zwei Perspektiven, eine nahtlose Geschichte.", es: "Un recorrido dinámico de 60 minutos que captura lo mejor de ambos mundos. Empezamos entre el encanto histórico y colorido de la Ribeira y damos un breve paseo escénico por el puente hasta Vila Nova de Gaia, para la vista panorámica más icónica del skyline de Oporto. Dos perspectivas, una historia sin cortes.", fr: "Un parcours dynamique de 60 minutes qui capture le meilleur des deux mondes. Nous commençons dans le charme historique et coloré de la Ribeira, puis effectuons une courte marche scénique sur le pont jusqu'à Vila Nova de Gaia pour la vue panoramique la plus emblématique de Porto. Deux perspectives, une histoire fluide." },
  },
  { id: "17895c35-1401-4c3d-b28a-0a3329b0e6b8",
    name: { pt: "O Grand Tour do Porto", de: "Die große Porto-Tour", es: "El Grand Tour de Oporto", fr: "Le Grand Tour de Porto" },
    description: { pt: "A jornada definitiva de 3 horas para quem quer tudo. Vamos explorar as paisagens diversas do Porto — das antigas muralhas da Cidade Velha à brisa atlântica em Foz. Esqueça Ubers ou subidas: levo-o(a) no meu carro privado para uma experiência confortável e VIP. Vai apanhar a melhor luz e um legado visual completo. Para terminar, paramos num restaurante tradicional autêntico, onde o(a) deixo para saborear os verdadeiros sabores da cidade.", de: "Die definitive 3-Stunden-Reise für alle, die alles wollen. Wir erkunden die vielfältigen Landschaften Portos — von den alten Mauern der Altstadt bis zur Atlantikbrise in Foz. Vergessen Sie Ubers oder steile Wege; ich fahre Sie in meinem privaten Auto für ein komfortables, VIP-Erlebnis. Sie erhalten das beste Licht und ein vollständiges visuelles Vermächtnis. Zum Abschluss halten wir an einem authentischen traditionellen Restaurant, wo ich Sie absetze, damit Sie die echten Aromen der Stadt genießen können.", es: "La jornada definitiva de 3 horas para quienes lo quieren todo. Exploraremos los paisajes diversos de Oporto — desde las antiguas murallas del casco antiguo hasta la brisa atlántica en Foz. Olvídese de Ubers o subidas: le llevo en mi coche privado para una experiencia cómoda y VIP. Disfrutará de la mejor luz y un legado visual completo. Para terminar, hacemos parada en un restaurante tradicional auténtico donde le dejo para que saboree los verdaderos sabores de la ciudad.", fr: "Le voyage ultime de 3 heures pour celles et ceux qui veulent tout. Nous explorons les paysages variés de Porto — des anciennes murailles de la vieille ville à la brise atlantique de Foz. Oubliez Uber ou les côtes : je vous conduis dans ma voiture privée pour une expérience confortable et VIP. Vous profiterez de la meilleure lumière et d'un héritage visuel complet. Pour finir, nous faisons étape dans un restaurant traditionnel authentique où je vous dépose pour savourer les vraies saveurs de la ville." },
  },
  { id: "34fcb9de-a40b-423f-826b-5099d410ebc5",
    name: { pt: "Pack Portfólio para Criadores", de: "Creator-Portfolio-Paket", es: "Pack Portafolio para Creadores", fr: "Pack Portfolio Créateur" },
    description: { pt: "Feito para o feed. Pensado para a história.\n\nPensado para influenciadores, bloggers e empreendedores criativos, este pacote maximiza a sua produção visual. Vamos aos pontos mais \"instagramáveis\" da cidade — das fachadas de azulejos azuis à arquitectura brutalista — para que saia com um mês de conteúdo premium numa única sessão. Eu trago o equipamento profissional e o olhar local; você traz a visão.", de: "Für den Feed. Für die Story.\n\nDieses Paket richtet sich an Influencer, Blogger und kreative Unternehmer und maximiert Ihren visuellen Output. Wir besuchen die instagramabelsten Orte der Stadt — von den blauen Fliesenfassaden bis zur brutalistischen Architektur — sodass Sie mit Premium-Content für einen ganzen Monat aus einer einzigen Session gehen. Ich bringe die professionelle Ausrüstung und das lokale Auge; Sie bringen die Vision.", es: "Hecho para el feed. Pensado para la historia.\n\nDiseñado para influencers, blogueros y emprendedores creativos, este paquete maximiza su producción visual. Recorreremos los lugares más \"instagrameables\" de la ciudad — de las fachadas de azulejos azules a la arquitectura brutalista — para que salga con un mes de contenido premium en una sola sesión. Yo aporto el equipo profesional y el ojo local; usted aporta la visión.", fr: "Fait pour le feed. Pensé pour la story.\n\nConçu pour les influenceurs, blogueurs et entrepreneurs créatifs, ce pack maximise votre production visuelle. Nous parcourons les lieux les plus \"instagrammables\" de la ville — des façades aux azulejos bleus à l'architecture brutaliste — pour que vous repartiez avec un mois de contenu premium en une seule séance. Je fournis le matériel pro et l'œil local ; vous apportez la vision." },
  },
  { id: "300b649f-8e15-4b3f-bd9e-b994cb2528b2",
    name: { pt: "Lua-de-mel: Legado", de: "Hochzeitsreise: Vermächtnis", es: "Luna de miel: Legado", fr: "Lune de miel : Héritage" },
    description: { pt: "Celebre a vossa primeira viagem juntos.\n\nA lua-de-mel é mais do que férias — é o início da vossa história partilhada. Deixem os selfies para trás e permitam-me documentar o vosso romance nos cenários mais encantadores do Norte. Das ruelas escondidas e banhadas pelo sol do Porto à elegância histórica de Braga, esta experiência foi pensada para ser descontraída, íntima e profundamente cinematográfica.", de: "Feiern Sie Ihre erste gemeinsame Reise.\n\nIhre Hochzeitsreise ist mehr als ein Urlaub — sie ist der Beginn Ihrer gemeinsamen Geschichte. Lassen Sie die Selfies hinter sich und erlauben Sie mir, Ihre Romanze vor den bezauberndsten Kulissen des Nordens festzuhalten. Von Portos versteckten, sonnendurchfluteten Gassen bis zur historischen Eleganz von Braga ist dieses Erlebnis entspannt, intim und zutiefst filmisch gestaltet.", es: "Celebren su primer viaje juntos.\n\nLa luna de miel es más que unas vacaciones — es el inicio de su historia compartida. Olviden los selfies y permítanme documentar su romance en los escenarios más encantadores del Norte. Desde las callejuelas escondidas y bañadas por el sol de Oporto hasta la elegancia histórica de Braga, esta experiencia está pensada para ser relajada, íntima y profundamente cinematográfica.", fr: "Célébrez votre premier voyage à deux.\n\nVotre lune de miel est plus que des vacances — c'est le début de votre histoire commune. Oubliez les selfies et laissez-moi documenter votre romance devant les décors les plus enchanteurs du Nord. Des ruelles cachées baignées de soleil de Porto à l'élégance historique de Braga, cette expérience est conçue pour être détendue, intime et profondément cinématographique." },
  },
  { id: "529a61e9-cc03-4464-aaee-0efdf3e63429",
    name: { pt: "Elopements: Histórias Íntimas no Coração do Norte", de: "Elopements: Intime Geschichten im Herzen des Nordens", es: "Elopements: Historias Íntimas en el Corazón del Norte", fr: "Elopements : Histoires intimes au cœur du Nord" },
    description: { pt: "A luz dourada do Porto e a elegância histórica de Braga oferecem alguns dos cenários mais românticos do mundo para duas pessoas dizerem \"sim\". Se o casamento tradicional não é para si, vamos criar um escape que seja.\n\nEspecializo-me em documentar elopements — os olhares discretos, os votos sussurrados e a emoção crua de um dia inteiramente centrado na vossa ligação. Quer seja um terraço secreto sobre o Douro ou os jardins monumentais do Bom Jesus, ofereço uma combinação fluida de fotografia e filme cinematográfico.", de: "Portos goldenes Licht und Bragas historische Eleganz bieten einige der romantischsten Kulissen der Welt, um zueinander \"Ja\" zu sagen. Wenn die traditionelle Hochzeit nichts für Sie ist, gestalten wir Ihre eigene Auszeit.\n\nIch spezialisiere mich darauf, Elopements zu dokumentieren — die stillen Blicke, die geflüsterten Schwüre, die rohe Emotion eines Tages, der ganz Ihrer Verbindung gewidmet ist. Ob auf einer geheimen Dachterrasse über dem Douro oder in den monumentalen Gärten des Bom Jesus — ich biete eine nahtlose Kombination aus Fotografie und filmischem Video.", es: "La luz dorada de Oporto y la elegancia histórica de Braga ofrecen algunos de los escenarios más románticos del mundo para que dos personas se digan \"sí\". Si la boda tradicional no es lo suyo, creemos juntos una escapada que sí lo sea.\n\nMe especializo en documentar elopements — las miradas discretas, los votos susurrados y la emoción pura de un día centrado por completo en su conexión. Ya sea una azotea secreta sobre el Duero o los jardines monumentales del Bom Jesus, ofrezco una combinación fluida de fotografía y vídeo cinematográfico.", fr: "La lumière dorée de Porto et l'élégance historique de Braga offrent certains des décors les plus romantiques au monde pour se dire \"oui\". Si le mariage traditionnel n'est pas pour vous, créons ensemble une escapade qui vous ressemble.\n\nJe me spécialise dans la documentation des elopements — les regards discrets, les vœux murmurés, l'émotion brute d'une journée entièrement consacrée à votre lien. Que ce soit un toit secret au-dessus du Douro ou les jardins monumentaux du Bom Jesus, j'offre un mélange fluide de photographie et de film cinématographique." },
  },
  // Chris Batista (3 identical packages)
  { id: "27a57f66-79c9-44c6-90ad-dc3a52608638",
    name: { pt: "Photo Tour no Porto", de: "Foto-Tour in Porto", es: "Photo Tour en Oporto", fr: "Photo Tour à Porto" },
    description: { pt: "Encontramo-nos no local e hora combinados, e a partir daí caminhamos, conversamos, apreciamos a vista e, claro, fotografamos em pontos estratégicos e bonitos pelo caminho. Não se preocupe com poses ou ângulos, eu trato disso. É uma experiência leve e muito divertida! Estou totalmente aberto a ideias e garanto que toda a gente se sente confortável e como em casa neste passeio.", de: "Wir treffen uns am vereinbarten Ort zur vereinbarten Zeit, und von dort aus laufen wir, unterhalten uns, genießen die Aussicht und fotografieren natürlich an strategischen, schönen Plätzen entlang des Wegs. Machen Sie sich keine Gedanken um Posen oder Winkel, das übernehme ich. Es ist eine leichte und sehr unterhaltsame Erfahrung! Ich bin sehr offen für Ideen und garantiere, dass sich alle wohl und zu Hause fühlen.", es: "Nos encontramos en el lugar y hora acordados, y desde allí caminamos, charlamos, disfrutamos de la vista y, por supuesto, fotografiamos en puntos estratégicos y bonitos por el camino. No se preocupe por poses o ángulos, yo me encargo. ¡Es una experiencia ligera y muy divertida! Estoy muy abierto a ideas y garantizo que todos se sientan cómodos y como en casa en este paseo.", fr: "Nous nous retrouvons au lieu et à l'heure convenus, et de là nous marchons, discutons, profitons de la vue et, bien sûr, photographions à des endroits stratégiques et magnifiques sur le chemin. Ne vous souciez pas des poses ou des angles, je m'en charge. C'est une expérience légère et très amusante ! Je suis totalement ouvert aux idées et je garantis que tout le monde se sent à l'aise et comme à la maison." },
  },
  { id: "e8a6790b-c837-4e9c-96ac-ba319d743360",
    name: { pt: "Photo Tour no Porto 2", de: "Foto-Tour in Porto 2", es: "Photo Tour en Oporto 2", fr: "Photo Tour à Porto 2" },
    description: { pt: "Encontramo-nos no local e hora combinados, e a partir daí caminhamos, conversamos, apreciamos a vista e, claro, fotografamos em pontos estratégicos e bonitos pelo caminho. Não se preocupe com poses ou ângulos, eu trato disso. É uma experiência leve e muito divertida! Estou totalmente aberto a ideias e garanto que toda a gente se sente confortável e como em casa neste passeio.", de: "Wir treffen uns am vereinbarten Ort zur vereinbarten Zeit, und von dort aus laufen wir, unterhalten uns, genießen die Aussicht und fotografieren natürlich an strategischen, schönen Plätzen entlang des Wegs. Machen Sie sich keine Gedanken um Posen oder Winkel, das übernehme ich. Es ist eine leichte und sehr unterhaltsame Erfahrung! Ich bin sehr offen für Ideen und garantiere, dass sich alle wohl und zu Hause fühlen.", es: "Nos encontramos en el lugar y hora acordados, y desde allí caminamos, charlamos, disfrutamos de la vista y, por supuesto, fotografiamos en puntos estratégicos y bonitos por el camino. No se preocupe por poses o ángulos, yo me encargo. ¡Es una experiencia ligera y muy divertida! Estoy muy abierto a ideas y garantizo que todos se sientan cómodos y como en casa en este paseo.", fr: "Nous nous retrouvons au lieu et à l'heure convenus, et de là nous marchons, discutons, profitons de la vue et, bien sûr, photographions à des endroits stratégiques et magnifiques sur le chemin. Ne vous souciez pas des poses ou des angles, je m'en charge. C'est une expérience légère et très amusante ! Je suis totalement ouvert aux idées et je garantis que tout le monde se sent à l'aise et comme à la maison." },
  },
  { id: "cadbac23-1001-4827-a3a8-9d2735c7193c",
    name: { pt: "Photo Tour no Porto 3", de: "Foto-Tour in Porto 3", es: "Photo Tour en Oporto 3", fr: "Photo Tour à Porto 3" },
    description: { pt: "Encontramo-nos no local e hora combinados, e a partir daí caminhamos, conversamos, apreciamos a vista e, claro, fotografamos em pontos estratégicos e bonitos pelo caminho. Não se preocupe com poses ou ângulos, eu trato disso. É uma experiência leve e muito divertida! Estou totalmente aberto a ideias e garanto que toda a gente se sente confortável e como em casa neste passeio.", de: "Wir treffen uns am vereinbarten Ort zur vereinbarten Zeit, und von dort aus laufen wir, unterhalten uns, genießen die Aussicht und fotografieren natürlich an strategischen, schönen Plätzen entlang des Wegs. Machen Sie sich keine Gedanken um Posen oder Winkel, das übernehme ich. Es ist eine leichte und sehr unterhaltsame Erfahrung! Ich bin sehr offen für Ideen und garantiere, dass sich alle wohl und zu Hause fühlen.", es: "Nos encontramos en el lugar y hora acordados, y desde allí caminamos, charlamos, disfrutamos de la vista y, por supuesto, fotografiamos en puntos estratégicos y bonitos por el camino. No se preocupe por poses o ángulos, yo me encargo. ¡Es una experiencia ligera y muy divertida! Estoy muy abierto a ideas y garantizo que todos se sientan cómodos y como en casa en este paseo.", fr: "Nous nous retrouvons au lieu et à l'heure convenus, et de là nous marchons, discutons, profitons de la vue et, bien sûr, photographions à des endroits stratégiques et magnifiques sur le chemin. Ne vous souciez pas des poses ou des angles, je m'en charge. C'est une expérience légère et très amusante ! Je suis totalement ouvert aux idées et je garantis que tout le monde se sent à l'aise et comme à la maison." },
  },
  // Isa Mestre
  { id: "0f88ad92-4d3f-4023-adc2-cea3126251e3",
    name: { pt: "Essential", de: "Essential", es: "Essential", fr: "Essential" },
    description: { pt: "Uma experiência simples e significativa, pensada para captar a vossa ligação de forma natural. Durante esta sessão de 45 minutos numa única localização deslumbrante, guio-vos com indicações de luz mantendo tudo descontraído e sem esforço. Recebem 20 imagens cuidadosamente editadas em alta resolução, entregues numa galeria privada online em 5 dias úteis.", de: "Eine schlichte, bedeutungsvolle Erfahrung, die Ihre Verbindung auf natürliche Weise festhält. In dieser 45-minütigen Session an einem atemberaubenden Ort führe ich Sie mit Lichtanweisungen, während alles entspannt und mühelos bleibt. Sie erhalten 20 sorgfältig bearbeitete Bilder in hoher Auflösung, geliefert in einer privaten Online-Galerie innerhalb von 5 Werktagen.", es: "Una experiencia simple y significativa, pensada para captar su conexión de forma natural. Durante esta sesión de 45 minutos en una ubicación espectacular, les guío con indicaciones de luz manteniendo todo relajado y sin esfuerzo. Reciben 20 imágenes cuidadosamente editadas en alta resolución, entregadas en una galería privada online en 5 días laborables.", fr: "Une expérience simple et porteuse de sens, conçue pour capter votre connexion de manière naturelle. Pendant cette séance de 45 minutes sur un lieu unique et magnifique, je vous guide avec des indications de lumière en gardant tout détendu et fluide. Vous recevez 20 images soigneusement retouchées en haute résolution, livrées dans une galerie privée en ligne sous 5 jours ouvrés." },
  },
  { id: "dd4468c2-af5c-45cf-a5ef-bac986ff4fe9",
    name: { pt: "Signature", de: "Signature", es: "Signature", fr: "Signature" },
    description: { pt: "Este pacote é ideal para quem quer um pouco mais de tempo e variedade na sessão. Com até 60 minutos de fotografia em uma ou duas localizações — como praia e falésias — vão desfrutar de uma experiência dinâmica e descontraída. Ofereço orientação personalizada, misturando momentos naturais e candid com poses suaves para criar uma galeria bonita e autêntica. Recebem 35 imagens editadas em alta resolução, entregues em 3 dias úteis.", de: "Dieses Paket ist ideal für alle, die etwas mehr Zeit und Vielfalt in ihrer Session möchten. Mit bis zu 60 Minuten Fotografie an ein oder zwei Orten — etwa Strand und Klippen — genießen Sie eine dynamische, entspannte Erfahrung. Ich biete personalisierte Anleitung, die natürliche, candid Momente mit sanften Posen verbindet, um eine schöne, authentische Galerie zu schaffen. Sie erhalten 35 hochauflösend bearbeitete Bilder, geliefert in 3 Werktagen.", es: "Este paquete es ideal para quienes quieren un poco más de tiempo y variedad en la sesión. Con hasta 60 minutos de fotografía en una o dos localizaciones — como playa y acantilados — disfrutarán de una experiencia dinámica y relajada. Ofrezco dirección personalizada, mezclando momentos naturales y candid con poses suaves para crear una galería bonita y auténtica. Reciben 35 imágenes editadas en alta resolución, entregadas en 3 días laborables.", fr: "Ce pack est idéal pour celles et ceux qui veulent un peu plus de temps et de variété dans la séance. Avec jusqu'à 60 minutes de prise de vue dans un ou deux lieux — plage et falaises par exemple — vous profiterez d'une expérience dynamique et détendue. Je propose une direction personnalisée, mêlant moments naturels et poses douces pour créer une galerie belle et authentique. Vous recevez 35 images haute résolution éditées, livrées sous 3 jours ouvrés." },
  },
  { id: "2edd4d7c-77f9-4427-8618-360c0278eaac",
    name: { pt: "Premium", de: "Premium", es: "Premium", fr: "Premium" },
    description: { pt: "Uma experiência signature para casais e famílias que procuram uma sessão refinada e cinematográfica. Em até 90 minutos exploramos até três localizações cuidadosamente escolhidas, criando uma galeria diversa e visualmente rica. Com direcção feita à medida que combina poses elegantes com momentos genuínos, cada detalhe é captado com intenção. A experiência inclui 60 imagens profissionalmente editadas em alta resolução e um slideshow highlight de 60 segundos, entregues em 48 horas.", de: "Ein Signature-Erlebnis für Paare und Familien, die eine raffinierte, filmische Session suchen. In bis zu 90 Minuten erkunden wir bis zu drei sorgfältig ausgewählte Orte und schaffen eine vielseitige, visuell reiche Galerie. Mit maßgeschneiderter Anleitung, die elegante Posen mit echten Momenten verbindet, wird jedes Detail mit Intention festgehalten. Inklusive 60 professionell bearbeiteter Bilder in hoher Auflösung und einer 60-Sekunden-Highlight-Slideshow, geliefert binnen 48 Stunden.", es: "Una experiencia signature para parejas y familias que buscan una sesión refinada y cinematográfica. En hasta 90 minutos exploramos hasta tres localizaciones cuidadosamente elegidas, creando una galería diversa y visualmente rica. Con dirección a medida que combina poses elegantes con momentos genuinos, cada detalle se capta con intención. La experiencia incluye 60 imágenes profesionalmente editadas en alta resolución y un slideshow highlight de 60 segundos, entregados en 48 horas.", fr: "Une expérience signature pour les couples et les familles en quête d'une séance raffinée et cinématographique. En 90 minutes, nous explorons jusqu'à trois lieux soigneusement sélectionnés pour créer une galerie variée et visuellement riche. Avec une direction sur mesure mêlant poses élégantes et instants sincères, chaque détail est capté avec intention. L'expérience inclut 60 images haute résolution éditées professionnellement et un diaporama highlight de 60 secondes, livrés sous 48 heures." },
  },
  // Sophie Bellmann
  { id: "a5904e59-3073-4856-bb1c-7bcb8950fa85",
    name: { pt: "Pequena Sessão na Praia", de: "Kleine Strand-Session", es: "Pequeña sesión en la playa", fr: "Petite séance plage" },
    description: { pt: "Uma forma simples e bonita de captar este momento sem ocupar muito tempo.\nPerfeita para quem quer algumas imagens significativas num cenário descontraído e natural.", de: "Eine einfache und schöne Möglichkeit, diesen Moment festzuhalten, ohne viel Zeit in Anspruch zu nehmen.\nPerfekt, wenn Sie ein paar bedeutungsvolle Bilder in entspannter, natürlicher Umgebung wünschen.", es: "Una forma sencilla y bonita de captar este momento sin ocupar demasiado tiempo.\nPerfecta para quienes quieren unas pocas imágenes significativas en un entorno relajado y natural.", fr: "Une façon simple et belle de capturer cet instant sans y consacrer trop de temps.\nParfait pour qui souhaite quelques images significatives dans un cadre détendu et naturel." },
  },
  { id: "baca12f9-3530-4510-9634-40c757b08b8b",
    name: { pt: "Sessão de Retrato", de: "Porträt-Session", es: "Sesión de retrato", fr: "Séance portrait" },
    description: { pt: "Uma sessão mais ampla e criativa, com tempo para abrandar, explorar e criar uma maior variedade de imagens.\nPerfeita para casais, famílias e sessões de maternidade onde quer mergulhar plenamente na experiência.", de: "Eine ausgedehntere, kreativere Session mit Zeit, langsamer zu werden, zu erkunden und eine größere Bildvielfalt zu schaffen.\nPerfekt für Paare, Familien und Schwangerschafts-Sessions, in denen Sie vollständig in die Erfahrung eintauchen möchten.", es: "Una sesión más amplia y creativa, con tiempo para bajar el ritmo, explorar y crear una mayor variedad de imágenes.\nPerfecta para parejas, familias y sesiones de maternidad en las que quiere sumergirse de lleno en la experiencia.", fr: "Une séance plus généreuse et créative, avec le temps de ralentir, d'explorer et de créer une plus grande variété d'images.\nParfaite pour les couples, les familles et les séances maternité où vous voulez vous immerger pleinement." },
  },
  { id: "cf357170-ddeb-4900-b3df-f58409539404",
    name: { pt: "Sessão de Pedido de Casamento & Elopement", de: "Heiratsantrag & Elopement-Session", es: "Sesión de pedida de mano y elopement", fr: "Séance demande en mariage & elopement" },
    description: { pt: "Capture um dos momentos mais íntimos e significativos da sua história de amor, de forma natural, artística e autêntica.\nEsta sessão de pedido de casamento e elopement foi pensada para preservar emoções reais — a antecipação, a surpresa, a ligação e a beleza silenciosa do vosso momento partilhado.\n\nGuio-vos com uma abordagem documental e suave, deixando espaço para expressões genuínas e oferecendo direcção criativa quando necessário. Juntos criamos uma história visual atemporal.", de: "Halten Sie einen der intimsten und bedeutungsvollsten Momente Ihrer Liebesgeschichte auf natürliche, künstlerische und authentische Weise fest.\nDiese Heiratsantrag- & Elopement-Session ist darauf ausgelegt, echte Emotionen zu bewahren — die Vorfreude, die Überraschung, die Verbindung und die stille Schönheit Ihres geteilten Moments.\n\nIch führe Sie mit einem sanften, dokumentarischen Ansatz, lasse Raum für authentische Ausdrücke und gebe bei Bedarf kreative Anleitung. Gemeinsam schaffen wir eine zeitlose visuelle Geschichte.", es: "Capture uno de los momentos más íntimos y significativos de su historia de amor, de forma natural, artística y auténtica.\nEsta sesión de pedida de mano y elopement está pensada para preservar emociones reales — la anticipación, la sorpresa, la conexión y la belleza silenciosa de su momento compartido.\n\nLes guío con un enfoque documental y suave, dejando espacio para expresiones genuinas y aportando dirección creativa cuando hace falta. Juntos creamos una historia visual atemporal.", fr: "Capturez l'un des moments les plus intimes et significatifs de votre histoire d'amour, de manière naturelle, artistique et authentique.\nCette séance demande en mariage et elopement est conçue pour préserver les vraies émotions — l'attente, la surprise, la connexion et la beauté silencieuse de votre instant partagé.\n\nJe vous guide avec une approche douce et documentaire, en laissant place aux expressions sincères tout en proposant une direction créative quand nécessaire. Ensemble nous créons une histoire visuelle intemporelle." },
  },
];

for (const p of PKG) {
  const cols = []; const params = [];
  for (const loc of ["pt","de","es","fr"]) {
    if (p.name?.[loc]) { cols.push(`name_${loc} = $${params.length+1}`); params.push(p.name[loc]); }
    if (p.description?.[loc]) { cols.push(`description_${loc} = $${params.length+1}`); params.push(p.description[loc]); }
  }
  if (cols.length === 0) continue;
  cols.push(`translations_updated_at = NOW()`, `translations_dirty = FALSE`);
  params.push(p.id);
  await client.query(`UPDATE packages SET ${cols.join(", ")} WHERE id = $${params.length}`, params);
  console.log(`✓ ${p.id.slice(0,8)} ${p.name.fr || p.name.en || ""}`);
}
await client.end();
console.log(`\nBatch pkg-1 done — ${PKG.length} packages translated.`);
