// Package batch 4 — final 40 packages (Andre, David, Elena K, Daniel, Cindy, Giovana, Marilia, Pedro, Jonathan, Nadiya, Irina, Elena L, J Grilo)
import pg from "pg";
import { readFileSync } from "fs";
const env = Object.fromEntries(readFileSync("/var/www/photoportugal/.env","utf-8").split("\n").filter((l)=>l&&l.includes("=")&&!l.startsWith("#")).map((l)=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim().replace(/^["']|["']$/g,"")]}));
const client = new pg.Client({ connectionString: env.DATABASE_URL });
await client.connect();

// Re-used template strings (André + David repeats)
const ANDRE_ELOPEMENT = {
  pt: "Chegou o grande dia.\nEscrito com luz e com amor, guiado pela espontaneidade e autenticidade de cada momento.\nLevamo-vos aos lugares mais extraordinários, onde irão viver a página mais bonita da vossa história.\nO capítulo mais bonito da vossa vida começa aqui.\nA Madeira é o cenário.\nTudo o que têm de fazer é viver o momento.\nO vosso novo começo começa aqui.",
  de: "Der große Tag ist da.\nGeschrieben mit Licht und Liebe, geführt von der Spontaneität und Authentizität jedes Moments.\nWir bringen euch an die außergewöhnlichsten Orte, wo ihr die schönste Seite eurer Geschichte erleben werdet.\nDas schönste Kapitel eures Lebens beginnt hier.\nMadeira ist die Kulisse.\nIhr müsst nur den Moment leben.\nEuer neuer Anfang beginnt hier.",
  es: "Ha llegado el gran día.\nEscrito con luz y con amor, guiado por la espontaneidad y autenticidad de cada momento.\nLes llevamos a los lugares más extraordinarios donde vivirán la página más bonita de su historia.\nEl capítulo más hermoso de su vida empieza aquí.\nMadeira es el escenario.\nLo único que tienen que hacer es vivir el momento.\nSu nuevo comienzo empieza aquí.",
  fr: "Le grand jour est arrivé.\nÉcrit avec lumière et amour, guidé par la spontanéité et l'authenticité de chaque instant.\nNous vous emmenons dans les lieux les plus extraordinaires où vous vivrez la plus belle page de votre histoire.\nLe plus beau chapitre de votre vie commence ici.\nMadère est le décor.\nVous n'avez qu'à vivre l'instant.\nVotre nouveau départ commence ici.",
};
const ANDRE_PROPOSAL = {
  pt: "O início da vossa história de amor começa aqui.\nLevamo-vos aos lugares mais extraordinários, para que possam viver verdadeiramente este novo capítulo da vida como ele merece.\nMais do que memórias, captamos a espontaneidade e autenticidade por trás de cada emoção para que possam revivê-las, vezes sem conta.\nA Madeira é o cenário.\nTudo o que têm de fazer é viver o momento.\nA vossa nova história começa aqui.",
  de: "Hier beginnt eure Liebesgeschichte.\nWir bringen euch an die außergewöhnlichsten Orte, damit ihr dieses neue Kapitel des Lebens wirklich so erlebt, wie es gelebt werden sollte.\nMehr als Erinnerungen — wir halten die Spontaneität und Authentizität hinter jeder Emotion fest, damit ihr sie immer wieder neu erleben könnt.\nMadeira ist die Kulisse.\nIhr müsst nur den Moment leben.\nEure neue Geschichte beginnt hier.",
  es: "El inicio de su historia de amor empieza aquí.\nLes llevamos a los lugares más extraordinarios para que puedan vivir verdaderamente este nuevo capítulo como merece ser vivido.\nMás que recuerdos, capturamos la espontaneidad y autenticidad detrás de cada emoción para que puedan revivirlas una y otra vez.\nMadeira es el escenario.\nLo único que tienen que hacer es vivir el momento.\nSu nueva historia empieza aquí.",
  fr: "Le début de votre histoire d'amour commence ici.\nNous vous emmenons dans les lieux les plus extraordinaires, pour que vous puissiez vraiment vivre ce nouveau chapitre comme il mérite de l'être.\nPlus que des souvenirs, nous captons la spontanéité et l'authenticité derrière chaque émotion pour que vous puissiez les revivre, encore et encore.\nMadère est le décor.\nVous n'avez plus qu'à vivre l'instant.\nVotre nouvelle histoire commence ici.",
};

const PKG = [
  { id: "ca9841f4-f087-487d-b59a-7580eba8867d",
    name: { pt: "Elopement", de: "Elopement", es: "Elopement", fr: "Elopement" }, description: ANDRE_ELOPEMENT },
  { id: "50ffd975-f2ab-4170-861b-7ba660ba61db",
    name: { pt: "Elopement", de: "Elopement", es: "Elopement", fr: "Elopement" }, description: ANDRE_ELOPEMENT },
  { id: "3ecddbbd-5b43-45cd-b03b-506944a93f87",
    name: { pt: "Pedidos de Casamento", de: "Heiratsanträge", es: "Pedidas de mano", fr: "Demandes en mariage" }, description: ANDRE_PROPOSAL },
  { id: "e6ee7ac2-97de-40b9-b99f-c201fb2158e3",
    name: { pt: "Casal Luz Atlântica", de: "Atlantik-Licht-Paar", es: "Pareja Luz Atlántica", fr: "Couple Lumière Atlantique" },
    description: { pt: "Viva uma sessão romântica de casal ao ar livre na deslumbrante Costa Alentejana, de Tróia a Porto Covo, com foco especial na região de Comporta. Capte o vosso amor entre dunas douradas, praias selvagens, arrozais e pinhais, banhados pela suave luz atlântica. Perfeito para viajantes que procuram memórias únicas e elegantes numa das paisagens costeiras mais intactas e mágicas da Europa.", de: "Erleben Sie ein romantisches Outdoor-Paar-Shooting an Portugals atemberaubender Alentejo-Küste, von Tróia bis Porto Covo, mit besonderem Fokus auf die Region Comporta. Halten Sie Ihre Liebe zwischen goldenen Dünen, wilden Stränden, Reisfeldern und Pinienwäldern fest, alles im sanften Atlantiklicht. Perfekt für Reisende, die einzigartige, elegante Erinnerungen in einer der unberührtesten und magischsten Küstenlandschaften Europas suchen.", es: "Disfrute de una romántica sesión de pareja al aire libre por la espectacular Costa Alentejana, de Tróia a Porto Covo, con especial atención a la región de Comporta. Capture su amor entre dunas doradas, playas salvajes, arrozales y pinares, todo bañado por la suave luz atlántica. Perfecto para viajeros que buscan recuerdos únicos y elegantes en uno de los paisajes costeros más vírgenes y mágicos de Europa.", fr: "Vivez une séance couple romantique en extérieur le long de la magnifique côte de l'Alentejo, de Tróia à Porto Covo, avec un focus particulier sur la région de Comporta. Capturez votre amour parmi les dunes dorées, les plages sauvages, les rizières et les forêts de pins, le tout baigné dans la douce lumière atlantique. Parfait pour les voyageurs en quête de souvenirs uniques et élégants dans l'un des paysages côtiers les plus préservés et magiques d'Europe." } },
  { id: "ac9c1159-b847-4f51-9961-f31ccfe8755f",
    name: { pt: "Tróia", de: "Tróia", es: "Tróia", fr: "Tróia" },
    description: { pt: "Viva uma sessão fotográfica deslumbrante na Península de Tróia, onde praias intermináveis de areia branca encontram águas atlânticas cristalinas e paisagens naturais protegidas. Das dunas douradas aos pinhais serenos e às vistas costeiras vastas, cada cenário parece intocado e cinematográfico. Perfeito para casais, famílias ou retratos que procuram um refúgio refinado, natural e inesquecível na costa atlântica selvagem de Portugal.", de: "Erleben Sie ein atemberaubendes Foto-Shooting auf der Halbinsel Tróia, wo endlose weiße Sandstrände auf kristallklares Atlantikwasser und geschützte Naturlandschaften treffen. Von goldenen Dünen über stille Pinienwälder bis hin zu weiten Küstenpanoramen wirkt jede Kulisse unberührt und filmisch. Perfekt für Paare, Familien oder Porträts, die einen raffinierten, natürlichen und unvergesslichen Rückzugsort an Portugals wilder Atlantikküste suchen.", es: "Disfrute de una espectacular sesión fotográfica en la Península de Tróia, donde interminables playas de arena blanca se encuentran con aguas atlánticas cristalinas y paisajes naturales protegidos. De las dunas doradas a los serenos pinares y las amplias vistas costeras, cada escenario se siente intacto y cinematográfico. Perfecto para parejas, familias o retratos que buscan una escapada refinada, natural e inolvidable en la salvaje costa atlántica de Portugal.", fr: "Vivez une séance photo magnifique sur la péninsule de Tróia, où les plages de sable blanc à perte de vue rencontrent les eaux atlantiques cristallines et des paysages naturels protégés. Des dunes dorées aux pinèdes sereines et aux vastes panoramas côtiers, chaque décor semble intact et cinématographique. Parfait pour couples, familles ou portraits en quête d'une escapade raffinée, naturelle et inoubliable sur la côte atlantique sauvage du Portugal." } },
  { id: "cc8e8403-9ce2-4744-8d93-4fc5daaeaeab",
    name: { pt: "Arroz Azul", de: "Blauer Reis", es: "Arroz Azul", fr: "Riz Bleu" },
    description: { pt: "Viva uma sessão fotográfica encantadora na vila de Comporta e nos arrozais circundantes, inspirada nas icónicas casas caiadas com apontamentos azuis. Percorra ruas tranquilas e paisagens luminosas onde a tradição encontra a elegância costeira. Perfeito para casais, famílias ou retratos que procuram uma estética descontraída, autêntica e atemporal num dos destinos mais pitorescos e serenos de Portugal.", de: "Erleben Sie ein bezauberndes Foto-Shooting im Dorf Comporta und seinen umliegenden Reisfeldern, inspiriert von den ikonischen weißgekalkten Häusern mit blauen Akzenten. Schlendern Sie durch ruhige Straßen und leuchtende Landschaften, in denen Tradition auf Küstenchic trifft. Perfekt für Paare, Familien oder Porträts, die eine entspannte, authentische und zeitlose Ästhetik in einem der malerischsten und ruhigsten Reiseziele Portugals suchen.", es: "Disfrute de una encantadora sesión fotográfica en el pueblo de Comporta y sus arrozales, inspirada en las icónicas casas encaladas con detalles azules. Recorra calles tranquilas y paisajes luminosos donde la tradición se encuentra con la elegancia costera. Perfecto para parejas, familias o retratos que buscan una estética relajada, auténtica y atemporal en uno de los destinos más pintorescos y serenos de Portugal.", fr: "Vivez une charmante séance photo dans le village de Comporta et ses rizières environnantes, inspirée par les emblématiques maisons blanchies à la chaux aux touches bleues. Flânez dans des rues paisibles et des paysages lumineux où la tradition rencontre l'élégance côtière. Parfait pour les couples, familles ou portraits en quête d'une esthétique détendue, authentique et intemporelle dans l'une des destinations les plus pittoresques et sereines du Portugal." } },
  { id: "cfdf323a-b3a5-442b-883f-b403fedfba38",
    name: { pt: "Melides", de: "Melides", es: "Melides", fr: "Melides" },
    description: { pt: "Viva uma sessão fotográfica atemporal na vila e na praia de Melides, onde o charme rústico encontra a beleza atlântica selvagem. Das ruas caiadas da vila aos vastos areais e dunas intocadas, cada momento é banhado por luz natural e serenidade. Perfeito para casais, famílias ou retratos que procuram uma escapada autêntica, elegante e tranquila na deslumbrante costa alentejana.", de: "Erleben Sie ein zeitloses Foto-Shooting im Dorf und am Strand von Melides, wo rustikaler Charme auf wilde Atlantikschönheit trifft. Von den weißgekalkten Dorfstraßen bis zu den weiten, unberührten Sänden und Dünen ist jeder Moment in natürliches Licht und Stille gehüllt. Perfekt für Paare, Familien oder Porträts, die eine authentische, elegante und friedliche Auszeit an Portugals herrlicher Alentejo-Küste suchen.", es: "Disfrute de una atemporal sesión fotográfica en el pueblo y la playa de Melides, donde el encanto rústico se encuentra con la salvaje belleza atlántica. De las calles encaladas del pueblo a las vastas arenas y dunas intactas, cada momento está bañado por luz natural y serenidad. Perfecto para parejas, familias o retratos que buscan una escapada auténtica, elegante y tranquila en la espectacular costa alentejana.", fr: "Vivez une séance photo intemporelle dans le village et la plage de Melides, où le charme rustique rencontre la beauté sauvage de l'Atlantique. Des ruelles blanchies à la chaux aux vastes plages et dunes intactes, chaque instant est baigné de lumière naturelle et de sérénité. Parfait pour les couples, familles ou portraits en quête d'une escapade authentique, élégante et paisible sur la magnifique côte de l'Alentejo." } },
  { id: "f33d87de-f6f7-4ffe-94a6-05491a8a6655",
    name: { pt: "Família Luz Atlântica", de: "Atlantik-Licht-Familie", es: "Familia Luz Atlántica", fr: "Famille Lumière Atlantique" },
    description: { pt: "Viva uma bela sessão familiar ao ar livre na deslumbrante Costa Alentejana, de Tróia a Porto Covo, com foco especial na região de Comporta. Capte momentos genuínos entre dunas douradas, praias selvagens, arrozais e pinhais, banhados pela suave luz atlântica. Perfeito para famílias que procuram memórias atemporais numa das paisagens costeiras mais intactas e mágicas da Europa.", de: "Erleben Sie ein wunderschönes Familienshooting an Portugals atemberaubender Alentejo-Küste, von Tróia bis Porto Covo, mit besonderem Fokus auf Comporta. Halten Sie echte Momente zwischen goldenen Dünen, wilden Stränden, Reisfeldern und Pinienwäldern fest, alles im sanften Atlantiklicht. Perfekt für Familien, die zeitlose Erinnerungen in einer der unberührtesten und magischsten Küstenlandschaften Europas suchen.", es: "Disfrute de una hermosa sesión familiar al aire libre en la espectacular Costa Alentejana, de Tróia a Porto Covo, con especial atención a Comporta. Capture momentos genuinos entre dunas doradas, playas salvajes, arrozales y pinares, todo bañado por la suave luz atlántica. Perfecto para familias que buscan recuerdos atemporales en uno de los paisajes costeros más vírgenes y mágicos de Europa.", fr: "Vivez une magnifique séance famille en extérieur le long de la côte de l'Alentejo, de Tróia à Porto Covo, avec un focus particulier sur la Comporta. Capturez des moments sincères parmi les dunes dorées, les plages sauvages, les rizières et les pinèdes, baignés dans la douce lumière atlantique. Parfait pour les familles en quête de souvenirs intemporels dans l'un des paysages côtiers les plus préservés et magiques d'Europe." } },
  { id: "e81d07d8-4ddb-4117-8a6f-b88167735c90",
    name: { pt: "Casamento de Destino em Comporta", de: "Destination-Hochzeit in Comporta", es: "Boda de destino en Comporta", fr: "Mariage de destination à Comporta" },
    description: { pt: "Celebre o seu casamento de destino na encantadora região de Comporta, onde praias selvagens, dunas douradas e arrozais serenos criam um cenário inesquecível. Com uma abordagem refinada e editorial, a vossa história é captada em luz natural e elegância sem esforço. Perfeito para casais que procuram uma experiência de casamento única, íntima e estilosa na costa mais exclusiva de Portugal.", de: "Feiern Sie Ihre Destination-Hochzeit in der bezaubernden Region Comporta, wo wilde Strände, goldene Dünen und stille Reisfelder eine unvergessliche Kulisse schaffen. Mit einem raffinierten, editorialen Ansatz wird Ihre Geschichte in natürlichem Licht und müheloser Eleganz festgehalten. Perfekt für Paare, die ein einzigartiges, intimes und stilvolles Hochzeitserlebnis an Portugals exklusivster Küste suchen.", es: "Celebre su boda de destino en la encantadora región de Comporta, donde playas salvajes, dunas doradas y arrozales serenos crean un escenario inolvidable. Con un enfoque refinado y editorial, su historia se capta en luz natural y elegancia sin esfuerzo. Perfecto para parejas que buscan una experiencia de boda única, íntima y con estilo en la costa más exclusiva de Portugal.", fr: "Célébrez votre mariage de destination dans la région enchantée de Comporta, où plages sauvages, dunes dorées et rizières paisibles offrent un décor inoubliable. Avec une approche raffinée et éditoriale, votre histoire est capturée dans une lumière naturelle et une élégance discrète. Parfait pour les couples en quête d'une expérience de mariage unique, intime et stylée sur la côte la plus exclusive du Portugal." } },
  { id: "bc25a0d9-f9dc-417a-99c9-4c088c37df2e",
    name: { pt: "Sessão Express no Porto", de: "Express-Foto-Shooting in Porto", es: "Sesión Express en Oporto", fr: "Séance Express à Porto" },
    description: { pt: "Uma sessão fotográfica curta e doce para viajantes solo ou casais que querem levar um pedacinho do Porto consigo. Descontraída, simpática e cheia de pequenos momentos que fazem sorrir. Perfeita se está com pouco tempo mas quer trazer memórias bonitas.", de: "Eine kurze, schöne Fotosession für Solo-Reisende oder Paare, die ein Stück Porto mitnehmen möchten. Entspannt, freundlich und voller kleiner Momente, die Sie zum Lächeln bringen. Perfekt, wenn Sie wenig Zeit haben, aber trotzdem schöne Erinnerungen mitnehmen wollen.", es: "Una sesión corta y bonita para viajeros solos o parejas que quieren llevarse un trocito de Oporto. Relajada, amable y llena de pequeños momentos que sacan la sonrisa. Perfecta si tiene poco tiempo pero quiere recuerdos preciosos.", fr: "Une séance courte et douce pour les voyageurs solos ou les couples qui veulent ramener un peu de Porto avec eux. Détendue, conviviale, pleine de petits moments qui font sourire. Parfait si vous avez peu de temps mais voulez de jolis souvenirs." } },
  { id: "fb431410-e926-459e-9858-94d7ee63904f",
    name: { pt: "Sessão Standard", de: "Standard-Fotosession", es: "Sesión estándar", fr: "Séance standard" },
    description: { pt: "Uma sessão fotográfica num local à sua escolha dentro da cidade. Se estiver indecisa(o), posso sugerir um sítio com base nas suas preferências.\n\nUma opção ideal para sessões individuais ou de casal.\n\nAjudo-o(a) com a escolha do outfit e guio-o(a) suavemente nas poses, mantendo tudo natural e confortável.", de: "Eine Fotosession an einem von Ihnen gewählten Ort in der Stadt. Wenn Sie unsicher sind, schlage ich einen Spot basierend auf Ihren Vorlieben vor.\n\nEine ideale Option für Solo- oder Paar-Sessions.\n\nIch helfe bei der Outfit-Auswahl und leite Sie sanft durch die Posen, alles bleibt natürlich und angenehm.", es: "Una sesión fotográfica en un lugar de su elección dentro de la ciudad. Si no se decide, puedo sugerirle un sitio según sus preferencias.\n\nUna opción ideal para sesiones individuales o de pareja.\n\nLe ayudo con la elección del outfit y le guío suavemente con las poses, manteniendo todo natural y cómodo.", fr: "Une séance photo dans un lieu de votre choix en ville. Si vous hésitez, je peux suggérer un endroit selon vos préférences.\n\nIdéal pour les séances solos ou en couple.\n\nJe vous aide à choisir la tenue et vous guide en douceur pour les poses, tout reste naturel et confortable." } },
  { id: "26c34aa3-f395-4631-853f-292d91db374f",
    name: { pt: "Sessão de Casal no Porto", de: "Paar-Fotoshooting in Porto", es: "Sesión de pareja en Oporto", fr: "Séance Couple à Porto" },
    description: { pt: "Sessão fotográfica descontraída de 1 hora pelos pontos mais icónicos do Porto. 30 fotografias editadas, naturais e autênticas, para captar o romance da vossa viagem!", de: "Entspannte 1-stündige Fotosession durch die ikonischsten Orte Portos. 30 bearbeitete, natürliche, authentische Fotos, um die Romantik Ihrer Reise einzufangen!", es: "Sesión fotográfica relajada de 1 hora por los puntos más icónicos de Oporto. 30 fotos editadas, naturales y auténticas, ¡para captar el romance de su viaje!", fr: "Séance photo détendue d'1 heure dans les lieux les plus emblématiques de Porto. 30 photos éditées, naturelles et authentiques, pour capturer la romance de votre voyage !" } },
  { id: "4997750b-4dd5-42f8-96de-228909eb3210",
    name: { pt: "Sessão de Casal — Praia", de: "Paar-Session am Strand", es: "Sesión de pareja — Playa", fr: "Séance Couple — Plage" },
    description: { pt: "Sessão de praia cinematográfica de 1h+, durante a hora dourada. Até 60 fotografias profissionalmente editadas e naturais, que preservam o romance da vossa viagem em estilo de filme!", de: "Filmische Strand-Session von 1h+ während der goldenen Stunde. Bis zu 60 professionell bearbeitete, natürliche Fotos, die die Romantik Ihrer Reise im Filmstil bewahren!", es: "Sesión cinematográfica en la playa de 1h+, durante la hora dorada. Hasta 60 fotos profesionalmente editadas y naturales, ¡que preservan el romance de su viaje en estilo de película!", fr: "Séance plage cinématographique d'1h+ pendant l'heure dorée. Jusqu'à 60 photos éditées professionnellement et naturelles, qui préservent la romance de votre voyage façon film !" } },
  { id: "05d05419-ea97-400b-8fa7-7d49fc0dda15",
    name: { pt: "Photo Walk Signature pelo Porto", de: "Porto Signature Foto-Spaziergang", es: "Photo Walk Signature por Oporto", fr: "Photo-balade Signature à Porto" },
    description: { pt: "Um passeio fotográfico curado pelos locais mais icónicos do Porto, incluindo a Igreja do Carmo, a estação de São Bento, a Sé Catedral e as ruas históricas da Cidade Velha.\n\nEste percurso reflecte a minha abordagem pessoal de fotografar a cidade — equilíbrio entre momentos naturais e retratos com orientação suave.\n\nPercorremos diferentes pontos a um ritmo descontraído, dando espaço para fotos candid e direcção simples quando necessário.", de: "Ein kuratierter Foto-Spaziergang durch Portos ikonischste Orte, darunter Igreja do Carmo, Bahnhof São Bento, Kathedrale Sé und die historischen Gassen der Altstadt.\n\nDiese Route spiegelt meinen persönlichen Ansatz wider, die Stadt zu fotografieren — eine Balance zwischen natürlichen Momenten und sanft geführten Porträts.\n\nWir bewegen uns in entspanntem Tempo durch verschiedene Spots, mit Raum für ungestellte Aufnahmen und einfache Anleitung bei Bedarf.", es: "Un photo walk curado por los lugares más icónicos de Oporto, incluyendo la Igreja do Carmo, la estación de São Bento, la Catedral Sé y las calles históricas del casco antiguo.\n\nEsta ruta refleja mi enfoque personal — el equilibrio entre momentos naturales y retratos con guía suave.\n\nRecorremos distintos puntos a un ritmo relajado, dejando espacio para fotos candid y dirección simple cuando hace falta.", fr: "Une photo-balade soignée à travers les lieux les plus emblématiques de Porto, dont l'Igreja do Carmo, la gare de São Bento, la cathédrale Sé et les rues historiques de la vieille ville.\n\nCe parcours reflète mon approche personnelle — un équilibre entre instants naturels et portraits guidés en douceur.\n\nNous parcourons différents lieux à un rythme détendu, en laissant place aux photos spontanées et à une direction simple quand nécessaire." } },
  { id: "9896d842-d527-4b49-b60c-c51254d60136",
    name: { pt: "História do Oceano", de: "Ozean-Geschichte", es: "Historia del Océano", fr: "Histoire de l'Océan" },
    description: { pt: "Uma sessão fotográfica junto à costa atlântica, focada em luz natural, movimento e atmosfera.\n\nEsta sessão é menos sobre locais específicos e mais sobre estado de espírito. Vento, oceano e espaço aberto criam uma sensação mais cinematográfica. Guio-o(a) com poses simples e naturais, e capto também momentos candid.\n\nMelhor agendar perto do pôr-do-sol, para uma luz mais suave.", de: "Eine Fotosession an der Atlantikküste, fokussiert auf natürliches Licht, Bewegung und Atmosphäre.\n\nDiese Session geht weniger um bestimmte Orte und mehr um Stimmung. Wind, Ozean und offener Raum schaffen ein cineastisches Gefühl. Ich leite Sie mit einfachen, natürlichen Posen und halte auch ungestellte Momente fest.\n\nAm besten zum Sonnenuntergang für weicheres Licht buchen.", es: "Una sesión fotográfica junto a la costa atlántica, centrada en la luz natural, el movimiento y la atmósfera.\n\nVa menos de lugares específicos y más de estado de ánimo. Viento, océano y espacio abierto crean una sensación cinematográfica. Le guío con poses simples y naturales y capto también momentos candid.\n\nMejor agendar cerca del atardecer para una luz más suave.", fr: "Une séance photo au bord de la côte atlantique, axée sur la lumière naturelle, le mouvement et l'atmosphère.\n\nCette séance n'est pas tant une question de lieux précis que d'ambiance. Vent, océan et espace ouvert créent une sensation cinématographique. Je vous guide avec des poses simples et naturelles, et je capte aussi les moments spontanés.\n\nÀ programmer de préférence près du coucher du soleil pour une lumière plus douce." } },
  { id: "ae5b219d-feb8-4217-ba84-3be0a9bbf273",
    name: { pt: "Mini-sessão", de: "Mini-Shooting", es: "Mini sesión", fr: "Mini-séance" },
    description: { pt: "15 minutos para captar algumas memórias bonitas!", de: "15 Minuten, um ein paar schöne Erinnerungen festzuhalten!", es: "¡15 minutos para captar unos cuantos recuerdos preciosos!", fr: "15 minutes pour capturer quelques beaux souvenirs !" } },
  { id: "3143eb8f-3e19-473f-9eb7-282d50437207",
    name: { pt: "Sessão Hora Dourada", de: "Goldene-Stunde-Session", es: "Sesión Hora Dorada", fr: "Séance Heure Dorée" },
    description: { pt: "(Máx 6 pessoas) Encontramo-nos na praia, conversamos sobre os vossos desejos e começamos a sessão de forma descontraída e natural. Guio-vos onde for preciso, deixando espaço para momentos reais. As fotografias editadas são entregues numa semana.", de: "(Max 6 Personen) Wir treffen uns am Strand, sprechen über eure Wünsche und beginnen die Session locker und natürlich. Ich leite, wenn nötig, lasse aber Raum für echte Momente. Die bearbeiteten Fotos werden innerhalb einer Woche geliefert.", es: "(Máx 6 personas) Nos encontramos en la playa, charlamos sobre sus deseos y comenzamos la sesión de forma relajada y natural. Le guío donde haga falta, dejando espacio para momentos reales. Las fotos editadas se entregan en una semana.", fr: "(Max 6 personnes) Nous nous retrouvons à la plage, parlons de vos envies, et commençons la séance de façon détendue et naturelle. Je vous guide quand nécessaire, en laissant place aux vrais moments. Les photos éditées sont livrées sous une semaine." } },
  { id: "e0a93e0d-e2e3-40cc-b634-32c98e4d1534",
    name: { pt: "Sessão de Retiro / Grupo", de: "Retreat-/Gruppen-Session", es: "Sesión de retiro / grupo", fr: "Séance Retraite / Groupe" },
    description: { pt: "Perfeito para um grupo de 6+ pessoas ou um pequeno evento, como um retiro. Encontramo-nos no local escolhido ou na praia e alinhamos o que querem captar. Durante a sessão de duas horas, documento momentos de grupo, interacções naturais e retratos individuais de forma descontraída e orgânica. As fotografias editadas são entregues numa semana.", de: "Perfekt für eine Gruppe von 6+ Personen oder ein kleines Event wie ein Retreat. Wir treffen uns am gewählten Ort oder am Strand und stimmen ab, was ihr festhalten wollt. Während der zweistündigen Session dokumentiere ich Gruppenmomente, natürliche Interaktionen und Einzelporträts auf entspannte, organische Weise. Die bearbeiteten Fotos werden innerhalb einer Woche geliefert.", es: "Perfecto para un grupo de 6+ personas o un pequeño evento como un retiro. Nos encontramos en el lugar elegido o en la playa y alineamos qué quieren captar. Durante la sesión de dos horas, documento momentos de grupo, interacciones naturales y retratos individuales de forma relajada y orgánica. Las fotos editadas se entregan en una semana.", fr: "Parfait pour un groupe de 6+ personnes ou un petit événement comme une retraite. Nous nous retrouvons à l'endroit choisi ou à la plage et alignons ce que vous voulez capturer. Pendant la séance de deux heures, je documente les moments de groupe, les interactions naturelles et des portraits individuels de manière détendue et organique. Les photos éditées sont livrées sous une semaine." } },
  { id: "4d570d39-478b-43bf-91c2-278c708caf7e",
    name: { pt: "Histórias-Lembrança", de: "Souvenir-Geschichten", es: "Historias-recuerdo", fr: "Histoires-souvenir" },
    description: { pt: "Sessão de 1 hora\n1 localização\n1 outfit\nFotografias entregues em galeria digital", de: "1-stündige Session\n1 Location\n1 Outfit\nFotos in digitaler Galerie geliefert", es: "Sesión de 1 hora\n1 localización\n1 outfit\nFotos entregadas en galería digital", fr: "Séance d'1 heure\n1 lieu\n1 tenue\nPhotos livrées en galerie numérique" } },
  { id: "d8414330-fe72-44af-b857-1ed4c1c93b05",
    name: { pt: "Postais da Sua Viagem", de: "Postkarten Ihrer Reise", es: "Postales de su viaje", fr: "Cartes postales de votre voyage" },
    description: { pt: "Sessão de 1,5 horas\n2 outfits\n1 localização\nFotografias entregues em galeria digital", de: "1,5-stündige Session\n2 Outfits\n1 Location\nFotos in digitaler Galerie geliefert", es: "Sesión de 1,5 horas\n2 outfits\n1 localización\nFotos entregadas en galería digital", fr: "Séance d'1h30\n2 tenues\n1 lieu\nPhotos livrées en galerie numérique" } },
  { id: "c3a1603c-7988-46c8-b754-4040c21958c5",
    name: { pt: "Colecção História Completa", de: "Vollständige Story-Kollektion", es: "Colección Historia Completa", fr: "Collection Histoire Complète" },
    description: { pt: "Sessão de 2 horas\n2 outfits\n2 localizações diferentes\nFotografias entregues em galeria digital", de: "2-stündige Session\n2 Outfits\n2 verschiedene Locations\nFotos in digitaler Galerie geliefert", es: "Sesión de 2 horas\n2 outfits\n2 localizaciones diferentes\nFotos entregadas en galería digital", fr: "Séance de 2 heures\n2 tenues\n2 lieux différents\nPhotos livrées en galerie numérique" } },
  { id: "c52262d7-f0c3-4c39-8a23-3888a66da946",
    name: { pt: "Sessão Curta — manhã", de: "Kurze Session — morgens", es: "Sesión corta — mañana", fr: "Séance courte — matin" },
    description: { pt: "Uma sessão rápida e intencional para casais que querem algumas imagens fortes e significativas em Lisboa.", de: "Eine schnelle, gezielte Session für Paare, die einige starke, bedeutungsvolle Bilder in Lissabon möchten.", es: "Una sesión rápida e intencional para parejas que quieren unas pocas imágenes fuertes y significativas en Lisboa.", fr: "Une séance rapide et intentionnelle pour les couples qui veulent quelques images fortes et porteuses de sens à Lisbonne." } },
  { id: "e860f31f-6468-4318-911c-eb0ecb46596d",
    name: { pt: "Sessão Signature — manhã", de: "Signature-Session — morgens", es: "Sesión Signature — mañana", fr: "Séance Signature — matin" },
    description: { pt: "Mesmo tempo, mais profundidade — ideal se quiserem uma galeria mais rica sem se comprometerem com uma sessão mais longa.", de: "Gleiche Zeit, mehr Tiefe — ideal, wenn ihr eine reichere Galerie wollt, ohne euch auf ein längeres Shooting festzulegen.", es: "Mismo tiempo, más profundidad — ideal si quieren una galería más rica sin comprometerse con una sesión más larga.", fr: "Même durée, plus de profondeur — idéal si vous voulez une galerie plus riche sans vous engager dans une séance plus longue." } },
  { id: "85526b6f-1756-4c04-b7b6-5c55def93d36",
    name: { pt: "Essência do Porto", de: "Porto-Essenz", es: "Esencia de Oporto", fr: "Essence de Porto" },
    description: { pt: "Uma introdução refinada e descontraída à sua experiência fotográfica no Porto.", de: "Eine raffinierte, mühelose Einführung in Ihr Porto-Foto-Erlebnis.", es: "Una introducción refinada y sin esfuerzo a su experiencia fotográfica en Oporto.", fr: "Une introduction raffinée et fluide à votre expérience photo à Porto." } },
  { id: "b7859cf7-9d36-4009-a98a-d85d6a05f76d",
    name: { pt: "The Porto Edit", de: "The Porto Edit", es: "The Porto Edit", fr: "The Porto Edit" },
    description: { pt: "Uma experiência fotográfica curada e elegante pelos cenários mais bonitos do Porto.", de: "Ein kuratiertes, elegantes Foto-Erlebnis durch Portos schönste Kulissen.", es: "Una experiencia fotográfica curada y elegante por los escenarios más bonitos de Oporto.", fr: "Une expérience photo soignée et élégante à travers les plus beaux décors de Porto." } },
  { id: "ee0c6b62-9840-4f73-8352-8c20d9a4643f",
    name: { pt: "Experiência Completa", de: "Vollständige Erfahrung", es: "Experiencia completa", fr: "Expérience Complète" },
    description: { pt: "Uma sessão completa de storytelling pela cidade, com tempo para explorar diferentes pontos e criar um conjunto de imagens mais cinematográfico. Fotografamos em locais icónicos como a Praça do Comércio e Graça (Alfama), com vistas panorâmicas sobre Lisboa.", de: "Eine vollständige Storytelling-Session durch die Stadt, mit Zeit, verschiedene Orte zu erkunden und einen filmischeren Bildersatz zu schaffen. Wir fotografieren an ikonischen Plätzen wie der Praça do Comércio und Graça (Alfama), mit Panoramablicken über Lissabon.", es: "Una sesión completa de storytelling por la ciudad, con tiempo para explorar distintos puntos y crear un conjunto de imágenes más cinematográfico. Fotografiamos en lugares icónicos como Praça do Comércio y Graça (Alfama), con vistas panorámicas sobre Lisboa.", fr: "Une séance storytelling complète à travers la ville, avec le temps d'explorer différents lieux et de créer un ensemble d'images plus cinématographique. Nous photographions dans des endroits emblématiques comme la Praça do Comércio et Graça (Alfama), avec des vues panoramiques sur Lisbonne." } },
  { id: "88e736c7-3b40-446b-8759-98df9aa8beb3",
    name: { pt: "Sessão de Praia no Algarve", de: "Strand-Fotoshooting in der Algarve", es: "Sesión de playa en el Algarve", fr: "Séance plage en Algarve" },
    description: { pt: "Capture os seus momentos especiais com uma sessão fotográfica na praia do Algarve, ao nascer ou pôr-do-sol. Perfeita para retratos, casais, famílias, maternidade ou pedidos de casamento. Máximo 5 pessoas.", de: "Halten Sie Ihre besonderen Momente bei einem Strand-Foto-Shooting in der Algarve fest — bei Sonnenaufgang oder Sonnenuntergang. Perfekt für Porträts, Paare, Familien, Schwangerschaft oder Heiratsanträge. Maximal 5 Personen.", es: "Capture sus momentos especiales con una sesión fotográfica en la playa del Algarve al amanecer o atardecer. Perfecta para retratos, parejas, familias, maternidad o pedidas. Máximo 5 personas.", fr: "Capturez vos moments spéciaux avec une séance photo à la plage en Algarve, au lever ou au coucher du soleil. Parfait pour portraits, couples, familles, maternité ou demandes en mariage. Maximum 5 personnes." } },
  { id: "06ba8482-9878-4897-a1e3-48eedeb13dbf",
    name: { pt: "Sessão Família Grande", de: "Großes Familien-Shooting", es: "Sesión de familia grande", fr: "Séance Grande Famille" },
    description: { pt: "Uma sessão fotográfica na praia com toda a família. Este pacote é para famílias com mais de 5 pessoas.", de: "Ein Foto-Shooting am Strand mit der ganzen Familie. Dieses Paket ist für Familien mit mehr als 5 Personen.", es: "Una sesión fotográfica en la playa con toda la familia. Este pack es para familias con más de 5 personas.", fr: "Une séance photo à la plage avec toute la famille. Ce pack est destiné aux familles de plus de 5 personnes." } },
  { id: "b6becf2b-61af-4864-9ce8-d13e9cf539f9",
    name: { pt: "Porto Bespoke", de: "Porto Bespoke", es: "Oporto Bespoke", fr: "Porto Bespoke" },
    description: { pt: "Uma experiência fotográfica totalmente personalizada e exclusiva, pensada para contar a sua história no Porto de forma atemporal e emocional.", de: "Ein vollständig personalisiertes und exklusives Foto-Erlebnis, das Ihre Porto-Geschichte zeitlos und emotional erzählen soll.", es: "Una experiencia fotográfica totalmente personalizada y exclusiva, pensada para contar su historia en Oporto de forma atemporal y emocional.", fr: "Une expérience photo entièrement personnalisée et exclusive, conçue pour raconter votre histoire à Porto de manière intemporelle et émotionnelle." } },
  { id: "aa7f1098-d1dc-4ad8-90f9-b40ac43f183c",
    name: { pt: "EXPRESS", de: "EXPRESS", es: "EXPRESS", fr: "EXPRESS" },
    description: { pt: "• criação de moodboard com base nos seus desejos\n• recomendações para escolha do outfit\n• apoio nas poses", de: "• Moodboard-Erstellung basierend auf Ihren Wünschen\n• Outfit-Empfehlungen\n• Unterstützung bei den Posen", es: "• creación de moodboard según sus deseos\n• recomendaciones para elegir el outfit\n• ayuda con las poses", fr: "• création d'un moodboard selon vos envies\n• conseils pour le choix de la tenue\n• aide pour les poses" } },
  { id: "c6999379-8b89-4020-8c87-c0703250068e",
    name: { pt: "Porto Cinematográfico e Você — Retratos Analógicos", de: "Cinematographic Porto und Sie — Analoge Porträts", es: "Oporto cinematográfico y usted — Retratos analógicos", fr: "Porto cinématographique et vous — Portraits argentiques" },
    description: { pt: "Esta sessão analógica é sobre você — a sua energia, a sua história, a sua presença no Porto. Vamos captá-lo(a) tal como é, num momento fugaz da sua viagem; retratos que parecem naturais, suaves e profundamente pessoais, graças à estética analógica.\n\nIdeal para: viajantes solo.\n\nVou fotografar tanto em filme como em digital, por segurança, porque o filme é imprevisível. O prazo de entrega depende da revelação no melhor laboratório de Portugal. Inclui-se um rolo de filme e despesas de revelação.", de: "Diese analoge Fotosession dreht sich um Sie — Ihre Energie, Ihre Geschichte, Ihre Präsenz in Porto. Wir halten Sie fest, wie Sie sind, in einem flüchtigen Moment Ihrer Reise: Porträts, die natürlich, weich und tief persönlich wirken — dank der analogen Ästhetik.\n\nIdeal für: Solo-Reisende.\n\nIch fotografiere sowohl analog als auch digital, zur Sicherheit, da Film unberechenbar ist. Die Lieferzeit hängt vom Entwicklungstempo des besten Labors in Portugal ab. Ein Filmrolle und Entwicklungskosten sind enthalten.", es: "Esta sesión analógica va sobre usted — su energía, su historia, su presencia en Oporto. Le capto tal y como es, en un instante fugaz de su viaje; retratos que se sienten naturales, suaves y profundamente personales gracias a la estética analógica.\n\nIdeal para: viajeros solos.\n\nFotografío tanto en analógico como en digital, por seguridad, porque el película es impredecible. El plazo de entrega depende del revelado en el mejor laboratorio de Portugal. Se incluye un rollo de película y los gastos de revelado.", fr: "Cette séance argentique parle de vous — votre énergie, votre histoire, votre présence à Porto. Je vous capture tel(le) que vous êtes, dans un instant fugace de votre voyage ; des portraits qui paraissent naturels, doux et profondément personnels grâce à l'esthétique argentique.\n\nIdéal pour : voyageurs solos.\n\nJe photographie en argentique et en numérique pour la sécurité, car la pellicule est imprévisible. Le délai de livraison dépend du temps de développement dans le meilleur laboratoire du Portugal. Une pellicule et les frais de développement sont inclus." } },
  { id: "f49d194d-6f5b-4e8c-9843-ac52ed51e757",
    name: { pt: "Sessão Fotográfica em Casa", de: "Fotoshooting zu Hause", es: "Sesión fotográfica en casa", fr: "Séance photo à la maison" },
    description: { pt: "Capture a vida das pessoas que ama numa atmosfera acolhedora.", de: "Halten Sie das Leben Ihrer Liebsten in einer einladenden Atmosphäre fest.", es: "Capture la vida de sus seres queridos en una atmósfera acogedora.", fr: "Capturez la vie de vos proches dans une atmosphère chaleureuse." } },
  { id: "5cd1cdf6-3673-4fda-8b3c-e7d11877c4ad",
    name: { pt: "Sessão Fotográfica na Praia", de: "Strand-Fotoshooting", es: "Sesión fotográfica en la playa", fr: "Séance photo à la plage" },
    description: { pt: "Fotografias com oceano, ondas e sol — para si ou para a sua família.", de: "Fotos mit Ozean, Wellen und Sonne — für Sie oder Ihre Familie.", es: "Fotos con océano, olas y sol — de usted o su familia.", fr: "Des photos avec océan, vagues et soleil — pour vous ou votre famille." } },
  { id: "e8fb193a-814a-4c30-b660-5584058af2d6",
    name: { pt: "Descobrir Lisboa", de: "Lissabon entdecken", es: "Descubrir Lisboa", fr: "Découvrir Lisbonne" },
    description: { pt: "Sessão fotográfica na zona histórica de Lisboa.", de: "Fotoshooting im historischen Teil Lissabons.", es: "Sesión fotográfica en la zona histórica de Lisboa.", fr: "Séance photo dans la partie historique de Lisbonne." } },
  { id: "3f3db23f-bbf0-43e6-bb3e-b423d5bd99f9",
    name: { pt: "Histórias de Amor no Porto — Sessão de Casal", de: "Porto Love Stories — Paar-Fotosession", es: "Historias de amor en Oporto — sesión de pareja", fr: "Porto Love Stories — séance couple" },
    description: { pt: "Seja num passeio pelo centro da cidade, a desfrutar do pôr-do-sol na praia, ou num pedido de casamento (enquanto eu fico escondida nos arbustos, claro), vou captar fotografias do(a) verdadeiro(a) você e das vossas emoções reais.\n\nIdeal para: aniversários, pedidos de casamento, luas-de-mel ou para celebrar o vosso tempo juntos.\n\nFotografo em filme e em digital, por segurança, porque o filme é imprevisível. O prazo de entrega depende da revelação no melhor laboratório de Portugal. Inclui-se um rolo de filme e despesas de revelação.", de: "Ob Spaziergang durchs Stadtzentrum, Sonnenuntergang am Strand oder Heiratsantrag (während ich mich natürlich in den Büschen verstecke) — ich halte Bilder von Ihrem wahren Ich und Ihren echten Emotionen fest.\n\nIdeal für: Jubiläen, Heiratsanträge, Hochzeitsreisen oder das gemeinsame Feiern eurer Zeit.\n\nIch fotografiere analog und digital, zur Sicherheit, da Film unberechenbar ist. Die Lieferzeit hängt vom Entwicklungstempo im besten Labor Portugals ab. Eine Filmrolle und Entwicklungskosten sind enthalten.", es: "Ya sea un paseo por el centro, disfrutar del atardecer en la playa o una pedida de mano (mientras yo me escondo entre los arbustos, por supuesto), captaré fotos de su verdadero(a) yo y de sus emociones reales.\n\nIdeal para: aniversarios, pedidas, lunas de miel o para celebrar su tiempo juntos.\n\nFotografío en analógico y en digital, por seguridad, porque la película es impredecible. El plazo de entrega depende del revelado en el mejor laboratorio de Portugal. Se incluye un rollo de película y los gastos de revelado.", fr: "Que ce soit une balade dans le centre-ville, profiter du coucher de soleil à la plage ou une demande en mariage (pendant que je me cache dans les buissons, bien sûr), je capte des photos du vrai vous et de vos émotions réelles.\n\nIdéal pour : anniversaires, demandes en mariage, lunes de miel ou la célébration de votre temps ensemble.\n\nJe photographie en argentique et en numérique pour la sécurité, car la pellicule est imprévisible. Le délai dépend du développement dans le meilleur laboratoire du Portugal. Une pellicule et les frais de développement sont inclus." } },
  { id: "06b8fef6-4c6b-4e58-b7fa-f13e3614cc92",
    name: { pt: "Sessão de Estúdio", de: "Studio-Session", es: "Sesión de estudio", fr: "Séance studio" },
    description: { pt: "A sessão inclui até 2 horas de tempo de fotografia e 2 mudanças de outfit para uma pessoa.\nUm fundo e uma luz instalada.\n\nEstúdio em Leiria.", de: "Die Session umfasst bis zu 2 Stunden Aufnahmezeit und 2 Outfit-Wechsel für eine Person.\nEin Hintergrund und ein Lichtsetup.\n\nStudio in Leiria.", es: "La sesión incluye hasta 2 horas de fotografía y 2 cambios de outfit para una persona.\nUn fondo y una iluminación montada.\n\nEstudio en Leiria.", fr: "La séance inclut jusqu'à 2 heures de prise de vue et 2 changements de tenue pour une personne.\nUn fond et un éclairage installé.\n\nStudio à Leiria." } },
  { id: "b00d3ce5-6524-44b3-aef8-3cc885791b20",
    name: { pt: "Feed Nostálgico — para Criadores de Conteúdo", de: "Nostalgischer Feed — für Content-Creator", es: "Feed nostálgico — para creadores de contenido", fr: "Feed nostalgique — pour créateurs de contenu" },
    description: { pt: "Para criadores que querem visuais editoriais com uma estética analógica distinta. Fotografado totalmente em filme, o seu feed parecerá nostálgico, suave e romântico sem esforço.\n\nPodemos também filmar um curto vídeo para Reels!\n\nIdeal para: influenciadores e marcas.\n\nFotografo em filme e em digital, por segurança. O prazo de entrega depende da revelação no melhor laboratório de Portugal. Inclui-se um rolo de filme e despesas de revelação.", de: "Für Creator, die editoriale Visuals mit einer markanten analogen Ästhetik möchten. Vollständig auf Film aufgenommen, fühlt sich Ihr Feed nostalgisch, weich und mühelos romantisch an.\n\nWir können auch ein kurzes Reels-Video drehen!\n\nIdeal für: Influencer und Marken.\n\nIch fotografiere analog und digital, zur Sicherheit. Die Lieferzeit hängt vom Entwicklungstempo im besten Labor Portugals ab. Eine Filmrolle und Entwicklungskosten sind enthalten.", es: "Para creadores que quieren visuales editoriales con una estética analógica única. Fotografiado totalmente en película, su feed se sentirá nostálgico, suave y romántico sin esfuerzo.\n\n¡También podemos grabar un breve vídeo para Reels!\n\nIdeal para: influencers y marcas.\n\nFotografío en analógico y en digital, por seguridad. El plazo de entrega depende del revelado en el mejor laboratorio de Portugal. Se incluye un rollo de película y gastos de revelado.", fr: "Pour les créateurs qui veulent des visuels éditoriaux avec une esthétique argentique distinctive. Entièrement tourné sur pellicule, votre feed paraîtra nostalgique, doux et romantique sans effort.\n\nNous pouvons aussi filmer une courte vidéo pour Reels !\n\nIdéal pour : influenceurs et marques.\n\nJe photographie en argentique et en numérique pour la sécurité. Le délai dépend du développement dans le meilleur laboratoire du Portugal. Une pellicule et les frais de développement sont inclus." } },
  { id: "5293e6a5-498f-4f4a-8464-23bd9bdfb46e",
    name: { pt: "Sessão em Localização", de: "Location-Shooting", es: "Sesión en localización", fr: "Séance en extérieur" },
    description: { pt: "• 2 mudanças de outfit\n• Inclui uma pessoa\n• Direcção e orientação profissional\n• Imagens em alta resolução cuidadosamente seleccionadas e editadas", de: "• 2 Outfit-Wechsel\n• Eine Person inklusive\n• Professionelle Anleitung und Direktion\n• Sorgfältig ausgewählte und bearbeitete Bilder in hoher Auflösung", es: "• 2 cambios de outfit\n• Incluye una persona\n• Dirección y guía profesional\n• Imágenes en alta resolución cuidadosamente seleccionadas y editadas", fr: "• 2 changements de tenue\n• Une personne incluse\n• Direction et accompagnement professionnels\n• Images haute résolution soigneusement sélectionnées et éditées" } },
  { id: "4da6a54d-e1fe-4a8e-bcb4-f210c30e0bb6",
    name: { pt: "BÁSICO", de: "BASIS", es: "BÁSICO", fr: "BASIQUE" },
    description: { pt: "• criação de moodboard com base nos seus desejos\n• recomendações para escolha do outfit\n• apoio nas poses\n• 50+ fotografias editadas\n• fotografias prontas em 7 dias numa galeria bonita", de: "• Moodboard-Erstellung basierend auf Ihren Wünschen\n• Outfit-Empfehlungen\n• Unterstützung bei den Posen\n• 50+ bearbeitete Fotos\n• Fertige Fotos nach 7 Tagen in einer schönen Galerie", es: "• creación de moodboard según sus deseos\n• recomendaciones para elegir el outfit\n• ayuda con las poses\n• 50+ fotos editadas\n• fotos listas en 7 días en una galería bonita", fr: "• création d'un moodboard selon vos envies\n• conseils pour le choix de la tenue\n• aide pour les poses\n• 50+ photos éditées\n• photos prêtes sous 7 jours dans une jolie galerie" } },
  { id: "ca1e7e5b-7a25-4a60-8762-d73ead2eab11",
    name: { pt: "CONFORTO", de: "COMFORT", es: "CONFORT", fr: "CONFORT" },
    description: { pt: "• criação de moodboard com base nos seus desejos\n• recomendações para escolha do outfit\n• apoio nas poses\n• fotografias prontas em 7 dias numa galeria bonita\n\n+como prenda: vídeo-reels grátis", de: "• Moodboard-Erstellung basierend auf Ihren Wünschen\n• Outfit-Empfehlungen\n• Unterstützung bei den Posen\n• Fertige Fotos nach 7 Tagen in einer schönen Galerie\n\n+als Geschenk: kostenloses Video-Reels", es: "• creación de moodboard según sus deseos\n• recomendaciones para elegir el outfit\n• ayuda con las poses\n• fotos listas en 7 días en una galería bonita\n\n+de regalo: vídeo-reels gratis", fr: "• création d'un moodboard selon vos envies\n• conseils pour le choix de la tenue\n• aide pour les poses\n• photos prêtes sous 7 jours dans une jolie galerie\n\n+en cadeau : vidéo-reels offerte" } },
];

for (const p of PKG) {
  const cols = []; const params = [];
  for (const loc of ["pt","de","es","fr"]) {
    if (p.name?.[loc]) { cols.push(`name_${loc} = $${params.length+1}`); params.push(p.name[loc]); }
    if (p.description?.[loc]) { cols.push(`description_${loc} = $${params.length+1}`); params.push(p.description[loc]); }
  }
  if (cols.length === 0) {
    await client.query(`UPDATE packages SET translations_dirty = FALSE, translations_updated_at = NOW() WHERE id = $1`, [p.id]);
    console.log(`✓ ${p.id.slice(0,8)} (empty)`);
    continue;
  }
  cols.push(`translations_updated_at = NOW()`, `translations_dirty = FALSE`);
  params.push(p.id);
  await client.query(`UPDATE packages SET ${cols.join(", ")} WHERE id = $${params.length}`, params);
  console.log(`✓ ${p.id.slice(0,8)} ${p.name.fr || ""}`);
}
await client.end();
console.log(`\nBatch pkg-4 done — ${PKG.length} packages translated. Total: 115/115 packages from approved photographers complete.`);
