// Package batch 3 — 25 more packages (Denis, Maria, Patricia, Jennifer, Goncalo, Aleksandra, Monica, Kristina, David, Andre)
import pg from "pg";
import { readFileSync } from "fs";
const env = Object.fromEntries(readFileSync("/var/www/photoportugal/.env","utf-8").split("\n").filter((l)=>l&&l.includes("=")&&!l.startsWith("#")).map((l)=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim().replace(/^["']|["']$/g,"")]}));
const client = new pg.Client({ connectionString: env.DATABASE_URL });
await client.connect();

const PKG = [
  { id: "d914d666-6c3e-4c0a-9f11-f859dd002b1a",
    name: { pt: "Entrega no próprio dia", de: "Lieferung am selben Tag", es: "Entrega en el mismo día", fr: "Livraison le jour même" },
    description: { pt: "Sessão expressa, entrega expressa :-)", de: "Express-Session, Express-Lieferung :-)", es: "Sesión exprés, entrega exprés :-)", fr: "Séance express, livraison express :-)" } },
  { id: "d804b8aa-2f2b-48cc-9d19-43c6d5c68271",
    name: { pt: "Alma Atlântica", de: "Atlantische Seele", es: "Alma Atlántica", fr: "Âme Atlantique" },
    description: { pt: "Viva a beleza crua da costa atlântica. Isto é mais do que uma sessão fotográfica — é um momento de absoluta liberdade onde as falésias encontram o azul infinito.\nQuer seja o vento dramático do Cabo da Roca, as areias douradas de Cascais, ou as ondas selvagens da Praia da Adraga, vamos captar a sua história entre os elementos. Do ar salgado no cabelo ao reflexo dourado do sol na água.", de: "Erleben Sie die rohe Schönheit der Atlantikküste. Das ist mehr als ein Fotoshooting — ein Moment absoluter Freiheit, in dem die Klippen auf das endlose Blau treffen.\nOb der dramatische Wind am Cabo da Roca, der goldene Sand von Cascais oder die wilden Wellen der Praia da Adraga — wir halten Ihre Geschichte zwischen den Elementen fest. Von der salzigen Luft im Haar bis zur goldenen Spiegelung der Sonne im Wasser.", es: "Viva la belleza cruda de la costa atlántica. Esto es más que una sesión — es un momento de absoluta libertad donde los acantilados se encuentran con el azul infinito.\nYa sea el viento dramático de Cabo da Roca, las arenas doradas de Cascais o las olas salvajes de Praia da Adraga, captaremos su historia entre los elementos. Del aire salado en el pelo al reflejo dorado del sol en el agua.", fr: "Vivez la beauté brute de la côte atlantique. Plus qu'une séance photo — un moment de liberté absolue où les falaises rencontrent le bleu infini.\nQue ce soit le vent dramatique du Cabo da Roca, les sables dorés de Cascais ou les vagues sauvages de la Praia da Adraga, nous capturons votre histoire au cœur des éléments. De l'air salé dans les cheveux au reflet doré du soleil sur l'eau." } },
  { id: "7b713bc2-5212-478e-af39-92aa31e91ab4",
    name: { pt: "Sessão perfeita para casais", de: "Perfekte Paar-Session", es: "Sesión perfecta para parejas", fr: "Séance parfaite pour couples" },
    description: { pt: "Olá, pombinhos! Que sorte termos a oportunidade de captar o vosso amor aqui em Portugal. Posso guiar-vos com poses se quiserem, mas se preferirem algo 100% natural e espontâneo, também funciona perfeitamente.", de: "Hallo, Turteltäubchen! Was für ein Glück, eure Liebe hier in Portugal festzuhalten. Ich kann euch durch Posen führen, wenn ihr möchtet, aber wenn ihr lieber etwas 100% Natürliches und Spontanes wollt, funktioniert das ebenfalls perfekt.", es: "¡Hola, tortolitos! Qué suerte poder captar su amor aquí en Portugal. Puedo guiarlos con poses si quieren, pero si prefieren algo 100% natural y espontáneo, también funciona perfectamente.", fr: "Bonjour, tourtereaux ! Quelle chance de pouvoir capturer votre amour ici au Portugal. Je peux vous guider dans les poses si vous voulez, mais si vous préférez quelque chose de 100% naturel et spontané, cela fonctionne parfaitement aussi." } },
  { id: "000312fc-1bef-420c-adce-232ce07c3b96",
    name: { pt: "DOIS CORAÇÕES (História de amor cinematográfica)", de: "ZWEI HERZEN (Filmische Liebesgeschichte)", es: "DOS CORAZONES (Historia de amor cinematográfica)", fr: "DEUX CŒURS (Histoire d'amour cinématographique)" },
    description: { pt: "Um filme sobre vocês os dois. A vossa história de amor, contada através de uma lente cinematográfica. Seja entre a alma histórica de Lisboa ou a força crua do Atlântico, criamos imagens que parecem cenas de filme. Planos cinematográficos dos vossos melhores momentos. Para recordar para sempre. Emoções reais, estilo atemporal.", de: "Ein Film über euch beide. Eure Liebesgeschichte, erzählt durch eine filmische Linse. Ob zwischen der historischen Seele Lissabons oder der rohen Kraft des Atlantiks — wir schaffen Bilder, die sich wie Filmszenen anfühlen. Cinematische Aufnahmen eurer schönsten Momente. Für immer in Erinnerung. Echte Emotionen, zeitloser Stil.", es: "Una película sobre los dos. Su historia de amor, contada a través de una lente cinematográfica. Ya sea entre el alma histórica de Lisboa o la fuerza cruda del Atlántico, creamos imágenes que parecen escenas de película. Planos cinematográficos de sus mejores momentos. Para recordar para siempre. Emociones reales, estilo atemporal.", fr: "Un film sur vous deux. Votre histoire d'amour, racontée à travers un objectif cinématographique. Que ce soit dans l'âme historique de Lisbonne ou la puissance brute de l'Atlantique, nous créons des images qui ressemblent à des scènes de film. Des plans cinématographiques de vos plus beaux instants. Pour se souvenir à jamais. Émotions réelles, style intemporel." } },
  { id: "db9ceabc-ac18-43fa-bf66-d86101f81c8e",
    name: { pt: "O CAPÍTULO PORTUGAL", de: "DAS PORTUGAL-KAPITEL", es: "EL CAPÍTULO PORTUGAL", fr: "LE CHAPITRE PORTUGAL" },
    description: { pt: "Uma bela história da vossa família em Portugal. Podemos passear pelas ruas soalheiras de Lisboa ou desfrutar do pôr-do-sol junto ao oceano.\nO meu objectivo é captar momentos reais: os sorrisos das crianças, abraços calorosos e a alegria de estarem juntos. Sem poses stressantes ou sorrisos forçados — apenas vocês e quem amam, com luz cinematográfica linda. São as memórias que vão guardar para sempre.\n(Inclui até 5 pessoas. Disponível na cidade ou na costa.)", de: "Eine schöne Geschichte Ihrer Familie in Portugal. Wir können durch die sonnigen Straßen Lissabons spazieren oder den Sonnenuntergang am Ozean genießen.\nMein Ziel ist es, echte Momente festzuhalten: das Lachen der Kinder, herzliche Umarmungen und die Freude des Zusammenseins. Kein stressiges Posieren, kein gespieltes Lächeln — nur Sie und Ihre Lieben in wunderschönem filmischem Licht. Erinnerungen, die für immer bleiben.\n(Bis zu 5 Personen. Verfügbar in der Stadt oder an der Küste.)", es: "Una bonita historia de su familia en Portugal. Podemos pasear por las calles soleadas de Lisboa o disfrutar del atardecer junto al océano.\nMi objetivo es captar momentos reales: las sonrisas de los niños, los abrazos cálidos y la alegría de estar juntos. Sin poses estresantes ni sonrisas forzadas — solo ustedes y los suyos en una hermosa luz cinematográfica. Son los recuerdos que guardarán para siempre.\n(Incluye hasta 5 personas. Disponible en la ciudad o en la costa.)", fr: "Une belle histoire de votre famille au Portugal. Nous pouvons marcher dans les rues ensoleillées de Lisbonne ou profiter du coucher de soleil près de l'océan.\nMon objectif : capter les vrais moments — les sourires des enfants, les étreintes chaleureuses, la joie d'être ensemble. Pas de poses stressantes ni de sourires forcés — juste vous et ceux que vous aimez, dans une belle lumière cinématographique. Ce sont les souvenirs que vous garderez à jamais.\n(Jusqu'à 5 personnes. Disponible en ville ou sur la côte.)" } },
  { id: "d6317970-abb8-467a-8d8c-d7f95b04b827",
    name: { pt: "Sessão personalizada para criadores de conteúdo", de: "Personalisierte Session für Content-Creator", es: "Sesión personalizada para creadores de contenido", fr: "Séance sur mesure pour créateurs de contenu" },
    description: { pt: "É criador(a) de conteúdo? Posso ajudar. Conversamos antes da sessão para garantir que estamos alinhados, e juntos entregamos uma sessão totalmente à medida que combina perfeitamente com a sua visão.", de: "Sind Sie Content-Creator? Ich kann helfen. Wir sprechen vor der Session, damit wir auf einer Linie sind — und liefern gemeinsam ein vollständig auf Sie zugeschnittenes Shooting, das perfekt zu Ihrer Vision passt.", es: "¿Es creador(a) de contenido? Puedo ayudarle. Charlamos antes de la sesión para alinearnos, y juntos entregamos una sesión totalmente a medida que encaja perfectamente con su visión.", fr: "Vous êtes créateur(rice) de contenu ? Je peux aider. On échange avant la séance pour être alignés, puis ensemble nous livrons une séance entièrement sur mesure parfaitement adaptée à votre vision." } },
  { id: "0dc62b29-b413-441a-bc28-cebf1aff6c69",
    name: { pt: "Casamento", de: "Hochzeit", es: "Boda", fr: "Mariage" },
    description: { pt: "De todas as disciplinas da fotografia, captar um casamento é a que mais me toca. É uma enorme responsabilidade, e levo-a muito a sério. Farei tudo para entregar imagens autênticas que verdadeiramente contem a história do vosso dia. Confiem-me as vossas memórias.", de: "Von allen Bereichen der Fotografie steht das Festhalten einer Hochzeit meinem Herzen am nächsten. Es ist eine enorme Verantwortung, die ich sehr ernst nehme. Ich werde alles tun, um authentische Bilder zu liefern, die die Geschichte Ihres Tages wirklich erzählen. Vertrauen Sie mir Ihre Erinnerungen an.", es: "De todas las disciplinas de la fotografía, capturar una boda es la que más me llega al corazón. Es una enorme responsabilidad y la asumo muy en serio. Haré todo lo posible por entregar imágenes auténticas que cuenten de verdad la historia de su día. Confíenme sus recuerdos.", fr: "De toutes les disciplines de la photographie, capturer un mariage est celle qui me tient le plus à cœur. C'est une immense responsabilité, que je prends très au sérieux. Je ferai tout pour livrer des images authentiques qui racontent vraiment l'histoire de votre journée. Confiez-moi vos souvenirs." } },
  { id: "b5b18f24-60cb-4b19-93a3-d5be22979fe5",
    name: { pt: "Experiência Romântica Imersiva", de: "Immersive romantische Erfahrung", es: "Experiencia romántica inmersiva", fr: "Expérience romantique immersive" },
    description: { pt: "A experiência perfeita para o casal exigente que procura profundidade e conexão.\n\nIsto não é uma sessão fotográfica normal. Pense nisto como: parte encontro intencional, parte ritual de casal, totalmente focado em VÓS — não em \"performar\" para a câmara. As fotografias deslumbrantes? São a bonita evidência de uma experiência que realmente significou algo.", de: "Die perfekte Erfahrung für anspruchsvolle Paare, die Tiefe und Verbindung suchen.\n\nDas ist kein gewöhnliches Fotoshooting. Stellen Sie es sich so vor: teils bewusste Verabredung, teils Paar-Ritual, ganz auf EUCH ausgerichtet — nicht darauf, vor der Kamera \"zu performen\". Die wunderschönen Fotos? Sie sind der schöne Beweis einer Erfahrung, die wirklich Bedeutung hatte.", es: "La experiencia perfecta para la pareja exigente que busca profundidad y conexión.\n\nEsto no es una sesión fotográfica normal. Piénselo así: parte cita intencional, parte ritual de pareja, totalmente centrada en USTEDES — no en \"actuar\" para la cámara. ¿Las fotos espectaculares? Son la bella prueba de una experiencia que verdaderamente importó.", fr: "L'expérience parfaite pour le couple exigeant qui recherche profondeur et connexion.\n\nCe n'est pas une séance photo classique. Imaginez-la comme : en partie un rendez-vous intentionnel, en partie un rituel de couple, entièrement centrée sur VOUS — pas sur le fait de \"jouer un rôle\" devant l'objectif. Les magnifiques photos ? Ce sont la belle preuve d'une expérience qui a vraiment compté." } },
  { id: "e1b2c8fe-4641-48d6-9715-4cb2f1a21cd2",
    name: { pt: "Básico", de: "Basis", es: "Básico", fr: "Basique" },
    description: { pt: null, de: null, es: null, fr: null } },
  { id: "f4492736-ac04-4959-8359-3ac7d3e5c499",
    name: { pt: "Premium", de: "Premium", es: "Premium", fr: "Premium" },
    description: { pt: "Galeria completa", de: "Vollständige Galerie", es: "Galería completa", fr: "Galerie complète" } },
  { id: "6fe580f7-0e11-4a8a-99f7-28de709e9fcc",
    name: { pt: "Casamento Elopement", de: "Elopement-Hochzeit", es: "Boda Elopement", fr: "Mariage Elopement" },
    description: { pt: "Vai casar em Portugal com o seu amor e procura um fotógrafo de casamento para um elopement? Aqui apresento o meu pacote standard. Se precisar de mais alguma coisa que não encontre aqui, sinta-se à vontade para enviar uma mensagem.", de: "Sie heiraten Ihren geliebten Menschen in Portugal und suchen einen Hochzeitsfotografen für ein Elopement? Hier ist mein Standard-Paket. Wenn Sie etwas brauchen, das hier nicht aufgeführt ist, schreiben Sie mir gerne.", es: "¿Se va a casar en Portugal con su amor y busca un fotógrafo de bodas para un elopement? Aquí le presento mi pack estándar. Si necesita algo más que no encuentre aquí, escríbame sin problema.", fr: "Vous vous mariez au Portugal avec votre amour et cherchez un photographe pour un elopement ? Voici mon pack standard. Si vous avez besoin d'autre chose qui n'est pas ici, écrivez-moi sans hésiter." } },
  { id: "feae6190-07a2-4405-96b6-6f13309ef704",
    name: { pt: "Mini Sessão de Casal", de: "Mini-Paar-Session", es: "Mini Sesión de Pareja", fr: "Mini Séance Couple" },
    description: { pt: "Uma sessão fotográfica sofisticada e cuidadosamente planeada, num local escolhido pelo casal.", de: "Ein anspruchsvolles, sorgfältig geplantes Fotoshooting an einem vom Paar gewählten Ort.", es: "Una sesión fotográfica sofisticada y cuidadosamente planificada, en un lugar elegido por la pareja.", fr: "Une séance photo soignée et minutieusement planifiée, dans un lieu choisi par le couple." } },
  { id: "71df5bcd-c63e-44a0-9d0f-e74dd9925ebd",
    name: { pt: "Sessão de Casal", de: "Paar-Session", es: "Sesión de Pareja", fr: "Séance Couple" },
    description: { pt: "Uma experiência fotográfica refinada e cuidadosamente preparada, com os cenários mais espectaculares do Porto como pano de fundo.", de: "Ein raffiniertes, durchdacht gestaltetes Foto-Erlebnis vor den spektakulärsten Kulissen Portos.", es: "Una experiencia fotográfica refinada y cuidadosamente preparada, con los escenarios más espectaculares de Oporto como telón de fondo.", fr: "Une expérience photo raffinée et minutieusement préparée, avec les décors les plus spectaculaires de Porto en toile de fond." } },
  { id: "ebabb078-b628-4e36-bc3e-3c1019b3fc6c",
    name: { pt: "Essência de Lisboa", de: "Essenz von Lissabon", es: "Esencia de Lisboa", fr: "Essence de Lisbonne" },
    description: { pt: "Uma sessão curta de 15 minutos nos charmosos miradouros de Alfama. Receba 7 fotografias bonitas como recordação duradoura da magia de Lisboa.", de: "Eine kurze 15-minütige Session an Alfamas charmanten Aussichtspunkten. Erhalten Sie 7 wunderschöne Fotos als bleibende Erinnerung an die Magie Lissabons.", es: "Una sesión corta de 15 minutos en los encantadores miradores de Alfama. Reciba 7 fotos preciosas como recuerdo duradero de la magia de Lisboa.", fr: "Une courte séance de 15 minutes aux miradouros pleins de charme d'Alfama. Recevez 7 belles photos en souvenir durable de la magie de Lisbonne." } },
  { id: "c1d95437-64b5-406c-ab08-a3aebe46572e",
    name: { pt: "Momentos em Lisboa", de: "Momente in Lissabon", es: "Momentos en Lisboa", fr: "Moments à Lisbonne" },
    description: { pt: "Um passeio de 1 hora pelas ruas de Alfama, cantos escondidos e miradouros. Receba 20 fotografias editadas que captam momentos candid e autênticos e a essência da cidade.", de: "Ein einstündiger Spaziergang durch Alfamas Straßen, versteckte Ecken und Aussichtspunkte. Erhalten Sie 20 bearbeitete Fotos, die ungestellte, authentische Momente und das Wesen der Stadt einfangen.", es: "Un paseo de 1 hora por las calles de Alfama, rincones escondidos y miradores. Reciba 20 fotos editadas que captan momentos candid y auténticos y la esencia de la ciudad.", fr: "Une balade d'1 heure dans les rues d'Alfama, ses coins cachés et ses miradouros. Recevez 20 photos éditées qui capturent des moments spontanés, authentiques et l'essence de la ville." } },
  { id: "2930eef4-71e2-4b7e-b03b-12c65eac5a58",
    name: { pt: "Sessão de Praia ao Pôr-do-Sol", de: "Strand-Session zum Sonnenuntergang", es: "Sesión de playa al atardecer", fr: "Séance plage au coucher du soleil" },
    description: { pt: "Sessão íntima de 1 hora na praia, focada em retratos românticos e sensuais. Ideal para casais, mas também óptima para famílias e sessões individuais que queiram fotografias oníricas e inesquecíveis junto ao mar.", de: "Einstündige intime Strand-Session, fokussiert auf romantische und sinnliche Porträts. Ideal für Paare, aber auch wunderbar für Familien und Solo-Sessions, die traumhafte, unvergessliche Bilder am Meer wünschen.", es: "Sesión íntima de 1 hora en la playa, centrada en retratos románticos y sensuales. Ideal para parejas, pero también estupenda para familias y sesiones individuales que quieran fotos oníricas e inolvidables junto al mar.", fr: "Séance intime d'1 heure à la plage, centrée sur des portraits romantiques et sensuels. Idéale pour les couples, mais aussi parfaite pour les familles et les séances solos en quête de photos oniriques et inoubliables au bord de la mer." } },
  { id: "60c3e9bd-6ff3-4868-befa-ee1088de879a",
    name: { pt: "O Pedido", de: "Der Antrag", es: "La Pedida", fr: "La Demande" },
    description: { pt: "Uma sessão de pedido de casamento discreta e emocional, captando um dos \"sins\" mais importantes da sua vida. Estarei em segundo plano, a documentar cada emoção real — a antecipação, a surpresa e a alegria que se segue. Natural, candid e cheia de sentimento, criando memórias atemporais que nunca vai esquecer. A sessão inclui fotografia e vídeo para captar plenamente o momento à medida que se desenrola.", de: "Eine diskrete, emotionale Antragssession, die einen der wichtigsten „Ja\"-Momente Ihres Lebens festhält. Ich bleibe im Hintergrund und dokumentiere jede echte Emotion — die Vorfreude, die Überraschung und die anschließende Freude. Natürlich, candid und voller Gefühl — zeitlose Erinnerungen, die Sie nie vergessen werden. Die Session umfasst Foto und Video, um den Moment vollständig festzuhalten.", es: "Una sesión de pedida de mano discreta y emocional, capturando uno de los \"sí\" más importantes de su vida. Estaré en segundo plano documentando cada emoción real — la anticipación, la sorpresa y la alegría que sigue. Natural, candid y llena de sentimiento, creando recuerdos atemporales que nunca olvidará. La sesión incluye fotografía y vídeo para captar plenamente el momento mientras se desarrolla.", fr: "Une séance de demande discrète et émotionnelle, capturant l'un des \"oui\" les plus importants de votre vie. Je serai en retrait, documentant chaque émotion réelle — l'attente, la surprise et la joie qui suit. Naturelle, spontanée et pleine de sentiment, pour des souvenirs intemporels que vous n'oublierez jamais. La séance inclut photo et vidéo pour capturer pleinement l'instant à mesure qu'il se déroule." } },
  { id: "1245ea42-4b4a-401a-8d42-87f5ae881c90",
    name: { pt: "Histórias de Lisboa", de: "Lissabon-Geschichten", es: "Historias de Lisboa", fr: "Histoires de Lisbonne" },
    description: { pt: "1,5 horas a explorar Alfama → centro de Lisboa → Praça do Comércio. Receba 35 fotografias editadas, criando memórias para guardar para sempre.", de: "1,5 Stunden Erkundung von Alfama → Lissabon-Zentrum → Praça do Comércio. Erhalten Sie 35 bearbeitete Fotos und Erinnerungen, die für immer bleiben.", es: "1,5 horas explorando Alfama → centro de Lisboa → Praça do Comércio. Reciba 35 fotos editadas, creando recuerdos que atesorará para siempre.", fr: "1h30 à explorer Alfama → centre de Lisbonne → Praça do Comércio. Recevez 35 photos éditées, des souvenirs que vous chérirez pour toujours." } },
  { id: "c906e582-291e-41d7-91d1-43e051c3800d",
    name: { pt: "Momentos Autênticos", de: "Authentische Momente", es: "Momentos auténticos", fr: "Moments authentiques" },
    description: { pt: "Uma sessão de 90 minutos em estilo documental que capta a vossa história à medida que se desenrola naturalmente — sem poses rígidas, apenas momentos reais e emoções autênticas.\nPerfeita para maternidade, família e casais.", de: "Eine 90-minütige Session im Dokumentarstil, die Ihre Geschichte einfängt, wie sie sich natürlich entfaltet — keine steifen Posen, nur echte Momente und authentische Emotionen.\nPerfekt für Schwangerschaft, Familie und Paare.", es: "Una sesión de 90 minutos en estilo documental que capta su historia tal como se desarrolla naturalmente — sin poses rígidas, solo momentos reales y emociones auténticas.\nPerfecta para maternidad, familia y parejas.", fr: "Une séance de 90 minutes en style documentaire qui capte votre histoire telle qu'elle se déroule naturellement — pas de poses figées, juste des moments réels et des émotions authentiques.\nParfait pour la maternité, la famille et les couples." } },
  { id: "9ecf78b1-b3f7-4b66-be3c-4fb2cdda4b30",
    name: { pt: "Experiência História Completa", de: "Komplette Story-Erfahrung", es: "Experiencia Historia Completa", fr: "Expérience Histoire Complète" },
    description: { pt: "Uma sessão alargada de 2 horas que combina fotografia documental e vídeo curto para contar a vossa história de uma forma mais profunda e completa.\nIdeal para quem quer reviver não só as imagens, mas também os sons, movimentos e a sensação do momento.", de: "Eine erweiterte 2-stündige Session, die dokumentarische Fotografie und kurze Videos kombiniert, um Ihre Geschichte tiefer und vollständiger zu erzählen.\nIdeal für alle, die nicht nur die Bilder, sondern auch die Geräusche, Bewegungen und das Gefühl des Moments noch einmal erleben wollen.", es: "Una sesión ampliada de 2 horas que combina fotografía documental y vídeo corto para contar su historia de una forma más profunda y completa.\nIdeal para quienes quieren revivir no solo las imágenes, sino también los sonidos, movimientos y la sensación del momento.", fr: "Une séance prolongée de 2 heures qui combine photographie documentaire et courte vidéo pour raconter votre histoire de manière plus profonde et complète.\nIdéal pour celles et ceux qui veulent revivre non seulement les images, mais aussi les sons, les mouvements et le ressenti de l'instant." } },
  { id: "ec206c2d-c277-403d-a118-58cff9e79be1",
    name: { pt: "Retratos Rápidos no Porto", de: "Schnelle Porto-Porträts", es: "Retratos rápidos en Oporto", fr: "Portraits rapides à Porto" },
    description: { pt: "Uma sessão descontraída de 45 minutos para viajantes solo ou casais, num dos locais icónicos do Porto — uma forma simples de captar o seu tempo na cidade.\n\nFunciona também muito bem para famílias com crianças pequenas, mantendo tudo fácil e confortável.\n\nVai receber uma selecção curada de pelo menos 30 imagens editadas, entregues numa galeria privada online em 7 dias.", de: "Eine entspannte 45-minütige Session für Solo-Reisende oder Paare, an einem ikonischen Ort in Porto — eine einfache Art, Ihre Zeit in der Stadt festzuhalten.\n\nFunktioniert auch gut für Familien mit kleinen Kindern, locker und angenehm.\n\nSie erhalten eine kuratierte Auswahl von mindestens 30 bearbeiteten Bildern in einer privaten Online-Galerie innerhalb von 7 Tagen.", es: "Una sesión relajada de 45 minutos para viajeros solos o parejas, en uno de los lugares icónicos de Oporto — una forma sencilla de captar su tiempo en la ciudad.\n\nTambién funciona muy bien para familias con niños pequeños, manteniéndolo todo fácil y cómodo.\n\nRecibirá una selección curada de al menos 30 imágenes editadas, entregadas en una galería privada online en 7 días.", fr: "Une séance détendue de 45 minutes pour voyageurs solos ou couples, dans l'un des lieux emblématiques de Porto — une façon simple de capter votre temps dans la ville.\n\nFonctionne aussi très bien pour les familles avec jeunes enfants, en gardant tout simple et confortable.\n\nVous recevrez une sélection soignée d'au moins 30 images éditées, livrées dans une galerie privée en ligne sous 7 jours." } },
  { id: "d2cd7bcd-b123-4410-8c4c-6bfdedf5461d",
    name: { pt: "Photo Walk pelos Pontos Altos do Porto", de: "Porto Highlights Foto-Spaziergang", es: "Photo Walk por los puntos icónicos de Oporto", fr: "Photo-balade dans les incontournables de Porto" },
    description: { pt: "Neste passeio fotográfico vamos explorar alguns dos pontos mais icónicos do Porto — da Igreja do Carmo coberta de azulejos, passando pela Torre dos Clérigos e Estação de São Bento, até à Ribeira e à Ponte D. Luís I.\n\nPelo caminho, capto discretamente os vossos momentos à medida que acontecem.\n\nReceberá uma galeria curada de pelo menos 60 imagens editadas em 7 dias.\nO passeio cobre cerca de 3 km com algumas pequenas subidas — calçado confortável é uma boa ideia.", de: "Auf diesem Foto-Spaziergang erkunden wir einige der ikonischsten Orte Portos — von der azulejo-bedeckten Igreja do Carmo über den Clérigos-Turm und den Bahnhof São Bento bis hinunter zur Ribeira und zur Brücke Dom Luís I.\n\nUnterwegs halte ich diskret eure Momente fest, wie sie geschehen.\n\nIhr erhaltet eine kuratierte Galerie von mindestens 60 bearbeiteten Bildern innerhalb von 7 Tagen.\nDer Spaziergang umfasst etwa 3 km mit einigen sanften Anstiegen — bequeme Schuhe sind eine gute Idee.", es: "En este photo walk exploramos algunos de los puntos más icónicos de Oporto — desde la Igreja do Carmo cubierta de azulejos, pasando por la Torre de los Clérigos y la estación de São Bento, hasta la Ribeira y el puente Dom Luís I.\n\nPor el camino, capto sus momentos discretamente a medida que ocurren.\n\nRecibirá una galería curada de al menos 60 imágenes editadas en 7 días.\nEl paseo cubre unos 3 km con algunas subidas suaves — calzado cómodo es buena idea.", fr: "Lors de cette photo-balade, nous explorons certains des lieux les plus emblématiques de Porto — de l'Igreja do Carmo recouverte d'azulejos, en passant par la Tour des Clérigos et la gare de São Bento, jusqu'à la Ribeira et le pont Dom Luís I.\n\nEn chemin, je capte discrètement vos moments tels qu'ils se présentent.\n\nVous recevrez une galerie soignée d'au moins 60 images éditées sous 7 jours.\nLa balade fait environ 3 km avec quelques montées douces — des chaussures confortables sont conseillées." } },
  { id: "c4cf0dac-ad9b-4502-89f6-97a8f8076f30",
    name: { pt: "O Seu Dia no Porto", de: "Ihr Tag in Porto", es: "Su día en Oporto", fr: "Votre journée à Porto" },
    description: { pt: "Uma sessão em estilo documental que capta o seu tempo no Porto à medida que se desenrola, suavemente.\nMovo-me convosco pela cidade, preservando a atmosfera, as emoções e os momentos entre os momentos que tornam tudo seu.\n\nReceberá uma galeria curada de pelo menos 100 imagens editadas, entregues em 14 dias após a sessão.\nPodem acrescentar-se horas extra; eventuais bilhetes de museus ou atracções precisam de ser cobertos se necessário.", de: "Eine Session im Dokumentarstil, die Ihre Zeit in Porto sanft einfängt, wie sie sich entfaltet.\nIch bewege mich mit Ihnen durch die Stadt und bewahre Atmosphäre, Emotionen und die Zwischenmomente, die Ihre Reise einzigartig machen.\n\nSie erhalten eine kuratierte Galerie von mindestens 100 bearbeiteten Bildern innerhalb von 14 Tagen nach der Session.\nZusätzliche Stunden buchbar; eventuelle Eintritte für Museen oder Attraktionen wären gegebenenfalls separat zu bezahlen.", es: "Una sesión en estilo documental que capta su tiempo en Oporto tal como se desarrolla, con suavidad.\nMe muevo con usted por la ciudad, preservando la atmósfera, las emociones y los momentos entre momentos que lo hacen suyo.\n\nRecibirá una galería curada de al menos 100 imágenes editadas, entregadas en 14 días tras la sesión.\nPueden añadirse horas extra; las entradas a museos o atracciones, si se requieren, correrían por su cuenta.", fr: "Une séance en style documentaire qui capte votre temps à Porto à mesure qu'il se déroule, en douceur.\nJe me déplace avec vous dans la ville, en préservant l'atmosphère, les émotions et les moments entre les moments qui rendent l'expérience unique.\n\nVous recevrez une galerie soignée d'au moins 100 images éditées, livrées sous 14 jours après la séance.\nDes heures supplémentaires peuvent être ajoutées ; les billets éventuels de musées ou d'attractions seraient à votre charge si nécessaires." } },
  { id: "f3292428-cefd-4422-a295-0aaf8658c143",
    name: { pt: "Carrasqueira", de: "Carrasqueira", es: "Carrasqueira", fr: "Carrasqueira" },
    description: { pt: "Descubra uma experiência fotográfica única no icónico Cais Palafítico da Carrasqueira, um dos pontões de madeira mais atmosféricos de Portugal. Rodeado pelas águas calmas e pela beleza crua do estuário do Sado, este recanto escondido oferece um cenário cinematográfico atemporal. Perfeito para casais, famílias ou retratos que procurem imagens autênticas e artísticas numa paisagem costeira rústica e verdadeiramente inesquecível.", de: "Entdecken Sie ein einzigartiges Foto-Erlebnis am ikonischen Cais Palafítico da Carrasqueira, einem der atmosphärischsten Holzpfahl-Stege Portugals. Umgeben vom ruhigen Wasser und der rohen Schönheit des Sado-Mündungsgebiets bietet dieses versteckte Juwel eine zeitlose, filmische Kulisse. Perfekt für Paare, Familien oder Porträts, die authentische, künstlerische Bilder in einer wirklich unvergesslichen, rustikalen Küstenlandschaft suchen.", es: "Descubra una experiencia fotográfica única en el icónico Cais Palafítico da Carrasqueira, uno de los muelles palafíticos más atmosféricos de Portugal. Rodeado por las aguas tranquilas y la belleza cruda del estuario del Sado, este rincón escondido ofrece un escenario cinematográfico atemporal. Perfecto para parejas, familias o retratos que busquen imágenes auténticas y artísticas en un paisaje costero rústico y verdaderamente inolvidable.", fr: "Découvrez une expérience photo unique à l'emblématique Cais Palafítico da Carrasqueira, l'un des pontons sur pilotis les plus atmosphériques du Portugal. Entouré par les eaux calmes et la beauté brute de l'estuaire du Sado, ce trésor caché offre un décor cinématographique intemporel. Idéal pour couples, familles ou portraits en quête d'images authentiques et artistiques dans un paysage côtier rustique vraiment inoubliable." } },
  { id: "3d7238d9-0a15-4204-8aa2-012075ec6236",
    name: { pt: "Pedidos de Casamento", de: "Heiratsanträge", es: "Pedidas de mano", fr: "Demandes en mariage" },
    description: { pt: "O início da vossa história de amor começa aqui.\nLevamo-vos aos lugares mais extraordinários, para que possam viver verdadeiramente este novo capítulo da vida como ele merece.\nMais do que memórias, captamos a espontaneidade e autenticidade por trás de cada emoção para que possam revivê-las, vezes sem conta.\nA Madeira é o cenário.\nTudo o que têm de fazer é viver o momento.\nA vossa nova história começa aqui.", de: "Hier beginnt Ihre Liebesgeschichte.\nWir bringen Sie an die außergewöhnlichsten Orte, damit Sie dieses neue Kapitel Ihres Lebens so erleben können, wie es gelebt werden sollte.\nMehr als Erinnerungen — wir halten die Spontaneität und Echtheit hinter jeder Emotion fest, damit Sie sie immer wieder neu erleben können.\nMadeira ist die Kulisse.\nSie müssen nur den Moment leben.\nIhre neue Geschichte beginnt hier.", es: "El inicio de su historia de amor empieza aquí.\nLes llevamos a los lugares más extraordinarios para que puedan vivir verdaderamente este nuevo capítulo como merece ser vivido.\nMás que recuerdos, capturamos la espontaneidad y autenticidad detrás de cada emoción para que puedan revivirlas una y otra vez.\nMadeira es el escenario.\nLo único que tienen que hacer es vivir el momento.\nSu nueva historia empieza aquí.", fr: "Le début de votre histoire d'amour commence ici.\nNous vous emmenons dans les lieux les plus extraordinaires, pour que vous puissiez vraiment vivre ce nouveau chapitre comme il mérite de l'être.\nPlus que des souvenirs, nous captons la spontanéité et l'authenticité derrière chaque émotion pour que vous puissiez les revivre, encore et encore.\nMadère est le décor.\nVous n'avez plus qu'à vivre l'instant.\nVotre nouvelle histoire commence ici." } },
];

for (const p of PKG) {
  const cols = []; const params = [];
  for (const loc of ["pt","de","es","fr"]) {
    if (p.name?.[loc]) { cols.push(`name_${loc} = $${params.length+1}`); params.push(p.name[loc]); }
    if (p.description?.[loc]) { cols.push(`description_${loc} = $${params.length+1}`); params.push(p.description[loc]); }
  }
  if (cols.length === 0) {
    await client.query(`UPDATE packages SET translations_dirty = FALSE, translations_updated_at = NOW() WHERE id = $1`, [p.id]);
    console.log(`✓ ${p.id.slice(0,8)} (empty/skipped)`);
    continue;
  }
  cols.push(`translations_updated_at = NOW()`, `translations_dirty = FALSE`);
  params.push(p.id);
  await client.query(`UPDATE packages SET ${cols.join(", ")} WHERE id = $${params.length}`, params);
  console.log(`✓ ${p.id.slice(0,8)} ${p.name.fr || ""}`);
}
await client.end();
console.log(`\nBatch pkg-3 done — ${PKG.length} packages translated.`);
