// Photo Portugal blog — batch 1 of the thin-category fills (2026-08-08).
// DE/ES/FR siblings of existing EN guides plus the missing PT/FR pieces,
// grouped for hreflang by scripts/blog-pt/link-translations.mjs.
export const POSTS = [
  {
    "slug": "beste-fotospots-porto",
    "locale": "de",
    "category": "locations",
    "published_at": "2026-08-04T10:00:00Z",
    "title": "Die besten Fotospots in Porto: Brücke, Gassen und das Licht am Douro",
    "meta_title": "Beste Fotospots in Porto: der Guide",
    "meta_description": "Die Ponte Luís I von beiden Ebenen, die Gassen der Ribeira, Azulejo-Fassaden und die Gaia-Seite zur goldenen Stunde — Portos beste Fotospots mit Uhrzeiten.",
    "target_keywords": "fotospots porto, porto fotoshooting orte, ponte luis fotos, ribeira porto fotos, gaia aussicht porto",
    "excerpt": "Porto fotografiert sich von der anderen Flussseite am besten — und aus den Gassen, in die kein Reisebus passt. Die Spots, mit Uhrzeit.",
    "content": "## Porto ist eine Stadt für die Gegenseite\n\nDas berühmteste Bild von Porto entsteht nicht in Porto: Es entsteht in Gaia, am anderen Ufer des Douro, wenn die Abendsonne die gestapelte Altstadt anzündet und die Ponte Luís I als schwarze Linie davorsteht. Wer das weiß, plant den Tag rückwärts — Gassen am Morgen, Fluss am Abend.\n\n## Die Spots, in sinnvoller Reihenfolge\n\n**Die Ribeira am Morgen.** Vor zehn gehören die Arkaden am Wasser und die schmalen Treppen dahinter Ihnen. Die bunten Fassaden stehen im Streiflicht, die Restauranttische sind noch drinnen. Wer Paare fotografiert, arbeitet hier die halbe Session ab: Praça da Ribeira, die Gasse Rua dos Canastreiros, die Bögen am Kai.\n\n**Ponte Luís I, untere Ebene.** Die Fußgängerspur neben der Straße bringt Sie auf Wasserhöhe ans andere Ufer — mit der Altstadt im Rücken. Kurz, praktisch, immer offen.\n\n**Ponte Luís I, obere Ebene.** 60 Meter über dem Fluss, die Metro fährt hinter Ihnen vorbei, unter Ihnen liegt die ganze Stadt. Nichts für Höhenangst, alles für Panoramen. Morgens Gegenlicht Richtung Altstadt, abends Rückenlicht — die Abendquerung gewinnt.\n\n**Jardim do Morro und Serra do Pilar, Gaia.** Direkt an der oberen Brückenebene beginnt der Garten, dessen Hang zur goldenen Stunde zum Amphitheater wird. Fünf Minuten höher steht das Kloster Serra do Pilar mit der klassischsten aller Porto-Ansichten. Sonnenuntergang hier ist kein Geheimtipp mehr — kommen Sie 45 Minuten früher und arbeiten Sie, bevor die Picknickdecken landen.\n\n**Azulejos: São Bento und Capela das Almas.** Die Bahnhofshalle von São Bento (20.000 Fliesen) funktioniert früh, bevor die Koffer rollen; die blau geflieste Capela das Almas in der Rua Santa Catarina steht mitten in der Einkaufsstraße — Sonntagmorgen ist ihre Stunde.\n\n**Die Gassen dazwischen.** Rua das Flores für Fassaden und Straßencafés, die Treppen der Escadas do Codeçal unterhalb der Kathedrale, Miradouro da Vitória für den Blick über die Dächer zur Brücke. Porto ist steil: Wer hier fotografiert, plant Pausen wie Spots.\n\n## Uhrzeiten, ehrlich\n\n| Fenster | Wo |\n| --- | --- |\n| 8–10 Uhr | Ribeira, São Bento, Rua das Flores |\n| 10–17 Uhr | Azulejos, Gassen im Schatten, Kaffeepausen |\n| Goldene Stunde | Gaia-Ufer, Jardim do Morro, obere Brücke |\n| Blaue Stunde | Serra do Pilar, wenn die Stadtlichter angehen |\n\n## Der praktische Teil\n\nPortos Granit ist bei Regen glatt wie Seife und die Stadt ist eine Treppe: flache Schuhe, die Absätze in der Tasche. Für eine Session reicht ein Gebiet — Ribeira plus Brücke plus Gaia ist der klassische Zwei-Stunden-Bogen, den ein ortskundiger Fotograf ohne Leerlauf führt. Die [Porto-Seite](/locations/porto) zeigt Fotografen und Pakete; für [Paar-Shootings](/photoshoots/couples) ist der Abendbogen die halbe Miete.\n"
  },
  {
    "slug": "mejores-lugares-fotos-porto",
    "locale": "es",
    "category": "locations",
    "published_at": "2026-08-04T10:00:00Z",
    "title": "Los mejores lugares para fotos en Oporto: puente, callejas y la luz del Duero",
    "meta_title": "Mejores lugares para fotos en Oporto: la guía",
    "meta_description": "El puente Luís I desde sus dos niveles, las callejas de la Ribeira, fachadas de azulejos y la orilla de Gaia a la hora dorada — los mejores spots de Oporto con horarios.",
    "target_keywords": "lugares fotos oporto, sesion fotos oporto, puente luis i fotos, ribeira oporto fotos, mirador gaia oporto",
    "excerpt": "Oporto se fotografía mejor desde la otra orilla — y desde las callejas donde no cabe un autobús. Los lugares, con su hora.",
    "content": "## Oporto es una ciudad de orilla contraria\n\nLa foto más famosa de Oporto no se hace en Oporto: se hace en Gaia, al otro lado del Duero, cuando el sol de la tarde enciende el casco viejo apilado y el puente Luís I queda delante como una línea negra. Sabiendo eso, el día se planifica al revés — callejas por la mañana, río por la tarde.\n\n## Los lugares, en orden útil\n\n**La Ribeira por la mañana.** Antes de las diez, los soportales junto al agua y las escaleras estrechas de detrás son vuestros. Las fachadas de colores reciben luz rasante y las mesas de los restaurantes siguen dentro. Para una sesión de pareja, aquí se trabaja media hora larga: la Praça da Ribeira, la Rua dos Canastreiros, los arcos del muelle.\n\n**Puente Luís I, nivel inferior.** El paso peatonal junto a la carretera cruza a ras de agua hasta la otra orilla, con el casco viejo a la espalda. Corto, práctico, siempre abierto.\n\n**Puente Luís I, nivel superior.** Sesenta metros sobre el río, el metro pasando detrás y la ciudad entera debajo. Nada para el vértigo, todo para los panoramas. Por la mañana, contraluz hacia el casco viejo; por la tarde, luz a favor — el cruce vespertino gana.\n\n**Jardim do Morro y Serra do Pilar, en Gaia.** Pegado al nivel alto del puente empieza el jardín cuya ladera se convierte en anfiteatro a la hora dorada. Cinco minutos más arriba, el monasterio de Serra do Pilar guarda la vista más clásica de Oporto. El atardecer aquí ya no es un secreto: llegad 45 minutos antes y trabajad antes de que aterricen las mantas de picnic.\n\n**Azulejos: São Bento y la Capela das Almas.** El vestíbulo de la estación de São Bento (veinte mil azulejos) funciona temprano, antes de que rueden las maletas; la capilla azul de la Rua Santa Catarina está en plena calle comercial — el domingo por la mañana es su hora.\n\n**Las callejas de en medio.** La Rua das Flores para fachadas y cafés, las escaleras del Codeçal bajo la catedral, el Miradouro da Vitória para la vista de tejados y puente. Oporto es empinado: aquí las pausas se planifican como los lugares.\n\n## Horarios, sin adornos\n\n| Ventana | Dónde |\n| --- | --- |\n| 8–10 h | Ribeira, São Bento, Rua das Flores |\n| 10–17 h | Azulejos, callejas en sombra, cafés |\n| Hora dorada | Orilla de Gaia, Jardim do Morro, puente superior |\n| Hora azul | Serra do Pilar, cuando se encienden las luces |\n\n## La parte práctica\n\nEl granito de Oporto con lluvia resbala como jabón y la ciudad es una escalera: calzado plano, los tacones en el bolso. Para una sesión basta una zona — Ribeira más puente más Gaia es el arco clásico de dos horas que un fotógrafo local guía sin tiempos muertos. La [página de Oporto](/locations/porto) muestra fotógrafos y paquetes; para las [sesiones de pareja](/photoshoots/couples), el arco vespertino es media victoria.\n"
  },
  {
    "slug": "meilleurs-spots-photo-porto",
    "locale": "fr",
    "category": "locations",
    "published_at": "2026-08-04T10:00:00Z",
    "title": "Les meilleurs spots photo de Porto : le pont, les ruelles et la lumière du Douro",
    "meta_title": "Meilleurs spots photo de Porto : le guide",
    "meta_description": "Le pont Luís I depuis ses deux niveaux, les ruelles de la Ribeira, les façades d'azulejos et la rive de Gaia à l'heure dorée — les spots de Porto, avec les horaires.",
    "target_keywords": "spots photo porto, seance photo porto, pont luis i photos, ribeira porto photos, point de vue gaia porto",
    "excerpt": "Porto se photographie depuis l'autre rive — et depuis les ruelles où aucun car ne passe. Les spots, avec leur heure.",
    "content": "## Porto est une ville de rive opposée\n\nLa photo la plus célèbre de Porto ne se prend pas à Porto : elle se prend à Gaia, de l'autre côté du Douro, quand le soleil du soir embrase la vieille ville empilée et que le pont Luís I se découpe devant en ligne noire. Une fois qu'on le sait, la journée se planifie à l'envers — ruelles le matin, fleuve le soir.\n\n## Les spots, dans l'ordre utile\n\n**La Ribeira au matin.** Avant dix heures, les arcades du bord de l'eau et les escaliers étroits de l'arrière sont à vous. Les façades colorées prennent la lumière rasante, les tables des restaurants sont encore rentrées. Pour une séance en couple, on travaille ici une grosse demi-heure : la Praça da Ribeira, la Rua dos Canastreiros, les arches du quai.\n\n**Pont Luís I, niveau bas.** Le passage piéton longe la route et traverse au ras de l'eau, la vieille ville dans le dos. Court, pratique, toujours ouvert.\n\n**Pont Luís I, niveau haut.** Soixante mètres au-dessus du fleuve, le métro qui passe derrière, la ville entière dessous. Rien pour le vertige, tout pour les panoramas. Le matin, contre-jour vers la vieille ville ; le soir, lumière de face — la traversée du soir l'emporte.\n\n**Jardim do Morro et Serra do Pilar, à Gaia.** Au débouché du tablier haut commence le jardin dont la pente devient amphithéâtre à l'heure dorée. Cinq minutes plus haut, le monastère de Serra do Pilar garde la vue la plus classique de Porto. Le coucher de soleil n'y est plus un secret : arrivez 45 minutes avant et travaillez avant l'atterrissage des couvertures de pique-nique.\n\n**Azulejos : São Bento et la Capela das Almas.** Le hall de la gare de São Bento (vingt mille carreaux) fonctionne tôt, avant les valises ; la chapelle bleue de la Rua Santa Catarina donne sur la rue commerçante — le dimanche matin est son heure.\n\n**Les ruelles entre les deux.** La Rua das Flores pour les façades et les cafés, les escaliers du Codeçal sous la cathédrale, le Miradouro da Vitória pour la vue sur les toits et le pont. Porto est raide : ici, on planifie les pauses comme les spots.\n\n## Les horaires, sans fard\n\n| Fenêtre | Où |\n| --- | --- |\n| 8–10 h | Ribeira, São Bento, Rua das Flores |\n| 10–17 h | Azulejos, ruelles à l'ombre, cafés |\n| Heure dorée | Rive de Gaia, Jardim do Morro, pont supérieur |\n| Heure bleue | Serra do Pilar, quand les lumières s'allument |\n\n## La partie pratique\n\nLe granit de Porto mouillé glisse comme du savon et la ville est un escalier : chaussures plates, les talons dans le sac. Une zone suffit pour une séance — Ribeira plus pont plus Gaia est l'arc classique de deux heures qu'un photographe du cru mène sans temps mort. La [page de Porto](/locations/porto) présente photographes et formules ; pour les [séances couple](/photoshoots/couples), l'arc du soir est la moitié de la victoire.\n"
  },
  {
    "slug": "was-anziehen-fotoshooting-portugal",
    "locale": "de",
    "category": "planning",
    "published_at": "2026-08-01T10:00:00Z",
    "title": "Was anziehen für ein Fotoshooting in Portugal — aus dem Koffer",
    "meta_title": "Was anziehen fürs Fotoshooting in Portugal",
    "meta_description": "Farben, die vor Azulejos und Atlantik funktionieren, der Wind an der Küste, Schuhe für Kopfsteinpflaster — was Sie für ein Shooting in Portugal einpacken.",
    "target_keywords": "was anziehen fotoshooting portugal, outfit fotoshooting lissabon, kleidung fotos algarve, fotoshooting kleidung tipps",
    "excerpt": "Portugals Kulissen haben zwei Paletten — Azulejo-Blau und Atlantik-Gold. Was dazu passt, was der Küstenwind verbietet und was ins Handgepäck gehört.",
    "content": "## Zwei Paletten, ein Koffer\n\nPortugal fotografiert sich in zwei Farbwelten: das Blau-Weiß der Azulejos und Kalkfassaden in Lissabon und Porto, und das Gold-Türkis der Algarve-Klippen und -Strände. Die gute Nachricht: Dieselben Kleiderfarben funktionieren in beiden — Creme, Sand, Terrakotta, Salbei, gedecktes Blau. Was in beiden scheitert: Neon, große Logos, kleinteilige Muster, die im Bild flimmern.\n\n## Die Regeln, die den Unterschied machen\n\n**Lange, fließende Stoffe schlagen alles.** Der Atlantikwind ist in Portugal Mitgestalter: Ein bodenlanges Kleid, das sich an der Klippe bewegt, IST das Foto. Steife, enge Silhouetten verschenken genau diesen Effekt.\n\n**Einer trägt Struktur, der andere Ruhe.** Bei Paaren: ein gemustertes oder strukturiertes Teil (Leinenhemd, Strickjacke), der Partner in Uni. Beide gemustert konkurrieren; beide uni wirken wie Uniform.\n\n**Kontrast zum Hintergrund denken.** Vor weißen Dörfern und Kalkwänden trägt Dunkles und Warmes; vor dunklem Basalt und Abendhimmel helles. Wer beides am selben Abend will, wechselt einmal — mehr Wechsel fressen Licht.\n\n**Die Schuhfrage ist in Portugal keine Stilfrage.** Calçada — das polierte Kopfsteinpflaster — ist steil, wellig und bei Feuchtigkeit spiegelglatt. Flache Schuhe zum Gehen, die Absätze kommen aus der Tasche nur fürs Bild. An den Algarve-Stränden: barfuß ist das eleganteste Schuhwerk.\n\n## Der Küsten-Absatz\n\nFür Klippen- und Strandsessions (Algarve, Ericeira, Nazaré) gelten drei Extras: eine Lage mehr als in der Stadt (der Wind kostet gefühlte fünf Grad), Haargummi für den Weg und offene Haare erst am Spot, und nichts, was fliegt — Hüte nur mit Band, Tücher nur zum Werfen geplant.\n\n## Was ins Handgepäck gehört\n\n- Outfit eins: das fließende Hauptstück in Uni oder Erdton.\n- Outfit zwei: die entspannte Variante — Jeans und helles Hemd altern auf Bildern nie.\n- Ein Lagen-Teil: Strickjacke oder Leinenblazer, der beide Outfits ergänzt.\n- Flache Schuhe plus die Bildschuhe.\n- Für den Abend an der Küste: ein Tuch, das absichtlich fliegen darf.\n\n## Was Sie dem Fotografen sagen sollten\n\nSchicken Sie vorab ein Foto der geplanten Outfits — nicht aus Eitelkeit, sondern wegen der Spots: Ein Fotograf, der weiß, dass Sie in Terrakotta kommen, legt die Route über die Kalkgassen von Alfama statt über die orangen Dächer. Nach der Buchung kommt ohnehin ein Style-Guide für Ort, Saison und Uhrzeit; die Grundregeln hier überleben jede Mode. Wie die Session selbst abläuft, steht in den [Paar-](/photoshoots/couples) und [Familien-Seiten](/photoshoots/family) — und wer in [Lissabon](/locations/lisbon) oder an der [Algarve](/locations/algarve) fotografiert, findet dort die Spots zur Palette.\n"
  },
  {
    "slug": "que-ponerse-sesion-fotos-portugal",
    "locale": "es",
    "category": "planning",
    "published_at": "2026-08-01T10:00:00Z",
    "title": "Qué ponerse para una sesión de fotos en Portugal — desde la maleta",
    "meta_title": "Qué ponerse para una sesión en Portugal",
    "meta_description": "Colores que funcionan ante azulejos y Atlántico, el viento de la costa, calzado para el empedrado — qué meter en la maleta para una sesión en Portugal.",
    "target_keywords": "que ponerse sesion fotos portugal, outfit sesion fotos lisboa, ropa fotos algarve, consejos ropa sesion fotos",
    "excerpt": "Los decorados de Portugal tienen dos paletas — azul azulejo y oro atlántico. Qué combina con ambas, qué prohíbe el viento de la costa y qué va en el equipaje de mano.",
    "content": "## Dos paletas, una maleta\n\nPortugal se fotografía en dos mundos de color: el azul y blanco de los azulejos y fachadas encaladas de Lisboa y Oporto, y el oro y turquesa de los acantilados y playas del Algarve. La buena noticia: los mismos colores de ropa funcionan en ambos — crema, arena, terracota, salvia, azules apagados. Lo que fracasa en ambos: el neón, los logos grandes y los estampados menudos que vibran en la imagen.\n\n## Las reglas que marcan la diferencia\n\n**Los tejidos largos y fluidos ganan siempre.** El viento atlántico es coautor en Portugal: un vestido largo moviéndose en el acantilado ES la foto. Las siluetas rígidas y ajustadas regalan justo ese efecto.\n\n**Uno lleva textura, el otro calma.** En pareja: una prenda estampada o con textura (camisa de lino, cárdigan) y el otro en liso. Dos estampados compiten; dos lisos parecen uniforme.\n\n**Pensar el contraste con el fondo.** Ante pueblos blancos y muros de cal, ropa oscura y cálida; ante basalto oscuro y cielo de atardecer, ropa clara. Quien quiera ambas en la misma tarde, un solo cambio — más cambios se comen la luz.\n\n**En Portugal, el calzado no es una cuestión de estilo.** La calçada — el empedrado pulido — es empinada, ondulada y, con humedad, un espejo. Zapato plano para caminar; los tacones salen del bolso solo para el encuadre. En las playas del Algarve, ir descalzo es el calzado más elegante.\n\n## El párrafo costero\n\nPara sesiones de acantilado y playa (Algarve, Ericeira, Nazaré) valen tres extras: una capa más que en ciudad (el viento resta cinco grados de sensación), coletero para el camino y melena suelta solo en el spot, y nada que vuele — sombreros solo con cinta, pañuelos solo si el plan es lanzarlos.\n\n## Qué va en el equipaje de mano\n\n- Outfit uno: la prenda fluida principal, lisa o en tono tierra.\n- Outfit dos: la variante relajada — vaqueros y camisa clara no envejecen nunca en foto.\n- Una capa: cárdigan o blazer de lino que complete ambos outfits.\n- Zapato plano más el zapato de la foto.\n- Para la tarde en la costa: un pañuelo con permiso para volar.\n\n## Qué decirle al fotógrafo\n\nEnviad antes una foto de los outfits previstos — no por vanidad, sino por los spots: un fotógrafo que sabe que venís de terracota trazará la ruta por las calles encaladas de Alfama y no por los tejados naranjas. Tras la reserva llega de todos modos una guía de estilo para lugar, estación y hora; las reglas de aquí sobreviven a cualquier moda. Cómo transcurre la sesión está en las páginas de [pareja](/photoshoots/couples) y [familia](/photoshoots/family) — y quien fotografíe en [Lisboa](/locations/lisbon) o el [Algarve](/locations/algarve) encontrará allí los spots para cada paleta.\n"
  },
  {
    "slug": "que-porter-seance-photo-portugal",
    "locale": "fr",
    "category": "planning",
    "published_at": "2026-08-01T10:00:00Z",
    "title": "Que porter pour une séance photo au Portugal — depuis la valise",
    "meta_title": "Que porter pour une séance photo au Portugal",
    "meta_description": "Les couleurs qui marchent devant azulejos et Atlantique, le vent de la côte, les chaussures pour les pavés — quoi emporter pour une séance au Portugal.",
    "target_keywords": "que porter seance photo portugal, tenue seance photo lisbonne, vetements photos algarve, conseils tenue seance photo",
    "excerpt": "Les décors du Portugal ont deux palettes — bleu azulejo et or atlantique. Ce qui va avec les deux, ce que le vent côtier interdit, ce qui tient dans le bagage cabine.",
    "content": "## Deux palettes, une valise\n\nLe Portugal se photographie dans deux mondes de couleur : le bleu-blanc des azulejos et des façades chaulées de Lisbonne et Porto, et l'or-turquoise des falaises et plages de l'Algarve. La bonne nouvelle : les mêmes couleurs de vêtements fonctionnent dans les deux — crème, sable, terracotta, sauge, bleus éteints. Ce qui échoue dans les deux : le néon, les gros logos, les petits motifs qui vibrent à l'image.\n\n## Les règles qui font la différence\n\n**Les tissus longs et fluides gagnent toujours.** Le vent atlantique est coauteur au Portugal : une robe longue qui bouge sur la falaise EST la photo. Les silhouettes raides et près du corps sacrifient exactement cet effet.\n\n**L'un porte la texture, l'autre le calme.** En couple : une pièce à motif ou texturée (chemise en lin, cardigan), l'autre en uni. Deux motifs se concurrencent ; deux unis font uniforme.\n\n**Penser le contraste avec le fond.** Devant les villages blancs et les murs de chaux, du sombre et du chaud ; devant le basalte sombre et le ciel du soir, du clair. Pour avoir les deux le même soir : un seul changement — les suivants mangent la lumière.\n\n**Au Portugal, la chaussure n'est pas une question de style.** La calçada — le pavé poli — est pentue, ondulée et, humide, un miroir. Chaussures plates pour marcher ; les talons sortent du sac pour le cadre seulement. Sur les plages de l'Algarve, pieds nus est la chaussure la plus élégante.\n\n## Le paragraphe côtier\n\nPour les séances falaise et plage (Algarve, Ericeira, Nazaré), trois extras : une couche de plus qu'en ville (le vent coûte cinq degrés de ressenti), un élastique pour le trajet et les cheveux lâchés seulement sur le spot, et rien qui s'envole — chapeaux à ruban, foulards seulement si le plan est de les lancer.\n\n## Ce qui va dans le bagage cabine\n\n- Tenue une : la pièce fluide principale, unie ou ton terre.\n- Tenue deux : la version détendue — jean et chemise claire ne vieillissent jamais en photo.\n- Une couche : cardigan ou blazer en lin qui complète les deux tenues.\n- Chaussures plates plus les chaussures d'image.\n- Pour le soir sur la côte : un foulard autorisé à voler.\n\n## Ce qu'il faut dire au photographe\n\nEnvoyez à l'avance une photo des tenues prévues — pas par vanité, mais pour les spots : un photographe qui sait que vous arrivez en terracotta tracera l'itinéraire par les ruelles chaulées de l'Alfama plutôt que par les toits orange. Après la réservation arrive de toute façon un guide de style pour le lieu, la saison et l'heure ; les règles d'ici survivent à toutes les modes. Le déroulé de la séance est sur les pages [couple](/photoshoots/couples) et [famille](/photoshoots/family) — et qui shoote à [Lisbonne](/locations/lisbon) ou en [Algarve](/locations/algarve) y trouvera les spots pour chaque palette.\n"
  },
  {
    "slug": "seance-photo-couple-lisbonne",
    "locale": "fr",
    "category": "couples",
    "published_at": "2026-07-29T10:00:00Z",
    "title": "Séance photo de couple à Lisbonne : les quartiers, l'heure et le tram",
    "meta_title": "Séance photo de couple à Lisbonne : le guide",
    "meta_description": "Alfama à l'aube, les miradouros à l'heure dorée, le tram 28 sans la foule — comment se construit une séance de couple à Lisbonne qui ne ressemble pas aux autres.",
    "target_keywords": "seance photo couple lisbonne, photographe couple lisbonne, alfama seance photo, miradouro lisbonne couple",
    "excerpt": "Lisbonne récompense les couples qui se lèvent tôt : l'Alfama vide, la lumière rasante sur les azulejos, et les miradouros avant les valises.",
    "content": "## Lisbonne se mérite à l'aube\n\nLisbonne est une ville de lumière rasante : bâtie sur des collines face au Tage, elle s'allume deux fois par jour — et le matin, elle s'allume vide. Une séance de couple qui commence à 7 h 30 dans l'Alfama obtient des ruelles sans personne, des azulejos dorés et un café ouvert à l'arrivée. La même séance à midi obtient des groupes de croisiéristes et un soleil vertical. Le choix est vite fait.\n\n## L'itinéraire qui fonctionne\n\n**L'Alfama d'abord.** Le quartier le plus ancien est un labyrinthe de ruelles, d'escaliers et de linge étendu — le décor le plus intime de la ville. Les spots qui portent une séance : les abords de la cathédrale, la Rua de São Miguel, les escaliers qui descendent vers le fleuve. On y travaille la proximité : mains, regards, la marche à deux dans une ruelle qui n'appartient qu'à vous.\n\n**Un miradouro ensuite.** Santa Luzia, avec sa pergola et ses azulejos, est le classique ; Portas do Sol, à cinquante mètres, ouvre plus large sur le Tage et les toits. Le matin, la lumière vient de derrière le fleuve — parfaite en contre-jour doux sur les silhouettes.\n\n**Le tram, sans y monter.** Le tram 28 est le motif le plus lisbonnin qui soit — et le plus raté quand on essaie de le prendre. Le secret : ne pas monter dedans, mais le laisser passer. Sur les courbes de l'Alfama ou à l'arrêt de la cathédrale, le jaune du tram derrière un couple en mouvement fait la photo. Votre photographe connaît les trois virages où il ralentit.\n\n**Finir au Chiado ou à la Baixa.** Vers 9 h 30, quand l'Alfama se remplit, la ville basse offre ses façades néoclassiques, l'Arco da Rua Augusta et les terrasses de café pour les dernières images — plus urbaines, plus habillées.\n\n## L'option du soir\n\nSi l'aube est impossible, le soir inverse l'itinéraire : Baixa à 18 h, miradouro à l'heure dorée — Graça ou Senhora do Monte, orientés ouest, regardent le soleil tomber derrière le château — et les ruelles de l'Alfama à la lueur des lampadaires pour clore. Plus de monde, mais la lumière du couchant sur le Tage compense.\n\n## Les détails qui font la séance\n\n- **Les chaussures, encore.** La calçada lisboète est polie par les siècles ; les talons se portent sur les photos, pas entre elles.\n- **Une couche pour le matin.** Même en été, 7 h 30 face au fleuve demande une veste — qui devient accessoire d'image.\n- **Le pastel de nata comme accessoire.** Le café du matin est une scène, pas une pause : comptoir en marbre, tasse, complicité. Certaines des meilleures images de couple de Lisbonne se prennent attablés.\n\nLa [page des séances couple](/photoshoots/couples) présente les photographes et les formules ; le détail des spots, quartier par quartier, vit sur la [page de Lisbonne](/locations/lisbon).\n"
  },
  {
    "slug": "sessao-fotografica-casal-porto",
    "locale": "pt",
    "category": "couples",
    "published_at": "2026-07-27T10:00:00Z",
    "title": "Sessão fotográfica de casal no Porto: a Ribeira, a ponte e a hora certa",
    "meta_title": "Sessão de casal no Porto: roteiro e hora certa",
    "meta_description": "A Ribeira de manhã, a Ponte Luís I nos dois tabuleiros e Gaia à hora dourada — como se constrói uma sessão de casal no Porto, com o roteiro e a hora certa.",
    "target_keywords": "sessao fotografica casal porto, fotografo casal porto, ribeira sessao fotos, gaia por do sol casal",
    "excerpt": "O Porto pede o dia ao contrário: vielas de manhã, rio ao fim da tarde. O roteiro de uma sessão de casal que aproveita a cidade toda.",
    "content": "## O dia ao contrário\n\nO Porto tem uma regra simples: as vielas são de manhã, o rio é ao fim do dia. A fotografia mais famosa da cidade — o casario empilhado aceso pelo sol poente, com a Ponte Luís I em silhueta — tira-se de Gaia, da outra margem. Uma sessão de casal bem desenhada respeita essa ordem: começa cedo na Ribeira e acaba do outro lado do Douro, com a cidade a arder ao fundo.\n\n## O roteiro\n\n**A Ribeira antes das dez.** As arcadas junto ao rio, a Praça da Ribeira, as escadas estreitas que sobem para a Sé — tudo vazio, tudo com luz rasante nas fachadas coloridas. É aqui que se trabalha a proximidade: as mãos, o passeio a dois, o riso verdadeiro numa viela que é só vossa.\n\n**A Rua das Flores e São Bento.** A subir para o centro, as fachadas e os cafés da Rua das Flores dão o cenário urbano; o átrio de São Bento, com vinte mil azulejos, funciona cedo — antes das malas de rodinhas.\n\n**A ponte, nos dois tabuleiros.** O inferior atravessa rente à água, com o casario nas costas; o superior, sessenta metros acima, entrega o panorama inteiro. À tarde, a travessia de cima ganha: a luz vem de trás e o rio brilha.\n\n**Gaia à hora dourada.** O Jardim do Morro transforma-se em anfiteatro ao pôr do sol, e cinco minutos acima o Mosteiro da Serra do Pilar guarda o postal clássico. Cheguem 45 minutos antes do sol baixo: trabalha-se melhor antes de as mantas de piquenique aterrarem.\n\n## Pormenores que fazem a sessão\n\n- **Calçado raso.** O granito do Porto molhado é um sabão, e a cidade é uma escada. Os saltos viajam no saco e saem só para o enquadramento.\n- **Uma camada extra.** O vento do Douro ao fim da tarde desconta cinco graus à sensação — e um casaco de linho é também adereço.\n- **Um copo no fim.** As caves e os rooftops de Gaia estão a dois passos do miradouro: as últimas fotografias, de copo na mão com a cidade acesa, são muitas vezes as preferidas.\n\n## Quanto tempo reservar\n\nUma hora chega para um dos lados do rio; duas horas compram o arco completo — Ribeira, ponte e Gaia — sem pressa e com espaço para o acaso. A [página das sessões de casal](/photoshoots/couples) tem os fotógrafos e os pacotes; os spots ao pormenor, com horas e alternativas, vivem na [página do Porto](/locations/porto).\n"
  },
  {
    "slug": "sessao-fotografica-familia-lisboa",
    "locale": "pt",
    "category": "family",
    "published_at": "2026-07-31T10:00:00Z",
    "title": "Sessão fotográfica de família em Lisboa com crianças pequenas",
    "meta_title": "Sessão de família em Lisboa com crianças",
    "meta_description": "Jardins onde as crianças correm, o elétrico como cenário e a manhã como regra — como planear uma sessão de família em Lisboa que os miúdos aguentam.",
    "target_keywords": "sessao fotografica familia lisboa, fotografo familia lisboa, fotos familia criancas lisboa, sessao familia jardim lisboa",
    "excerpt": "Uma criança de quatro anos não vos deve uma hora de pose. Em Lisboa, a sessão de família funciona onde ela pode correr — e de manhã, não ao pôr do sol.",
    "content": "## A regra: o roteiro é do mais novo\n\nUma sessão de família em Lisboa falha por uma única razão: um roteiro pensado para adultos. Subidas, filas, \"não toques\", horário de pôr do sol quando o cansaço está no máximo. O plano certo parte da idade do mais novo e constrói tudo à volta disso.\n\n## Os sítios que funcionam\n\n**O Jardim da Estrela.** O valor mais seguro da cidade: caminhos planos (carrinho de bebé sem drama), sombra a sério, o coreto, os patos, um parque infantil para a pausa. As melhores fotografias acontecem enquanto brincam — o fotógrafo observa e reage, não põe em pose.\n\n**Belém, de manhã cedo.** O jardim em frente aos Jerónimos dá espaço para correr com o mosteiro ao fundo, e o rio está a cinco minutos planos. A paragem estratégica: os pastéis de Belém — uma criança a caminho do pastel é uma criança feliz em fotografia. Antes das dez, filas curtas e luz suave.\n\n**A Alfama, com juízo.** As vielas são um cenário lindíssimo e um labirinto de escadas: funcionam para famílias com crianças que já caminham bem, num troço curto — Portas do Sol até Santa Luzia, com o elétrico 28 a passar como cenário. Com carrinho de bebé, não.\n\n**O miradouro no fim.** Se a energia chegar, um miradouro fecha a sessão com a fotografia de família e a cidade em fundo — a Graça tem quiosque com gelados, o que resolve dois problemas de uma vez.\n\n## A hora certa (não é o pôr do sol)\n\nCom crianças até aos seis anos, a manhã ganha sempre: entre as 8h30 e as 10h30 a energia está no ponto, a luz ainda é boa e os sítios estão vazios. Uma sessão às 19h com uma criança de três anos é uma aposta contra o sono — e o sono ganha.\n\n## Como os preparar (pouco)\n\n- **Não anunciem \"fotografias\".** Anunciem uma aventura: o jardim, os patos, o pastel. A câmara é um pormenor.\n- **Lanche e água** no saco, sempre. Metade das birras é fome.\n- **Roupa para mexer**, paleta coordenada sem exageros — tons terra e pastéis resultam bem contra o calcário e os azulejos.\n- **45 minutos úteis**, não 90. Abaixo dos cinco anos, o limite é a paciência: o pacote de uma hora chega.\n\n## O que esperar da galeria\n\nTrês famílias de fotografias: as de conjunto no miradouro ou jardim, as de brincadeira (as mais verdadeiras) e os pormenores — mãos pequenas, o pastel, a corrida. A [página das sessões de família](/photoshoots/family) mostra os fotógrafos que sabem mesmo lidar com crianças; os spots com horas e alternativas estão na [página de Lisboa](/locations/lisbon).\n"
  },
  {
    "slug": "demande-en-mariage-lisbonne-lieux",
    "locale": "fr",
    "category": "proposals",
    "published_at": "2026-08-03T10:00:00Z",
    "title": "Demande en mariage à Lisbonne : les lieux qui marchent vraiment",
    "meta_title": "Demande en mariage à Lisbonne : les lieux",
    "meta_description": "Miradouros au coucher du soleil, jardins discrets et l'aube dans l'Alfama — où faire sa demande à Lisbonne, avec l'heure juste et le photographe caché.",
    "target_keywords": "demande en mariage lisbonne, ou faire sa demande lisbonne, demande surprise lisbonne, photographe demande lisbonne",
    "excerpt": "Lisbonne regarde le Tage depuis dix belvédères — mais tous ne conviennent pas à une demande. Ceux qui marchent, l'heure juste, et la logistique de la surprise.",
    "content": "## Le choix de départ : la vue ou l'intimité\n\nComme toute ville de collines, Lisbonne propose deux familles de lieux : les miradouros — panoramas sur le Tage, mais fréquentés au coucher du soleil — et les coins discrets, jardins et ruelles, où la surprise reste entre vous. La bonne réponse dépend d'une seule chose : comment votre partenaire vit un public qui applaudit.\n\n## Les lieux qui marchent\n\n**Le Miradouro da Senhora do Monte, en semaine, 40 minutes avant le coucher.** Le plus haut belvédère de la ville regarde le château et le fleuve plein ouest — le soleil tombe exactement dans l'axe. C'est aussi le plus couru au moment précis du couchant : d'où la règle des 40 minutes d'avance, quand la lumière est déjà dorée et la foule encore clairsemée.\n\n**Le Jardim da Cerca da Graça.** À cinq minutes du précédent, ce jardin en terrasses reste étonnamment calme : oliviers, pelouses, la ville en contrebas. L'option intimité avec vue — et le repli parfait si le miradouro déborde.\n\n**L'Alfama à l'aube.** Pour les couples du matin : les ruelles vides, la lumière rasante sur les azulejos de Santa Luzia, personne d'autre que le photographe déguisé en touriste. La demande la plus cinématographique de Lisbonne se fait à 7 h 30.\n\n**Le Parque Eduardo VII, en haut.** La perspective plonge vers le Tage entre les haies taillées — géométrique, dégagée, rarement bondée. L'option élégante à dix minutes du centre.\n\n**À écarter : le Miradouro de Santa Luzia au coucher.** Magnifique, mais sa pergola est étroite et les cars de tourisme y déversent leur monde précisément à l'heure dorée. Gardez-le pour les portraits d'après, à l'aube.\n\n## La logistique de la surprise\n\n- **Le photographe arrive avant vous**, en touriste, téléobjectif au cou — et vous envoie sa photo la veille pour que vous le reconnaissiez sans le chercher.\n- **Un signal simple** — retirer sa casquette, désigner le fleuve — déclenche la rafale.\n- **Le plan pluie s'écrit à l'avance :** les arcades de la Praça do Comércio ou le hall carrelé d'un palais — Lisbonne en offre plusieurs à dix minutes de chaque miradouro.\n- **La bague voyage sur vous**, dans une pochette plate — l'écrin classique se voit dans toutes les poches.\n\n## Après le oui\n\nComptez 30 à 60 minutes de portraits dans la foulée — de la Senhora do Monte on descend vers la Graça et ses ruelles ; de l'Alfama on remonte vers Portas do Sol quand la lumière grimpe. La [séance demande en mariage](/photoshoots/proposal) inclut le repérage du mètre exact ; pour construire le reste de la journée, la [page de Lisbonne](/locations/lisbon) donne les spots heure par heure.\n"
  },
  {
    "slug": "voyager-seul-portugal-reserver-photographe",
    "locale": "fr",
    "category": "solo",
    "published_at": "2026-08-05T10:00:00Z",
    "title": "Voyager seul au Portugal et réserver un photographe : mode d'emploi",
    "meta_title": "Voyage solo au Portugal : réserver un photographe",
    "meta_description": "Comment se passe une séance photo quand on voyage seul au Portugal : le déroulé, la sécurité, les villes où une heure rapporte le plus — et quoi demander.",
    "target_keywords": "voyage solo portugal photographe, seance photo voyageur seul, photographe personnel lisbonne porto, photos voyage solo",
    "excerpt": "Vous organisez le voyage seul — les photos ne devraient pas être des selfies. Le déroulé d'une séance solo au Portugal, et où une heure rapporte le plus.",
    "content": "## La seule chose que le voyage solo ne donne pas\n\nVous planifiez l'itinéraire, prenez les trains, dînez seul face au monde — et rentrez avec deux cents photos de bâtiments et quatre selfies ratés. Une séance solo corrige l'asymétrie : pendant une heure, quelqu'un dont le métier est la lumière et le cadrage marche dans votre ville avec vous, et vous voilà DANS le voyage que vous avez organisé.\n\n## Comment ça se passe vraiment\n\nLes dix premières minutes sont gauches pour tout le monde — c'est normal et prévu. Un bon photographe commence par le mouvement plutôt que la pose : marcher vers l'objectif, traverser une place, regarder une vitrine. À la quinzième minute, la plupart des gens oublient l'appareil ; à la fin, le retour le plus fréquent est « c'était vraiment agréable » — venant précisément des gens qui avaient écrit « je suis très mal à l'aise en photo » dans les notes de réservation.\n\nEt vous gagnez une deuxième chose : un local. Les photographes savent quelle ruelle est vide à 8 h, où le café est bon, quel belvédère mérite la montée. Beaucoup de voyageurs solo traitent la séance comme une heure guidée avec preuves photographiques.\n\n## Où une heure rapporte le plus\n\n- **Lisbonne** — l'aube dans l'Alfama : ruelles vides, azulejos dorés, le tram 28 qui passe en décor. La séance solo classique du Portugal.\n- **Porto** — l'économie de la marche : Ribeira, pont Luís I et rive de Gaia dans un seul arc à pied, avec le panorama en récompense finale.\n- **Sintra** — pour l'imaginaire : palais et forêts, à condition de viser l'ouverture des sites, avant les cars.\n- **L'Algarve** — falaises dorées et plages au couchant ; la séance solo la plus spectaculaire, à condition d'accepter le vent dans les cheveux comme co-auteur.\n\n## La sécurité, puisqu'on rencontre un inconnu\n\nRéserver par une plateforme signifie : photographe vérifié, avis de clients précédents, paiement séquestré plutôt que remis en liquide, échanges conservés, rendez-vous en lieu public convenu d'avance. Exactement les garanties qu'un DM Instagram ne donne pas.\n\n## Quoi demander, quoi apporter\n\nDemandez les deux formats (vertical pour les stories, horizontal pour le reste) et un vrai portrait serré par tenue. Apportez une tenue dans laquelle vous vous sentez bien, une de rechange qui se plie petit, des chaussures confortables — la paire photogénique dans le sac. Au Portugal, la ville est l'accessoire : inutile d'en apporter d'autres.\n\nLa [page des séances solo](/photoshoots/solo) liste photographes et tarifs ; et si une partie des photos doit servir un profil professionnel, dites-le en réservant — le photographe intégrera un arrêt « LinkedIn » dans l'itinéraire.\n"
  },
  {
    "slug": "photographe-mariage-portugal-questions",
    "locale": "fr",
    "category": "weddings",
    "published_at": "2026-08-06T10:00:00Z",
    "title": "Photographe de mariage au Portugal : les questions à poser avant de signer",
    "meta_title": "Photographe de mariage au Portugal : questions",
    "meta_description": "Heures réelles, second photographe, déplacements Lisbonne-Algarve, délais de livraison, droits d'image et plan vent — le devis portugais rendu lisible.",
    "target_keywords": "photographe mariage portugal questions, que demander photographe mariage portugal, mariage portugal photographe, contrat photographe mariage portugal",
    "excerpt": "Le devis semble parfait jusqu'aux questions sur les heures, les droits et le vent de l'Atlantique. Douze questions qui rendent un devis portugais lisible.",
    "content": "## Demandez pendant que tout le monde est charmant\n\nLes déceptions en photo de mariage commencent toujours pareil : personne n'a osé demander pendant que tout le monde était adorable. Un bon photographe répond à ces douze questions sans ciller — et celui qui cille a répondu aussi.\n\n## La journée\n\n**1. Combien d'heures réelles ?** Des préparatifs à la première danse, un mariage au Portugal court sur 10 à 12 heures. Si la formule en couvre huit, demandez le tarif de l'heure supplémentaire maintenant — pas à 23 heures le jour J.\n\n**2. Qui photographie, nommément ?** Les studios remplacent ; le contrat l'empêche. Demandez un mariage COMPLET photographié par la personne nommée, pas la vitrine du studio.\n\n**3. Second photographe : inclus ?** Au-delà de 80 invités — ou quand les préparatifs se font à deux endroits, fréquent dans les quintas — le second angle transforme la couverture en récit.\n\n**4. Quel est le plan vent ?** La spécificité portugaise : un mariage face à l'Atlantique — falaises de l'Algarve, Ericeira, Comporta — vit avec le vent. Voiles, coiffures, arches de fleurs : un photographe qui a shooté la côte en parle de lui-même, avec les heures où le vent tombe.\n\n## L'argent\n\n**5. Les déplacements.** Lisbonne–Algarve, c'est trois heures de route : la ligne déplacement (et parfois la nuit d'hôtel) appartient au devis, pas à la surprise.\n\n**6. Acompte et solde.** Standard portugais : 20 à 30 % à la réservation, le solde autour du jour J. Tout d'avance est un signal.\n\n**7. Annulation et report, en trois scénarios écrits.** Vous annulez ; vous reportez (l'acompte suit-il ?) ; le photographe annule — avec sa solution de remplacement.\n\n## Les photos\n\n**8. Combien, et sous quel délai ?** Une journée complète : 400 à 800 images livrées. Délai honnête en haute saison : 4 à 8 semaines, avec un aperçu sous quelques jours — nombre et date de l'aperçu par écrit.\n\n**9. Que veut dire « retouchée » ?** Couleur et exposition sur tout, retouche de peau sur une sélection. Demandez une paire avant-après.\n\n**10. Les droits.** Usage personnel illimité par écrit ; et si vous ne voulez pas paraître dans son portfolio, la confidentialité se négocie maintenant, pas après publication.\n\n## Le lieu\n\n**11. Connaissez-vous la quinta — ou irez-vous en repérage ?** Des palais de Sintra aux caves à vin de la vallée du Douro, chaque lieu portugais a sa lumière piège. Un repérage se voit ensuite dans chaque image.\n\n**12. Comment dirigez-vous les gens ?** Mise en scène ou documentaire — aucun des deux n'est faux, mais le décalage d'attentes est la première source de déception. Montrez les mariages de son portfolio qui ressemblent au vôtre.\n\nLes portfolios vérifiés vivent sur la [page mariage](/weddings) ; et si votre mariage tient sur une terrasse à vingt, le format honnête est l'[elopement](/photoshoots/elopement) — mêmes questions, journée plus courte.\n"
  }
]
